<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create(['id'=>1,'ciudad'=>'Abriaquí','id_departamento'=>5]);
        City::create(['id'=>2,'ciudad'=>'Acacías','id_departamento'=>50]);
        City::create(['id'=>3,'ciudad'=>'Acandí','id_departamento'=>27]);
        City::create(['id'=>4,'ciudad'=>'Acevedo','id_departamento'=>41]);
        City::create(['id'=>5,'ciudad'=>'Achí','id_departamento'=>13]);
        City::create(['id'=>6,'ciudad'=>'Agrado','id_departamento'=>41]);
        City::create(['id'=>7,'ciudad'=>'Agua de Dios','id_departamento'=>25]);
        City::create(['id'=>8,'ciudad'=>'Aguachica','id_departamento'=>20]);
        City::create(['id'=>9,'ciudad'=>'Aguada','id_departamento'=>68]);
        City::create(['id'=>10,'ciudad'=>'Aguadas','id_departamento'=>17]);
        City::create(['id'=>11,'ciudad'=>'Aguazul','id_departamento'=>85]);
        City::create(['id'=>12,'ciudad'=>'Agustín Codazzi','id_departamento'=>20]);
        City::create(['id'=>13,'ciudad'=>'Aipe','id_departamento'=>41]);
        City::create(['id'=>14,'ciudad'=>'Albania','id_departamento'=>18]);
        City::create(['id'=>15,'ciudad'=>'Albania','id_departamento'=>44]);
        City::create(['id'=>16,'ciudad'=>'Albania','id_departamento'=>68]);
        City::create(['id'=>17,'ciudad'=>'Albán','id_departamento'=>25]);
        City::create(['id'=>18,'ciudad'=>'Albán (San José)','id_departamento'=>52]);
        City::create(['id'=>19,'ciudad'=>'Alcalá','id_departamento'=>76]);
        City::create(['id'=>20,'ciudad'=>'Alejandria','id_departamento'=>5]);
        City::create(['id'=>21,'ciudad'=>'Algarrobo','id_departamento'=>47]);
        City::create(['id'=>22,'ciudad'=>'Algeciras','id_departamento'=>41]);
        City::create(['id'=>23,'ciudad'=>'Almaguer','id_departamento'=>19]);
        City::create(['id'=>24,'ciudad'=>'Almeida','id_departamento'=>15]);
        City::create(['id'=>25,'ciudad'=>'Alpujarra','id_departamento'=>73]);
        City::create(['id'=>26,'ciudad'=>'Altamira','id_departamento'=>41]);
        City::create(['id'=>27,'ciudad'=>'Alto Baudó (Pie de Pato)','id_departamento'=>27]);
        City::create(['id'=>28,'ciudad'=>'Altos del Rosario','id_departamento'=>13]);
        City::create(['id'=>29,'ciudad'=>'Alvarado','id_departamento'=>73]);
        City::create(['id'=>30,'ciudad'=>'Amagá','id_departamento'=>5]);
        City::create(['id'=>31,'ciudad'=>'Amalfi','id_departamento'=>5]);
        City::create(['id'=>32,'ciudad'=>'Ambalema','id_departamento'=>73]);
        City::create(['id'=>33,'ciudad'=>'Anapoima','id_departamento'=>25]);
        City::create(['id'=>34,'ciudad'=>'Ancuya','id_departamento'=>52]);
        City::create(['id'=>35,'ciudad'=>'Andalucía','id_departamento'=>76]);
        City::create(['id'=>36,'ciudad'=>'Andes','id_departamento'=>5]);
        City::create(['id'=>37,'ciudad'=>'Angelópolis','id_departamento'=>5]);
        City::create(['id'=>38,'ciudad'=>'Angostura','id_departamento'=>5]);
        City::create(['id'=>39,'ciudad'=>'Anolaima','id_departamento'=>25]);
        City::create(['id'=>40,'ciudad'=>'Anorí','id_departamento'=>5]);
        City::create(['id'=>41,'ciudad'=>'Anserma','id_departamento'=>17]);
        City::create(['id'=>42,'ciudad'=>'Ansermanuevo','id_departamento'=>76]);
        City::create(['id'=>43,'ciudad'=>'Anzoátegui','id_departamento'=>73]);
        City::create(['id'=>44,'ciudad'=>'Anzá','id_departamento'=>5]);
        City::create(['id'=>45,'ciudad'=>'Apartadó','id_departamento'=>5]);
        City::create(['id'=>46,'ciudad'=>'Apulo','id_departamento'=>25]);
        City::create(['id'=>47,'ciudad'=>'Apía','id_departamento'=>66]);
        City::create(['id'=>48,'ciudad'=>'Aquitania','id_departamento'=>15]);
        City::create(['id'=>49,'ciudad'=>'Aracataca','id_departamento'=>47]);
        City::create(['id'=>50,'ciudad'=>'Aranzazu','id_departamento'=>17]);
        City::create(['id'=>51,'ciudad'=>'Aratoca','id_departamento'=>68]);
        City::create(['id'=>52,'ciudad'=>'Arauca','id_departamento'=>81]);
        City::create(['id'=>53,'ciudad'=>'Arauquita','id_departamento'=>81]);
        City::create(['id'=>54,'ciudad'=>'Arbeláez','id_departamento'=>25]);
        City::create(['id'=>55,'ciudad'=>'Arboleda (Berruecos)','id_departamento'=>52]);
        City::create(['id'=>56,'ciudad'=>'Arboledas','id_departamento'=>54]);
        City::create(['id'=>57,'ciudad'=>'Arboletes','id_departamento'=>5]);
        City::create(['id'=>58,'ciudad'=>'Arcabuco','id_departamento'=>15]);
        City::create(['id'=>59,'ciudad'=>'Arenal','id_departamento'=>13]);
        City::create(['id'=>60,'ciudad'=>'Argelia','id_departamento'=>5]);
        City::create(['id'=>61,'ciudad'=>'Argelia','id_departamento'=>19]);
        City::create(['id'=>62,'ciudad'=>'Argelia','id_departamento'=>76]);
        City::create(['id'=>63,'ciudad'=>'Ariguaní (El Difícil)','id_departamento'=>47]);
        City::create(['id'=>64,'ciudad'=>'Arjona','id_departamento'=>13]);
        City::create(['id'=>65,'ciudad'=>'Armenia','id_departamento'=>5]);
        City::create(['id'=>66,'ciudad'=>'Armenia','id_departamento'=>63]);
        City::create(['id'=>67,'ciudad'=>'Armero (Guayabal)','id_departamento'=>73]);
        City::create(['id'=>68,'ciudad'=>'Arroyohondo','id_departamento'=>13]);
        City::create(['id'=>69,'ciudad'=>'Astrea','id_departamento'=>20]);
        City::create(['id'=>70,'ciudad'=>'Ataco','id_departamento'=>73]);
        City::create(['id'=>71,'ciudad'=>'Atrato (Yuto)','id_departamento'=>27]);
        City::create(['id'=>72,'ciudad'=>'Ayapel','id_departamento'=>23]);
        City::create(['id'=>73,'ciudad'=>'Bagadó','id_departamento'=>27]);
        City::create(['id'=>74,'ciudad'=>'Bahía Solano (Mútis)','id_departamento'=>27]);
        City::create(['id'=>75,'ciudad'=>'Bajo Baudó (Pizarro)','id_departamento'=>27]);
        City::create(['id'=>76,'ciudad'=>'Balboa','id_departamento'=>19]);
        City::create(['id'=>77,'ciudad'=>'Balboa','id_departamento'=>66]);
        City::create(['id'=>78,'ciudad'=>'Baranoa','id_departamento'=>8]);
        City::create(['id'=>79,'ciudad'=>'Baraya','id_departamento'=>41]);
        City::create(['id'=>80,'ciudad'=>'Barbacoas','id_departamento'=>52]);
        City::create(['id'=>81,'ciudad'=>'Barbosa','id_departamento'=>5]);
        City::create(['id'=>82,'ciudad'=>'Barbosa','id_departamento'=>68]);
        City::create(['id'=>83,'ciudad'=>'Barichara','id_departamento'=>68]);
        City::create(['id'=>84,'ciudad'=>'Barranca de Upía','id_departamento'=>50]);
        City::create(['id'=>85,'ciudad'=>'Barrancabermeja','id_departamento'=>68]);
        City::create(['id'=>86,'ciudad'=>'Barrancas','id_departamento'=>44]);
        City::create(['id'=>87,'ciudad'=>'Barranco de Loba','id_departamento'=>13]);
        City::create(['id'=>88,'ciudad'=>'Barranquilla','id_departamento'=>8]);
        City::create(['id'=>89,'ciudad'=>'Becerríl','id_departamento'=>20]);
        City::create(['id'=>90,'ciudad'=>'Belalcázar','id_departamento'=>17]);
        City::create(['id'=>91,'ciudad'=>'Bello','id_departamento'=>5]);
        City::create(['id'=>92,'ciudad'=>'Belmira','id_departamento'=>5]);
        City::create(['id'=>93,'ciudad'=>'Beltrán','id_departamento'=>25]);
        City::create(['id'=>94,'ciudad'=>'Belén','id_departamento'=>15]);
        City::create(['id'=>95,'ciudad'=>'Belén','id_departamento'=>52]);
        City::create(['id'=>96,'ciudad'=>'Belén de Bajirá','id_departamento'=>27]);
        City::create(['id'=>97,'ciudad'=>'Belén de Umbría','id_departamento'=>66]);
        City::create(['id'=>98,'ciudad'=>'Belén de los Andaquíes','id_departamento'=>18]);
        City::create(['id'=>99,'ciudad'=>'Berbeo','id_departamento'=>15]);
        City::create(['id'=>100,'ciudad'=>'Betania','id_departamento'=>5]);
        City::create(['id'=>101,'ciudad'=>'Beteitiva','id_departamento'=>15]);
        City::create(['id'=>102,'ciudad'=>'Betulia','id_departamento'=>5]);
        City::create(['id'=>103,'ciudad'=>'Betulia','id_departamento'=>68]);
        City::create(['id'=>104,'ciudad'=>'Bituima','id_departamento'=>25]);
        City::create(['id'=>105,'ciudad'=>'Boavita','id_departamento'=>15]);
        City::create(['id'=>106,'ciudad'=>'Bochalema','id_departamento'=>54]);
        City::create(['id'=>107,'ciudad'=>'Bogotá D.C.','id_departamento'=>11]);
        City::create(['id'=>108,'ciudad'=>'Bojacá','id_departamento'=>25]);
        City::create(['id'=>109,'ciudad'=>'Bojayá (Bellavista)','id_departamento'=>27]);
        City::create(['id'=>110,'ciudad'=>'Bolívar','id_departamento'=>5]);
        City::create(['id'=>111,'ciudad'=>'Bolívar','id_departamento'=>19]);
        City::create(['id'=>112,'ciudad'=>'Bolívar','id_departamento'=>68]);
        City::create(['id'=>113,'ciudad'=>'Bolívar','id_departamento'=>76]);
        City::create(['id'=>114,'ciudad'=>'Bosconia','id_departamento'=>20]);
        City::create(['id'=>115,'ciudad'=>'Boyacá','id_departamento'=>15]);
        City::create(['id'=>116,'ciudad'=>'Briceño','id_departamento'=>5]);
        City::create(['id'=>117,'ciudad'=>'Briceño','id_departamento'=>15]);
        City::create(['id'=>118,'ciudad'=>'Bucaramanga','id_departamento'=>68]);
        City::create(['id'=>119,'ciudad'=>'Bucarasica','id_departamento'=>54]);
        City::create(['id'=>120,'ciudad'=>'Buenaventura','id_departamento'=>76]);
        City::create(['id'=>121,'ciudad'=>'Buenavista','id_departamento'=>15]);
        City::create(['id'=>122,'ciudad'=>'Buenavista','id_departamento'=>23]);
        City::create(['id'=>123,'ciudad'=>'Buenavista','id_departamento'=>63]);
        City::create(['id'=>124,'ciudad'=>'Buenavista','id_departamento'=>70]);
        City::create(['id'=>125,'ciudad'=>'Buenos Aires','id_departamento'=>19]);
        City::create(['id'=>126,'ciudad'=>'Buesaco','id_departamento'=>52]);
        City::create(['id'=>127,'ciudad'=>'Buga','id_departamento'=>76]);
        City::create(['id'=>128,'ciudad'=>'Bugalagrande','id_departamento'=>76]);
        City::create(['id'=>129,'ciudad'=>'Burítica','id_departamento'=>5]);
        City::create(['id'=>130,'ciudad'=>'Busbanza','id_departamento'=>15]);
        City::create(['id'=>131,'ciudad'=>'Cabrera','id_departamento'=>25]);
        City::create(['id'=>132,'ciudad'=>'Cabrera','id_departamento'=>68]);
        City::create(['id'=>133,'ciudad'=>'Cabuyaro','id_departamento'=>50]);
        City::create(['id'=>134,'ciudad'=>'Cachipay','id_departamento'=>25]);
        City::create(['id'=>135,'ciudad'=>'Caicedo','id_departamento'=>5]);
        City::create(['id'=>136,'ciudad'=>'Caicedonia','id_departamento'=>76]);
        City::create(['id'=>137,'ciudad'=>'Caimito','id_departamento'=>70]);
        City::create(['id'=>138,'ciudad'=>'Cajamarca','id_departamento'=>73]);
        City::create(['id'=>139,'ciudad'=>'Cajibío','id_departamento'=>19]);
        City::create(['id'=>140,'ciudad'=>'Cajicá','id_departamento'=>25]);
        City::create(['id'=>141,'ciudad'=>'Calamar','id_departamento'=>13]);
        City::create(['id'=>142,'ciudad'=>'Calamar','id_departamento'=>95]);
        City::create(['id'=>143,'ciudad'=>'Calarcá','id_departamento'=>63]);
        City::create(['id'=>144,'ciudad'=>'Caldas','id_departamento'=>5]);
        City::create(['id'=>145,'ciudad'=>'Caldas','id_departamento'=>15]);
        City::create(['id'=>146,'ciudad'=>'Caldono','id_departamento'=>19]);
        City::create(['id'=>147,'ciudad'=>'California','id_departamento'=>68]);
        City::create(['id'=>148,'ciudad'=>'Calima (Darién)','id_departamento'=>76]);
        City::create(['id'=>149,'ciudad'=>'Caloto','id_departamento'=>19]);
        City::create(['id'=>150,'ciudad'=>'Calí','id_departamento'=>76]);
        City::create(['id'=>151,'ciudad'=>'Campamento','id_departamento'=>5]);
        City::create(['id'=>152,'ciudad'=>'Campo de la Cruz','id_departamento'=>8]);
        City::create(['id'=>153,'ciudad'=>'Campoalegre','id_departamento'=>41]);
        City::create(['id'=>154,'ciudad'=>'Campohermoso','id_departamento'=>15]);
        City::create(['id'=>155,'ciudad'=>'Canalete','id_departamento'=>23]);
        City::create(['id'=>156,'ciudad'=>'Candelaria','id_departamento'=>8]);
        City::create(['id'=>157,'ciudad'=>'Candelaria','id_departamento'=>76]);
        City::create(['id'=>158,'ciudad'=>'Cantagallo','id_departamento'=>13]);
        City::create(['id'=>159,'ciudad'=>'Cantón de San Pablo','id_departamento'=>27]);
        City::create(['id'=>160,'ciudad'=>'Caparrapí','id_departamento'=>25]);
        City::create(['id'=>161,'ciudad'=>'Capitanejo','id_departamento'=>68]);
        City::create(['id'=>162,'ciudad'=>'Caracolí','id_departamento'=>5]);
        City::create(['id'=>163,'ciudad'=>'Caramanta','id_departamento'=>5]);
        City::create(['id'=>164,'ciudad'=>'Carcasí','id_departamento'=>68]);
        City::create(['id'=>165,'ciudad'=>'Carepa','id_departamento'=>5]);
        City::create(['id'=>166,'ciudad'=>'Carmen de Apicalá','id_departamento'=>73]);
        City::create(['id'=>167,'ciudad'=>'Carmen de Carupa','id_departamento'=>25]);
        City::create(['id'=>168,'ciudad'=>'Carmen de Viboral','id_departamento'=>5]);
        City::create(['id'=>169,'ciudad'=>'Carmen del Darién (CURBARADÓ)','id_departamento'=>27]);
        City::create(['id'=>170,'ciudad'=>'Carolina','id_departamento'=>5]);
        City::create(['id'=>171,'ciudad'=>'Cartagena','id_departamento'=>13]);
        City::create(['id'=>172,'ciudad'=>'Cartagena del Chairá','id_departamento'=>18]);
        City::create(['id'=>173,'ciudad'=>'Cartago','id_departamento'=>76]);
        City::create(['id'=>174,'ciudad'=>'Carurú','id_departamento'=>97]);
        City::create(['id'=>175,'ciudad'=>'Casabianca','id_departamento'=>73]);
        City::create(['id'=>176,'ciudad'=>'Castilla la Nueva','id_departamento'=>50]);
        City::create(['id'=>177,'ciudad'=>'Caucasia','id_departamento'=>5]);
        City::create(['id'=>178,'ciudad'=>'Cañasgordas','id_departamento'=>5]);
        City::create(['id'=>179,'ciudad'=>'Cepita','id_departamento'=>68]);
        City::create(['id'=>180,'ciudad'=>'Cereté','id_departamento'=>23]);
        City::create(['id'=>181,'ciudad'=>'Cerinza','id_departamento'=>15]);
        City::create(['id'=>182,'ciudad'=>'Cerrito','id_departamento'=>68]);
        City::create(['id'=>183,'ciudad'=>'Cerro San Antonio','id_departamento'=>47]);
        City::create(['id'=>184,'ciudad'=>'Chachaguí','id_departamento'=>52]);
        City::create(['id'=>185,'ciudad'=>'Chaguaní','id_departamento'=>25]);
        City::create(['id'=>186,'ciudad'=>'Chalán','id_departamento'=>70]);
        City::create(['id'=>187,'ciudad'=>'Chaparral','id_departamento'=>73]);
        City::create(['id'=>188,'ciudad'=>'Charalá','id_departamento'=>68]);
        City::create(['id'=>189,'ciudad'=>'Charta','id_departamento'=>68]);
        City::create(['id'=>190,'ciudad'=>'Chigorodó','id_departamento'=>5]);
        City::create(['id'=>191,'ciudad'=>'Chima','id_departamento'=>68]);
        City::create(['id'=>192,'ciudad'=>'Chimichagua','id_departamento'=>20]);
        City::create(['id'=>193,'ciudad'=>'Chimá','id_departamento'=>23]);
        City::create(['id'=>194,'ciudad'=>'Chinavita','id_departamento'=>15]);
        City::create(['id'=>195,'ciudad'=>'Chinchiná','id_departamento'=>17]);
        City::create(['id'=>196,'ciudad'=>'Chinácota','id_departamento'=>54]);
        City::create(['id'=>197,'ciudad'=>'Chinú','id_departamento'=>23]);
        City::create(['id'=>198,'ciudad'=>'Chipaque','id_departamento'=>25]);
        City::create(['id'=>199,'ciudad'=>'Chipatá','id_departamento'=>68]);
        City::create(['id'=>200,'ciudad'=>'Chiquinquirá','id_departamento'=>15]);
        City::create(['id'=>201,'ciudad'=>'Chiriguaná','id_departamento'=>20]);
        City::create(['id'=>202,'ciudad'=>'Chiscas','id_departamento'=>15]);
        City::create(['id'=>203,'ciudad'=>'Chita','id_departamento'=>15]);
        City::create(['id'=>204,'ciudad'=>'Chitagá','id_departamento'=>54]);
        City::create(['id'=>205,'ciudad'=>'Chitaraque','id_departamento'=>15]);
        City::create(['id'=>206,'ciudad'=>'Chivatá','id_departamento'=>15]);
        City::create(['id'=>207,'ciudad'=>'Chivolo','id_departamento'=>47]);
        City::create(['id'=>208,'ciudad'=>'Choachí','id_departamento'=>25]);
        City::create(['id'=>209,'ciudad'=>'Chocontá','id_departamento'=>25]);
        City::create(['id'=>210,'ciudad'=>'Chámeza','id_departamento'=>85]);
        City::create(['id'=>211,'ciudad'=>'Chía','id_departamento'=>25]);
        City::create(['id'=>212,'ciudad'=>'Chíquiza','id_departamento'=>15]);
        City::create(['id'=>213,'ciudad'=>'Chívor','id_departamento'=>15]);
        City::create(['id'=>214,'ciudad'=>'Cicuco','id_departamento'=>13]);
        City::create(['id'=>215,'ciudad'=>'Cimitarra','id_departamento'=>68]);
        City::create(['id'=>216,'ciudad'=>'Circasia','id_departamento'=>63]);
        City::create(['id'=>217,'ciudad'=>'Cisneros','id_departamento'=>5]);
        City::create(['id'=>218,'ciudad'=>'Ciénaga','id_departamento'=>15]);
        City::create(['id'=>219,'ciudad'=>'Ciénaga','id_departamento'=>47]);
        City::create(['id'=>220,'ciudad'=>'Ciénaga de Oro','id_departamento'=>23]);
        City::create(['id'=>221,'ciudad'=>'Clemencia','id_departamento'=>13]);
        City::create(['id'=>222,'ciudad'=>'Cocorná','id_departamento'=>5]);
        City::create(['id'=>223,'ciudad'=>'Coello','id_departamento'=>73]);
        City::create(['id'=>224,'ciudad'=>'Cogua','id_departamento'=>25]);
        City::create(['id'=>225,'ciudad'=>'Colombia','id_departamento'=>41]);
        City::create(['id'=>226,'ciudad'=>'Colosó (Ricaurte)','id_departamento'=>70]);
        City::create(['id'=>227,'ciudad'=>'Colón','id_departamento'=>86]);
        City::create(['id'=>228,'ciudad'=>'Colón (Génova)','id_departamento'=>52]);
        City::create(['id'=>229,'ciudad'=>'Concepción','id_departamento'=>5]);
        City::create(['id'=>230,'ciudad'=>'Concepción','id_departamento'=>68]);
        City::create(['id'=>231,'ciudad'=>'Concordia','id_departamento'=>5]);
        City::create(['id'=>232,'ciudad'=>'Concordia','id_departamento'=>47]);
        City::create(['id'=>233,'ciudad'=>'Condoto','id_departamento'=>27]);
        City::create(['id'=>234,'ciudad'=>'Confines','id_departamento'=>68]);
        City::create(['id'=>235,'ciudad'=>'Consaca','id_departamento'=>52]);
        City::create(['id'=>236,'ciudad'=>'Contadero','id_departamento'=>52]);
        City::create(['id'=>237,'ciudad'=>'Contratación','id_departamento'=>68]);
        City::create(['id'=>238,'ciudad'=>'Convención','id_departamento'=>54]);
        City::create(['id'=>239,'ciudad'=>'Copacabana','id_departamento'=>5]);
        City::create(['id'=>240,'ciudad'=>'Coper','id_departamento'=>15]);
        City::create(['id'=>241,'ciudad'=>'Cordobá','id_departamento'=>63]);
        City::create(['id'=>242,'ciudad'=>'Corinto','id_departamento'=>19]);
        City::create(['id'=>243,'ciudad'=>'Coromoro','id_departamento'=>68]);
        City::create(['id'=>244,'ciudad'=>'Corozal','id_departamento'=>70]);
        City::create(['id'=>245,'ciudad'=>'Corrales','id_departamento'=>15]);
        City::create(['id'=>246,'ciudad'=>'Cota','id_departamento'=>25]);
        City::create(['id'=>247,'ciudad'=>'Cotorra','id_departamento'=>23]);
        City::create(['id'=>248,'ciudad'=>'Covarachía','id_departamento'=>15]);
        City::create(['id'=>249,'ciudad'=>'Coveñas','id_departamento'=>70]);
        City::create(['id'=>250,'ciudad'=>'Coyaima','id_departamento'=>73]);
        City::create(['id'=>251,'ciudad'=>'Cravo Norte','id_departamento'=>81]);
        City::create(['id'=>252,'ciudad'=>'Cuaspud (Carlosama)','id_departamento'=>52]);
        City::create(['id'=>253,'ciudad'=>'Cubarral','id_departamento'=>50]);
        City::create(['id'=>254,'ciudad'=>'Cubará','id_departamento'=>15]);
        City::create(['id'=>255,'ciudad'=>'Cucaita','id_departamento'=>15]);
        City::create(['id'=>256,'ciudad'=>'Cucunubá','id_departamento'=>25]);
        City::create(['id'=>257,'ciudad'=>'Cucutilla','id_departamento'=>54]);
        City::create(['id'=>258,'ciudad'=>'Cuitiva','id_departamento'=>15]);
        City::create(['id'=>259,'ciudad'=>'Cumaral','id_departamento'=>50]);
        City::create(['id'=>260,'ciudad'=>'Cumaribo','id_departamento'=>99]);
        City::create(['id'=>261,'ciudad'=>'Cumbal','id_departamento'=>52]);
        City::create(['id'=>262,'ciudad'=>'Cumbitara','id_departamento'=>52]);
        City::create(['id'=>263,'ciudad'=>'Cunday','id_departamento'=>73]);
        City::create(['id'=>264,'ciudad'=>'Curillo','id_departamento'=>18]);
        City::create(['id'=>265,'ciudad'=>'Curití','id_departamento'=>68]);
        City::create(['id'=>266,'ciudad'=>'Curumaní','id_departamento'=>20]);
        City::create(['id'=>267,'ciudad'=>'Cáceres','id_departamento'=>5]);
        City::create(['id'=>268,'ciudad'=>'Cáchira','id_departamento'=>54]);
        City::create(['id'=>269,'ciudad'=>'Cácota','id_departamento'=>54]);
        City::create(['id'=>270,'ciudad'=>'Cáqueza','id_departamento'=>25]);
        City::create(['id'=>271,'ciudad'=>'Cértegui','id_departamento'=>27]);
        City::create(['id'=>272,'ciudad'=>'Cómbita','id_departamento'=>15]);
        City::create(['id'=>273,'ciudad'=>'Córdoba','id_departamento'=>13]);
        City::create(['id'=>274,'ciudad'=>'Córdoba','id_departamento'=>52]);
        City::create(['id'=>275,'ciudad'=>'Cúcuta','id_departamento'=>54]);
        City::create(['id'=>276,'ciudad'=>'Dabeiba','id_departamento'=>5]);
        City::create(['id'=>277,'ciudad'=>'Dagua','id_departamento'=>76]);
        City::create(['id'=>278,'ciudad'=>'Dibulla','id_departamento'=>44]);
        City::create(['id'=>279,'ciudad'=>'Distracción','id_departamento'=>44]);
        City::create(['id'=>280,'ciudad'=>'Dolores','id_departamento'=>73]);
        City::create(['id'=>281,'ciudad'=>'Don Matías','id_departamento'=>5]);
        City::create(['id'=>282,'ciudad'=>'Dos Quebradas','id_departamento'=>66]);
        City::create(['id'=>283,'ciudad'=>'Duitama','id_departamento'=>15]);
        City::create(['id'=>284,'ciudad'=>'Durania','id_departamento'=>54]);
        City::create(['id'=>285,'ciudad'=>'Ebéjico','id_departamento'=>5]);
        City::create(['id'=>286,'ciudad'=>'El Bagre','id_departamento'=>5]);
        City::create(['id'=>287,'ciudad'=>'El Banco','id_departamento'=>47]);
        City::create(['id'=>288,'ciudad'=>'El Cairo','id_departamento'=>76]);
        City::create(['id'=>289,'ciudad'=>'El Calvario','id_departamento'=>50]);
        City::create(['id'=>290,'ciudad'=>'El Carmen','id_departamento'=>54]);
        City::create(['id'=>291,'ciudad'=>'El Carmen','id_departamento'=>68]);
        City::create(['id'=>292,'ciudad'=>'El Carmen de Atrato','id_departamento'=>27]);
        City::create(['id'=>293,'ciudad'=>'El Carmen de Bolívar','id_departamento'=>13]);
        City::create(['id'=>294,'ciudad'=>'El Castillo','id_departamento'=>50]);
        City::create(['id'=>295,'ciudad'=>'El Cerrito','id_departamento'=>76]);
        City::create(['id'=>296,'ciudad'=>'El Charco','id_departamento'=>52]);
        City::create(['id'=>297,'ciudad'=>'El Cocuy','id_departamento'=>15]);
        City::create(['id'=>298,'ciudad'=>'El Colegio','id_departamento'=>25]);
        City::create(['id'=>299,'ciudad'=>'El Copey','id_departamento'=>20]);
        City::create(['id'=>300,'ciudad'=>'El Doncello','id_departamento'=>18]);
        City::create(['id'=>301,'ciudad'=>'El Dorado','id_departamento'=>50]);
        City::create(['id'=>302,'ciudad'=>'El Dovio','id_departamento'=>76]);
        City::create(['id'=>303,'ciudad'=>'El Espino','id_departamento'=>15]);
        City::create(['id'=>304,'ciudad'=>'El Guacamayo','id_departamento'=>68]);
        City::create(['id'=>305,'ciudad'=>'El Guamo','id_departamento'=>13]);
        City::create(['id'=>306,'ciudad'=>'El Molino','id_departamento'=>44]);
        City::create(['id'=>307,'ciudad'=>'El Paso','id_departamento'=>20]);
        City::create(['id'=>308,'ciudad'=>'El Paujil','id_departamento'=>18]);
        City::create(['id'=>309,'ciudad'=>'El Peñol','id_departamento'=>52]);
        City::create(['id'=>310,'ciudad'=>'El Peñon','id_departamento'=>13]);
        City::create(['id'=>311,'ciudad'=>'El Peñon','id_departamento'=>68]);
        City::create(['id'=>312,'ciudad'=>'El Peñón','id_departamento'=>25]);
        City::create(['id'=>313,'ciudad'=>'El Piñon','id_departamento'=>47]);
        City::create(['id'=>314,'ciudad'=>'El Playón','id_departamento'=>68]);
        City::create(['id'=>315,'ciudad'=>'El Retorno','id_departamento'=>95]);
        City::create(['id'=>316,'ciudad'=>'El Retén','id_departamento'=>47]);
        City::create(['id'=>317,'ciudad'=>'El Roble','id_departamento'=>70]);
        City::create(['id'=>318,'ciudad'=>'El Rosal','id_departamento'=>25]);
        City::create(['id'=>319,'ciudad'=>'El Rosario','id_departamento'=>52]);
        City::create(['id'=>320,'ciudad'=>'El Tablón de Gómez','id_departamento'=>52]);
        City::create(['id'=>321,'ciudad'=>'El Tambo','id_departamento'=>19]);
        City::create(['id'=>322,'ciudad'=>'El Tambo','id_departamento'=>52]);
        City::create(['id'=>323,'ciudad'=>'El Tarra','id_departamento'=>54]);
        City::create(['id'=>324,'ciudad'=>'El Zulia','id_departamento'=>54]);
        City::create(['id'=>325,'ciudad'=>'El Águila','id_departamento'=>76]);
        City::create(['id'=>326,'ciudad'=>'Elías','id_departamento'=>41]);
        City::create(['id'=>327,'ciudad'=>'Encino','id_departamento'=>68]);
        City::create(['id'=>328,'ciudad'=>'Enciso','id_departamento'=>68]);
        City::create(['id'=>329,'ciudad'=>'Entrerríos','id_departamento'=>5]);
        City::create(['id'=>330,'ciudad'=>'Envigado','id_departamento'=>5]);
        City::create(['id'=>331,'ciudad'=>'Espinal','id_departamento'=>73]);
        City::create(['id'=>332,'ciudad'=>'Facatativá','id_departamento'=>25]);
        City::create(['id'=>333,'ciudad'=>'Falan','id_departamento'=>73]);
        City::create(['id'=>334,'ciudad'=>'Filadelfia','id_departamento'=>17]);
        City::create(['id'=>335,'ciudad'=>'Filandia','id_departamento'=>63]);
        City::create(['id'=>336,'ciudad'=>'Firavitoba','id_departamento'=>15]);
        City::create(['id'=>337,'ciudad'=>'Flandes','id_departamento'=>73]);
        City::create(['id'=>338,'ciudad'=>'Florencia','id_departamento'=>18]);
        City::create(['id'=>339,'ciudad'=>'Florencia','id_departamento'=>19]);
        City::create(['id'=>340,'ciudad'=>'Floresta','id_departamento'=>15]);
        City::create(['id'=>341,'ciudad'=>'Florida','id_departamento'=>76]);
        City::create(['id'=>342,'ciudad'=>'Floridablanca','id_departamento'=>68]);
        City::create(['id'=>343,'ciudad'=>'Florián','id_departamento'=>68]);
        City::create(['id'=>344,'ciudad'=>'Fonseca','id_departamento'=>44]);
        City::create(['id'=>345,'ciudad'=>'Fortúl','id_departamento'=>81]);
        City::create(['id'=>346,'ciudad'=>'Fosca','id_departamento'=>25]);
        City::create(['id'=>347,'ciudad'=>'Francisco Pizarro','id_departamento'=>52]);
        City::create(['id'=>348,'ciudad'=>'Fredonia','id_departamento'=>5]);
        City::create(['id'=>349,'ciudad'=>'Fresno','id_departamento'=>73]);
        City::create(['id'=>350,'ciudad'=>'Frontino','id_departamento'=>5]);
        City::create(['id'=>351,'ciudad'=>'Fuente de Oro','id_departamento'=>50]);
        City::create(['id'=>352,'ciudad'=>'Fundación','id_departamento'=>47]);
        City::create(['id'=>353,'ciudad'=>'Funes','id_departamento'=>52]);
        City::create(['id'=>354,'ciudad'=>'Funza','id_departamento'=>25]);
        City::create(['id'=>355,'ciudad'=>'Fusagasugá','id_departamento'=>25]);
        City::create(['id'=>356,'ciudad'=>'Fómeque','id_departamento'=>25]);
        City::create(['id'=>357,'ciudad'=>'Fúquene','id_departamento'=>25]);
        City::create(['id'=>358,'ciudad'=>'Gachalá','id_departamento'=>25]);
        City::create(['id'=>359,'ciudad'=>'Gachancipá','id_departamento'=>25]);
        City::create(['id'=>360,'ciudad'=>'Gachantivá','id_departamento'=>15]);
        City::create(['id'=>361,'ciudad'=>'Gachetá','id_departamento'=>25]);
        City::create(['id'=>362,'ciudad'=>'Galapa','id_departamento'=>8]);
        City::create(['id'=>363,'ciudad'=>'Galeras (Nueva Granada)','id_departamento'=>70]);
        City::create(['id'=>364,'ciudad'=>'Galán','id_departamento'=>68]);
        City::create(['id'=>365,'ciudad'=>'Gama','id_departamento'=>25]);
        City::create(['id'=>366,'ciudad'=>'Gamarra','id_departamento'=>20]);
        City::create(['id'=>367,'ciudad'=>'Garagoa','id_departamento'=>15]);
        City::create(['id'=>368,'ciudad'=>'Garzón','id_departamento'=>41]);
        City::create(['id'=>369,'ciudad'=>'Gigante','id_departamento'=>41]);
        City::create(['id'=>370,'ciudad'=>'Ginebra','id_departamento'=>76]);
        City::create(['id'=>371,'ciudad'=>'Giraldo','id_departamento'=>5]);
        City::create(['id'=>372,'ciudad'=>'Girardot','id_departamento'=>25]);
        City::create(['id'=>373,'ciudad'=>'Girardota','id_departamento'=>5]);
        City::create(['id'=>374,'ciudad'=>'Girón','id_departamento'=>68]);
        City::create(['id'=>375,'ciudad'=>'Gonzalez','id_departamento'=>20]);
        City::create(['id'=>376,'ciudad'=>'Gramalote','id_departamento'=>54]);
        City::create(['id'=>377,'ciudad'=>'Granada','id_departamento'=>5]);
        City::create(['id'=>378,'ciudad'=>'Granada','id_departamento'=>25]);
        City::create(['id'=>379,'ciudad'=>'Granada','id_departamento'=>50]);
        City::create(['id'=>380,'ciudad'=>'Guaca','id_departamento'=>68]);
        City::create(['id'=>381,'ciudad'=>'Guacamayas','id_departamento'=>15]);
        City::create(['id'=>382,'ciudad'=>'Guacarí','id_departamento'=>76]);
        City::create(['id'=>383,'ciudad'=>'Guachavés','id_departamento'=>52]);
        City::create(['id'=>384,'ciudad'=>'Guachené','id_departamento'=>19]);
        City::create(['id'=>385,'ciudad'=>'Guachetá','id_departamento'=>25]);
        City::create(['id'=>386,'ciudad'=>'Guachucal','id_departamento'=>52]);
        City::create(['id'=>387,'ciudad'=>'Guadalupe','id_departamento'=>5]);
        City::create(['id'=>388,'ciudad'=>'Guadalupe','id_departamento'=>41]);
        City::create(['id'=>389,'ciudad'=>'Guadalupe','id_departamento'=>68]);
        City::create(['id'=>390,'ciudad'=>'Guaduas','id_departamento'=>25]);
        City::create(['id'=>391,'ciudad'=>'Guaitarilla','id_departamento'=>52]);
        City::create(['id'=>392,'ciudad'=>'Gualmatán','id_departamento'=>52]);
        City::create(['id'=>393,'ciudad'=>'Guamal','id_departamento'=>47]);
        City::create(['id'=>394,'ciudad'=>'Guamal','id_departamento'=>50]);
        City::create(['id'=>395,'ciudad'=>'Guamo','id_departamento'=>73]);
        City::create(['id'=>396,'ciudad'=>'Guapota','id_departamento'=>68]);
        City::create(['id'=>397,'ciudad'=>'Guapí','id_departamento'=>19]);
        City::create(['id'=>398,'ciudad'=>'Guaranda','id_departamento'=>70]);
        City::create(['id'=>399,'ciudad'=>'Guarne','id_departamento'=>5]);
        City::create(['id'=>400,'ciudad'=>'Guasca','id_departamento'=>25]);
        City::create(['id'=>401,'ciudad'=>'Guatapé','id_departamento'=>5]);
        City::create(['id'=>402,'ciudad'=>'Guataquí','id_departamento'=>25]);
        City::create(['id'=>403,'ciudad'=>'Guatavita','id_departamento'=>25]);
        City::create(['id'=>404,'ciudad'=>'Guateque','id_departamento'=>15]);
        City::create(['id'=>405,'ciudad'=>'Guavatá','id_departamento'=>68]);
        City::create(['id'=>406,'ciudad'=>'Guayabal de Siquima','id_departamento'=>25]);
        City::create(['id'=>407,'ciudad'=>'Guayabetal','id_departamento'=>25]);
        City::create(['id'=>408,'ciudad'=>'Guayatá','id_departamento'=>15]);
        City::create(['id'=>409,'ciudad'=>'Guepsa','id_departamento'=>68]);
        City::create(['id'=>410,'ciudad'=>'Guicán','id_departamento'=>15]);
        City::create(['id'=>411,'ciudad'=>'Gutiérrez','id_departamento'=>25]);
        City::create(['id'=>412,'ciudad'=>'Guática','id_departamento'=>66]);
        City::create(['id'=>413,'ciudad'=>'Gámbita','id_departamento'=>68]);
        City::create(['id'=>414,'ciudad'=>'Gámeza','id_departamento'=>15]);
        City::create(['id'=>415,'ciudad'=>'Génova','id_departamento'=>63]);
        City::create(['id'=>416,'ciudad'=>'Gómez Plata','id_departamento'=>5]);
        City::create(['id'=>417,'ciudad'=>'Hacarí','id_departamento'=>54]);
        City::create(['id'=>418,'ciudad'=>'Hatillo de Loba','id_departamento'=>13]);
        City::create(['id'=>419,'ciudad'=>'Hato','id_departamento'=>68]);
        City::create(['id'=>420,'ciudad'=>'Hato Corozal','id_departamento'=>85]);
        City::create(['id'=>421,'ciudad'=>'Hatonuevo','id_departamento'=>44]);
        City::create(['id'=>422,'ciudad'=>'Heliconia','id_departamento'=>5]);
        City::create(['id'=>423,'ciudad'=>'Herrán','id_departamento'=>54]);
        City::create(['id'=>424,'ciudad'=>'Herveo','id_departamento'=>73]);
        City::create(['id'=>425,'ciudad'=>'Hispania','id_departamento'=>5]);
        City::create(['id'=>426,'ciudad'=>'Hobo','id_departamento'=>41]);
        City::create(['id'=>427,'ciudad'=>'Honda','id_departamento'=>73]);
        City::create(['id'=>428,'ciudad'=>'Ibagué','id_departamento'=>73]);
        City::create(['id'=>429,'ciudad'=>'Icononzo','id_departamento'=>73]);
        City::create(['id'=>430,'ciudad'=>'Iles','id_departamento'=>52]);
        City::create(['id'=>431,'ciudad'=>'Imúes','id_departamento'=>52]);
        City::create(['id'=>432,'ciudad'=>'Inzá','id_departamento'=>19]);
        City::create(['id'=>433,'ciudad'=>'Inírida','id_departamento'=>94]);
        City::create(['id'=>434,'ciudad'=>'Ipiales','id_departamento'=>52]);
        City::create(['id'=>435,'ciudad'=>'Isnos','id_departamento'=>41]);
        City::create(['id'=>436,'ciudad'=>'Istmina','id_departamento'=>27]);
        City::create(['id'=>437,'ciudad'=>'Itagüí','id_departamento'=>5]);
        City::create(['id'=>438,'ciudad'=>'Ituango','id_departamento'=>5]);
        City::create(['id'=>439,'ciudad'=>'Izá','id_departamento'=>15]);
        City::create(['id'=>440,'ciudad'=>'Jambaló','id_departamento'=>19]);
        City::create(['id'=>441,'ciudad'=>'Jamundí','id_departamento'=>76]);
        City::create(['id'=>442,'ciudad'=>'Jardín','id_departamento'=>5]);
        City::create(['id'=>443,'ciudad'=>'Jenesano','id_departamento'=>15]);
        City::create(['id'=>444,'ciudad'=>'Jericó','id_departamento'=>5]);
        City::create(['id'=>445,'ciudad'=>'Jericó','id_departamento'=>15]);
        City::create(['id'=>446,'ciudad'=>'Jerusalén','id_departamento'=>25]);
        City::create(['id'=>447,'ciudad'=>'Jesús María','id_departamento'=>68]);
        City::create(['id'=>448,'ciudad'=>'Jordán','id_departamento'=>68]);
        City::create(['id'=>449,'ciudad'=>'Juan de Acosta','id_departamento'=>8]);
        City::create(['id'=>450,'ciudad'=>'Junín','id_departamento'=>25]);
        City::create(['id'=>451,'ciudad'=>'Juradó','id_departamento'=>27]);
        City::create(['id'=>452,'ciudad'=>'La Apartada y La Frontera','id_departamento'=>23]);
        City::create(['id'=>453,'ciudad'=>'La Argentina','id_departamento'=>41]);
        City::create(['id'=>454,'ciudad'=>'La Belleza','id_departamento'=>68]);
        City::create(['id'=>455,'ciudad'=>'La Calera','id_departamento'=>25]);
        City::create(['id'=>456,'ciudad'=>'La Capilla','id_departamento'=>15]);
        City::create(['id'=>457,'ciudad'=>'La Ceja','id_departamento'=>5]);
        City::create(['id'=>458,'ciudad'=>'La Celia','id_departamento'=>66]);
        City::create(['id'=>459,'ciudad'=>'La Cruz','id_departamento'=>52]);
        City::create(['id'=>460,'ciudad'=>'La Cumbre','id_departamento'=>76]);
        City::create(['id'=>461,'ciudad'=>'La Dorada','id_departamento'=>17]);
        City::create(['id'=>462,'ciudad'=>'La Esperanza','id_departamento'=>54]);
        City::create(['id'=>463,'ciudad'=>'La Estrella','id_departamento'=>5]);
        City::create(['id'=>464,'ciudad'=>'La Florida','id_departamento'=>52]);
        City::create(['id'=>465,'ciudad'=>'La Gloria','id_departamento'=>20]);
        City::create(['id'=>466,'ciudad'=>'La Jagua de Ibirico','id_departamento'=>20]);
        City::create(['id'=>467,'ciudad'=>'La Jagua del Pilar','id_departamento'=>44]);
        City::create(['id'=>468,'ciudad'=>'La Llanada','id_departamento'=>52]);
        City::create(['id'=>469,'ciudad'=>'La Macarena','id_departamento'=>50]);
        City::create(['id'=>470,'ciudad'=>'La Merced','id_departamento'=>17]);
        City::create(['id'=>471,'ciudad'=>'La Mesa','id_departamento'=>25]);
        City::create(['id'=>472,'ciudad'=>'La Montañita','id_departamento'=>18]);
        City::create(['id'=>473,'ciudad'=>'La Palma','id_departamento'=>25]);
        City::create(['id'=>474,'ciudad'=>'La Paz','id_departamento'=>68]);
        City::create(['id'=>475,'ciudad'=>'La Paz (Robles)','id_departamento'=>20]);
        City::create(['id'=>476,'ciudad'=>'La Peña','id_departamento'=>25]);
        City::create(['id'=>477,'ciudad'=>'La Pintada','id_departamento'=>5]);
        City::create(['id'=>478,'ciudad'=>'La Plata','id_departamento'=>41]);
        City::create(['id'=>479,'ciudad'=>'La Playa','id_departamento'=>54]);
        City::create(['id'=>480,'ciudad'=>'La Primavera','id_departamento'=>99]);
        City::create(['id'=>481,'ciudad'=>'La Salina','id_departamento'=>85]);
        City::create(['id'=>482,'ciudad'=>'La Sierra','id_departamento'=>19]);
        City::create(['id'=>483,'ciudad'=>'La Tebaida','id_departamento'=>63]);
        City::create(['id'=>484,'ciudad'=>'La Tola','id_departamento'=>52]);
        City::create(['id'=>485,'ciudad'=>'La Unión','id_departamento'=>5]);
        City::create(['id'=>486,'ciudad'=>'La Unión','id_departamento'=>52]);
        City::create(['id'=>487,'ciudad'=>'La Unión','id_departamento'=>70]);
        City::create(['id'=>488,'ciudad'=>'La Unión','id_departamento'=>76]);
        City::create(['id'=>489,'ciudad'=>'La Uvita','id_departamento'=>15]);
        City::create(['id'=>490,'ciudad'=>'La Vega','id_departamento'=>19]);
        City::create(['id'=>491,'ciudad'=>'La Vega','id_departamento'=>25]);
        City::create(['id'=>492,'ciudad'=>'La Victoria','id_departamento'=>15]);
        City::create(['id'=>493,'ciudad'=>'La Victoria','id_departamento'=>17]);
        City::create(['id'=>494,'ciudad'=>'La Victoria','id_departamento'=>76]);
        City::create(['id'=>495,'ciudad'=>'La Virginia','id_departamento'=>66]);
        City::create(['id'=>496,'ciudad'=>'Labateca','id_departamento'=>54]);
        City::create(['id'=>497,'ciudad'=>'Labranzagrande','id_departamento'=>15]);
        City::create(['id'=>498,'ciudad'=>'Landázuri','id_departamento'=>68]);
        City::create(['id'=>499,'ciudad'=>'Lebrija','id_departamento'=>68]);
        City::create(['id'=>500,'ciudad'=>'Leiva','id_departamento'=>52]);
        City::create(['id'=>501,'ciudad'=>'Lejanías','id_departamento'=>50]);
        City::create(['id'=>502,'ciudad'=>'Lenguazaque','id_departamento'=>25]);
        City::create(['id'=>503,'ciudad'=>'Leticia','id_departamento'=>91]);
        City::create(['id'=>504,'ciudad'=>'Liborina','id_departamento'=>5]);
        City::create(['id'=>505,'ciudad'=>'Linares','id_departamento'=>52]);
        City::create(['id'=>506,'ciudad'=>'Lloró','id_departamento'=>27]);
        City::create(['id'=>507,'ciudad'=>'Lorica','id_departamento'=>23]);
        City::create(['id'=>508,'ciudad'=>'Los Córdobas','id_departamento'=>23]);
        City::create(['id'=>509,'ciudad'=>'Los Palmitos','id_departamento'=>70]);
        City::create(['id'=>510,'ciudad'=>'Los Patios','id_departamento'=>54]);
        City::create(['id'=>511,'ciudad'=>'Los Santos','id_departamento'=>68]);
        City::create(['id'=>512,'ciudad'=>'Lourdes','id_departamento'=>54]);
        City::create(['id'=>513,'ciudad'=>'Luruaco','id_departamento'=>8]);
        City::create(['id'=>514,'ciudad'=>'Lérida','id_departamento'=>73]);
        City::create(['id'=>515,'ciudad'=>'Líbano','id_departamento'=>73]);
        City::create(['id'=>516,'ciudad'=>'López (Micay)','id_departamento'=>19]);
        City::create(['id'=>517,'ciudad'=>'Macanal','id_departamento'=>15]);
        City::create(['id'=>518,'ciudad'=>'Macaravita','id_departamento'=>68]);
        City::create(['id'=>519,'ciudad'=>'Maceo','id_departamento'=>5]);
        City::create(['id'=>520,'ciudad'=>'Machetá','id_departamento'=>25]);
        City::create(['id'=>521,'ciudad'=>'Madrid','id_departamento'=>25]);
        City::create(['id'=>522,'ciudad'=>'Magangué','id_departamento'=>13]);
        City::create(['id'=>523,'ciudad'=>'Magüi (Payán)','id_departamento'=>52]);
        City::create(['id'=>524,'ciudad'=>'Mahates','id_departamento'=>13]);
        City::create(['id'=>525,'ciudad'=>'Maicao','id_departamento'=>44]);
        City::create(['id'=>526,'ciudad'=>'Majagual','id_departamento'=>70]);
        City::create(['id'=>527,'ciudad'=>'Malambo','id_departamento'=>8]);
        City::create(['id'=>528,'ciudad'=>'Mallama (Piedrancha)','id_departamento'=>52]);
        City::create(['id'=>529,'ciudad'=>'Manatí','id_departamento'=>8]);
        City::create(['id'=>530,'ciudad'=>'Manaure','id_departamento'=>44]);
        City::create(['id'=>531,'ciudad'=>'Manaure Balcón del Cesar','id_departamento'=>20]);
        City::create(['id'=>532,'ciudad'=>'Manizales','id_departamento'=>17]);
        City::create(['id'=>533,'ciudad'=>'Manta','id_departamento'=>25]);
        City::create(['id'=>534,'ciudad'=>'Manzanares','id_departamento'=>17]);
        City::create(['id'=>535,'ciudad'=>'Maní','id_departamento'=>85]);
        City::create(['id'=>536,'ciudad'=>'Mapiripan','id_departamento'=>50]);
        City::create(['id'=>537,'ciudad'=>'Margarita','id_departamento'=>13]);
        City::create(['id'=>538,'ciudad'=>'Marinilla','id_departamento'=>5]);
        City::create(['id'=>539,'ciudad'=>'Maripí','id_departamento'=>15]);
        City::create(['id'=>540,'ciudad'=>'Mariquita','id_departamento'=>73]);
        City::create(['id'=>541,'ciudad'=>'Marmato','id_departamento'=>17]);
        City::create(['id'=>542,'ciudad'=>'Marquetalia','id_departamento'=>17]);
        City::create(['id'=>543,'ciudad'=>'Marsella','id_departamento'=>66]);
        City::create(['id'=>544,'ciudad'=>'Marulanda','id_departamento'=>17]);
        City::create(['id'=>545,'ciudad'=>'María la Baja','id_departamento'=>13]);
        City::create(['id'=>546,'ciudad'=>'Matanza','id_departamento'=>68]);
        City::create(['id'=>547,'ciudad'=>'Medellín','id_departamento'=>5]);
        City::create(['id'=>548,'ciudad'=>'Medina','id_departamento'=>25]);
        City::create(['id'=>549,'ciudad'=>'Medio Atrato','id_departamento'=>27]);
        City::create(['id'=>550,'ciudad'=>'Medio Baudó','id_departamento'=>27]);
        City::create(['id'=>551,'ciudad'=>'Medio San Juan (ANDAGOYA)','id_departamento'=>27]);
        City::create(['id'=>552,'ciudad'=>'Melgar','id_departamento'=>73]);
        City::create(['id'=>553,'ciudad'=>'Mercaderes','id_departamento'=>19]);
        City::create(['id'=>554,'ciudad'=>'Mesetas','id_departamento'=>50]);
        City::create(['id'=>555,'ciudad'=>'Milán','id_departamento'=>18]);
        City::create(['id'=>556,'ciudad'=>'Miraflores','id_departamento'=>15]);
        City::create(['id'=>557,'ciudad'=>'Miraflores','id_departamento'=>95]);
        City::create(['id'=>558,'ciudad'=>'Miranda','id_departamento'=>19]);
        City::create(['id'=>559,'ciudad'=>'Mistrató','id_departamento'=>66]);
        City::create(['id'=>560,'ciudad'=>'Mitú','id_departamento'=>97]);
        City::create(['id'=>561,'ciudad'=>'Mocoa','id_departamento'=>86]);
        City::create(['id'=>562,'ciudad'=>'Mogotes','id_departamento'=>68]);
        City::create(['id'=>563,'ciudad'=>'Molagavita','id_departamento'=>68]);
        City::create(['id'=>564,'ciudad'=>'Momil','id_departamento'=>23]);
        City::create(['id'=>565,'ciudad'=>'Mompós','id_departamento'=>13]);
        City::create(['id'=>566,'ciudad'=>'Mongua','id_departamento'=>15]);
        City::create(['id'=>567,'ciudad'=>'Monguí','id_departamento'=>15]);
        City::create(['id'=>568,'ciudad'=>'Moniquirá','id_departamento'=>15]);
        City::create(['id'=>569,'ciudad'=>'Montebello','id_departamento'=>5]);
        City::create(['id'=>570,'ciudad'=>'Montecristo','id_departamento'=>13]);
        City::create(['id'=>571,'ciudad'=>'Montelíbano','id_departamento'=>23]);
        City::create(['id'=>572,'ciudad'=>'Montenegro','id_departamento'=>63]);
        City::create(['id'=>573,'ciudad'=>'Monteria','id_departamento'=>23]);
        City::create(['id'=>574,'ciudad'=>'Monterrey','id_departamento'=>85]);
        City::create(['id'=>575,'ciudad'=>'Morales','id_departamento'=>13]);
        City::create(['id'=>576,'ciudad'=>'Morales','id_departamento'=>19]);
        City::create(['id'=>577,'ciudad'=>'Morelia','id_departamento'=>18]);
        City::create(['id'=>578,'ciudad'=>'Morroa','id_departamento'=>70]);
        City::create(['id'=>579,'ciudad'=>'Mosquera','id_departamento'=>25]);
        City::create(['id'=>580,'ciudad'=>'Mosquera','id_departamento'=>52]);
        City::create(['id'=>581,'ciudad'=>'Motavita','id_departamento'=>15]);
        City::create(['id'=>582,'ciudad'=>'Moñitos','id_departamento'=>23]);
        City::create(['id'=>583,'ciudad'=>'Murillo','id_departamento'=>73]);
        City::create(['id'=>584,'ciudad'=>'Murindó','id_departamento'=>5]);
        City::create(['id'=>585,'ciudad'=>'Mutatá','id_departamento'=>5]);
        City::create(['id'=>586,'ciudad'=>'Mutiscua','id_departamento'=>54]);
        City::create(['id'=>587,'ciudad'=>'Muzo','id_departamento'=>15]);
        City::create(['id'=>588,'ciudad'=>'Málaga','id_departamento'=>68]);
        City::create(['id'=>589,'ciudad'=>'Nariño','id_departamento'=>5]);
        City::create(['id'=>590,'ciudad'=>'Nariño','id_departamento'=>25]);
        City::create(['id'=>591,'ciudad'=>'Nariño','id_departamento'=>52]);
        City::create(['id'=>592,'ciudad'=>'Natagaima','id_departamento'=>73]);
        City::create(['id'=>593,'ciudad'=>'Nechí','id_departamento'=>5]);
        City::create(['id'=>594,'ciudad'=>'Necoclí','id_departamento'=>5]);
        City::create(['id'=>595,'ciudad'=>'Neira','id_departamento'=>17]);
        City::create(['id'=>596,'ciudad'=>'Neiva','id_departamento'=>41]);
        City::create(['id'=>597,'ciudad'=>'Nemocón','id_departamento'=>25]);
        City::create(['id'=>598,'ciudad'=>'Nilo','id_departamento'=>25]);
        City::create(['id'=>599,'ciudad'=>'Nimaima','id_departamento'=>25]);
        City::create(['id'=>600,'ciudad'=>'Nobsa','id_departamento'=>15]);
        City::create(['id'=>601,'ciudad'=>'Nocaima','id_departamento'=>25]);
        City::create(['id'=>602,'ciudad'=>'Norcasia','id_departamento'=>17]);
        City::create(['id'=>603,'ciudad'=>'Norosí','id_departamento'=>13]);
        City::create(['id'=>604,'ciudad'=>'Novita','id_departamento'=>27]);
        City::create(['id'=>605,'ciudad'=>'Nueva Granada','id_departamento'=>47]);
        City::create(['id'=>606,'ciudad'=>'Nuevo Colón','id_departamento'=>15]);
        City::create(['id'=>607,'ciudad'=>'Nunchía','id_departamento'=>85]);
        City::create(['id'=>608,'ciudad'=>'Nuquí','id_departamento'=>27]);
        City::create(['id'=>609,'ciudad'=>'Nátaga','id_departamento'=>41]);
        City::create(['id'=>610,'ciudad'=>'Obando','id_departamento'=>76]);
        City::create(['id'=>611,'ciudad'=>'Ocamonte','id_departamento'=>68]);
        City::create(['id'=>612,'ciudad'=>'Ocaña','id_departamento'=>54]);
        City::create(['id'=>613,'ciudad'=>'Oiba','id_departamento'=>68]);
        City::create(['id'=>614,'ciudad'=>'Oicatá','id_departamento'=>15]);
        City::create(['id'=>615,'ciudad'=>'Olaya','id_departamento'=>5]);
        City::create(['id'=>616,'ciudad'=>'Olaya Herrera','id_departamento'=>52]);
        City::create(['id'=>617,'ciudad'=>'Onzaga','id_departamento'=>68]);
        City::create(['id'=>618,'ciudad'=>'Oporapa','id_departamento'=>41]);
        City::create(['id'=>619,'ciudad'=>'Orito','id_departamento'=>86]);
        City::create(['id'=>620,'ciudad'=>'Orocué','id_departamento'=>85]);
        City::create(['id'=>621,'ciudad'=>'Ortega','id_departamento'=>73]);
        City::create(['id'=>622,'ciudad'=>'Ospina','id_departamento'=>52]);
        City::create(['id'=>623,'ciudad'=>'Otanche','id_departamento'=>15]);
        City::create(['id'=>624,'ciudad'=>'Ovejas','id_departamento'=>70]);
        City::create(['id'=>625,'ciudad'=>'Pachavita','id_departamento'=>15]);
        City::create(['id'=>626,'ciudad'=>'Pacho','id_departamento'=>25]);
        City::create(['id'=>627,'ciudad'=>'Padilla','id_departamento'=>19]);
        City::create(['id'=>628,'ciudad'=>'Paicol','id_departamento'=>41]);
        City::create(['id'=>629,'ciudad'=>'Pailitas','id_departamento'=>20]);
        City::create(['id'=>630,'ciudad'=>'Paime','id_departamento'=>25]);
        City::create(['id'=>631,'ciudad'=>'Paipa','id_departamento'=>15]);
        City::create(['id'=>632,'ciudad'=>'Pajarito','id_departamento'=>15]);
        City::create(['id'=>633,'ciudad'=>'Palermo','id_departamento'=>41]);
        City::create(['id'=>634,'ciudad'=>'Palestina','id_departamento'=>17]);
        City::create(['id'=>635,'ciudad'=>'Palestina','id_departamento'=>41]);
        City::create(['id'=>636,'ciudad'=>'Palmar','id_departamento'=>68]);
        City::create(['id'=>637,'ciudad'=>'Palmar de Varela','id_departamento'=>8]);
        City::create(['id'=>638,'ciudad'=>'Palmas del Socorro','id_departamento'=>68]);
        City::create(['id'=>639,'ciudad'=>'Palmira','id_departamento'=>76]);
        City::create(['id'=>640,'ciudad'=>'Palmito','id_departamento'=>70]);
        City::create(['id'=>641,'ciudad'=>'Palocabildo','id_departamento'=>73]);
        City::create(['id'=>642,'ciudad'=>'Pamplona','id_departamento'=>54]);
        City::create(['id'=>643,'ciudad'=>'Pamplonita','id_departamento'=>54]);
        City::create(['id'=>644,'ciudad'=>'Pandi','id_departamento'=>25]);
        City::create(['id'=>645,'ciudad'=>'Panqueba','id_departamento'=>15]);
        City::create(['id'=>646,'ciudad'=>'Paratebueno','id_departamento'=>25]);
        City::create(['id'=>647,'ciudad'=>'Pasca','id_departamento'=>25]);
        City::create(['id'=>648,'ciudad'=>'Patía (El Bordo)','id_departamento'=>19]);
        City::create(['id'=>649,'ciudad'=>'Pauna','id_departamento'=>15]);
        City::create(['id'=>650,'ciudad'=>'Paya','id_departamento'=>15]);
        City::create(['id'=>651,'ciudad'=>'Paz de Ariporo','id_departamento'=>85]);
        City::create(['id'=>652,'ciudad'=>'Paz de Río','id_departamento'=>15]);
        City::create(['id'=>653,'ciudad'=>'Pedraza','id_departamento'=>47]);
        City::create(['id'=>654,'ciudad'=>'Pelaya','id_departamento'=>20]);
        City::create(['id'=>655,'ciudad'=>'Pensilvania','id_departamento'=>17]);
        City::create(['id'=>656,'ciudad'=>'Peque','id_departamento'=>5]);
        City::create(['id'=>657,'ciudad'=>'Pereira','id_departamento'=>66]);
        City::create(['id'=>658,'ciudad'=>'Pesca','id_departamento'=>15]);
        City::create(['id'=>659,'ciudad'=>'Peñol','id_departamento'=>5]);
        City::create(['id'=>660,'ciudad'=>'Piamonte','id_departamento'=>19]);
        City::create(['id'=>661,'ciudad'=>'Pie de Cuesta','id_departamento'=>68]);
        City::create(['id'=>662,'ciudad'=>'Piedras','id_departamento'=>73]);
        City::create(['id'=>663,'ciudad'=>'Piendamó','id_departamento'=>19]);
        City::create(['id'=>664,'ciudad'=>'Pijao','id_departamento'=>63]);
        City::create(['id'=>665,'ciudad'=>'Pijiño','id_departamento'=>47]);
        City::create(['id'=>666,'ciudad'=>'Pinchote','id_departamento'=>68]);
        City::create(['id'=>667,'ciudad'=>'Pinillos','id_departamento'=>13]);
        City::create(['id'=>668,'ciudad'=>'Piojo','id_departamento'=>8]);
        City::create(['id'=>669,'ciudad'=>'Pisva','id_departamento'=>15]);
        City::create(['id'=>670,'ciudad'=>'Pital','id_departamento'=>41]);
        City::create(['id'=>671,'ciudad'=>'Pitalito','id_departamento'=>41]);
        City::create(['id'=>672,'ciudad'=>'Pivijay','id_departamento'=>47]);
        City::create(['id'=>673,'ciudad'=>'Planadas','id_departamento'=>73]);
        City::create(['id'=>674,'ciudad'=>'Planeta Rica','id_departamento'=>23]);
        City::create(['id'=>675,'ciudad'=>'Plato','id_departamento'=>47]);
        City::create(['id'=>676,'ciudad'=>'Policarpa','id_departamento'=>52]);
        City::create(['id'=>677,'ciudad'=>'Polonuevo','id_departamento'=>8]);
        City::create(['id'=>678,'ciudad'=>'Ponedera','id_departamento'=>8]);
        City::create(['id'=>679,'ciudad'=>'Popayán','id_departamento'=>19]);
        City::create(['id'=>680,'ciudad'=>'Pore','id_departamento'=>85]);
        City::create(['id'=>681,'ciudad'=>'Potosí','id_departamento'=>52]);
        City::create(['id'=>682,'ciudad'=>'Pradera','id_departamento'=>76]);
        City::create(['id'=>683,'ciudad'=>'Prado','id_departamento'=>73]);
        City::create(['id'=>684,'ciudad'=>'Providencia','id_departamento'=>52]);
        City::create(['id'=>685,'ciudad'=>'Providencia','id_departamento'=>88]);
        City::create(['id'=>686,'ciudad'=>'Pueblo Bello','id_departamento'=>20]);
        City::create(['id'=>687,'ciudad'=>'Pueblo Nuevo','id_departamento'=>23]);
        City::create(['id'=>688,'ciudad'=>'Pueblo Rico','id_departamento'=>66]);
        City::create(['id'=>689,'ciudad'=>'Pueblorrico','id_departamento'=>5]);
        City::create(['id'=>690,'ciudad'=>'Puebloviejo','id_departamento'=>47]);
        City::create(['id'=>691,'ciudad'=>'Puente Nacional','id_departamento'=>68]);
        City::create(['id'=>692,'ciudad'=>'Puerres','id_departamento'=>52]);
        City::create(['id'=>693,'ciudad'=>'Puerto Asís','id_departamento'=>86]);
        City::create(['id'=>694,'ciudad'=>'Puerto Berrío','id_departamento'=>5]);
        City::create(['id'=>695,'ciudad'=>'Puerto Boyacá','id_departamento'=>15]);
        City::create(['id'=>696,'ciudad'=>'Puerto Caicedo','id_departamento'=>86]);
        City::create(['id'=>697,'ciudad'=>'Puerto Carreño','id_departamento'=>99]);
        City::create(['id'=>698,'ciudad'=>'Puerto Colombia','id_departamento'=>8]);
        City::create(['id'=>699,'ciudad'=>'Puerto Concordia','id_departamento'=>50]);
        City::create(['id'=>700,'ciudad'=>'Puerto Escondido','id_departamento'=>23]);
        City::create(['id'=>701,'ciudad'=>'Puerto Gaitán','id_departamento'=>50]);
        City::create(['id'=>702,'ciudad'=>'Puerto Guzmán','id_departamento'=>86]);
        City::create(['id'=>703,'ciudad'=>'Puerto Leguízamo','id_departamento'=>86]);
        City::create(['id'=>704,'ciudad'=>'Puerto Libertador','id_departamento'=>23]);
        City::create(['id'=>705,'ciudad'=>'Puerto Lleras','id_departamento'=>50]);
        City::create(['id'=>706,'ciudad'=>'Puerto López','id_departamento'=>50]);
        City::create(['id'=>707,'ciudad'=>'Puerto Nare','id_departamento'=>5]);
        City::create(['id'=>708,'ciudad'=>'Puerto Nariño','id_departamento'=>91]);
        City::create(['id'=>709,'ciudad'=>'Puerto Parra','id_departamento'=>68]);
        City::create(['id'=>710,'ciudad'=>'Puerto Rico','id_departamento'=>18]);
        City::create(['id'=>711,'ciudad'=>'Puerto Rico','id_departamento'=>50]);
        City::create(['id'=>712,'ciudad'=>'Puerto Rondón','id_departamento'=>81]);
        City::create(['id'=>713,'ciudad'=>'Puerto Salgar','id_departamento'=>25]);
        City::create(['id'=>714,'ciudad'=>'Puerto Santander','id_departamento'=>54]);
        City::create(['id'=>715,'ciudad'=>'Puerto Tejada','id_departamento'=>19]);
        City::create(['id'=>716,'ciudad'=>'Puerto Triunfo','id_departamento'=>5]);
        City::create(['id'=>717,'ciudad'=>'Puerto Wilches','id_departamento'=>68]);
        City::create(['id'=>718,'ciudad'=>'Pulí','id_departamento'=>25]);
        City::create(['id'=>719,'ciudad'=>'Pupiales','id_departamento'=>52]);
        City::create(['id'=>720,'ciudad'=>'Puracé (Coconuco)','id_departamento'=>19]);
        City::create(['id'=>721,'ciudad'=>'Purificación','id_departamento'=>73]);
        City::create(['id'=>722,'ciudad'=>'Purísima','id_departamento'=>23]);
        City::create(['id'=>723,'ciudad'=>'Pácora','id_departamento'=>17]);
        City::create(['id'=>724,'ciudad'=>'Páez','id_departamento'=>15]);
        City::create(['id'=>725,'ciudad'=>'Páez (Belalcazar)','id_departamento'=>19]);
        City::create(['id'=>726,'ciudad'=>'Páramo','id_departamento'=>68]);
        City::create(['id'=>727,'ciudad'=>'Quebradanegra','id_departamento'=>25]);
        City::create(['id'=>728,'ciudad'=>'Quetame','id_departamento'=>25]);
        City::create(['id'=>729,'ciudad'=>'Quibdó','id_departamento'=>27]);
        City::create(['id'=>730,'ciudad'=>'Quimbaya','id_departamento'=>63]);
        City::create(['id'=>731,'ciudad'=>'Quinchía','id_departamento'=>66]);
        City::create(['id'=>732,'ciudad'=>'Quipama','id_departamento'=>15]);
        City::create(['id'=>733,'ciudad'=>'Quipile','id_departamento'=>25]);
        City::create(['id'=>734,'ciudad'=>'Ragonvalia','id_departamento'=>54]);
        City::create(['id'=>735,'ciudad'=>'Ramiriquí','id_departamento'=>15]);
        City::create(['id'=>736,'ciudad'=>'Recetor','id_departamento'=>85]);
        City::create(['id'=>737,'ciudad'=>'Regidor','id_departamento'=>13]);
        City::create(['id'=>738,'ciudad'=>'Remedios','id_departamento'=>5]);
        City::create(['id'=>739,'ciudad'=>'Remolino','id_departamento'=>47]);
        City::create(['id'=>740,'ciudad'=>'Repelón','id_departamento'=>8]);
        City::create(['id'=>741,'ciudad'=>'Restrepo','id_departamento'=>50]);
        City::create(['id'=>742,'ciudad'=>'Restrepo','id_departamento'=>76]);
        City::create(['id'=>743,'ciudad'=>'Retiro','id_departamento'=>5]);
        City::create(['id'=>744,'ciudad'=>'Ricaurte','id_departamento'=>25]);
        City::create(['id'=>745,'ciudad'=>'Ricaurte','id_departamento'=>52]);
        City::create(['id'=>746,'ciudad'=>'Rio Negro','id_departamento'=>68]);
        City::create(['id'=>747,'ciudad'=>'Rioblanco','id_departamento'=>73]);
        City::create(['id'=>748,'ciudad'=>'Riofrío','id_departamento'=>76]);
        City::create(['id'=>749,'ciudad'=>'Riohacha','id_departamento'=>44]);
        City::create(['id'=>750,'ciudad'=>'Risaralda','id_departamento'=>17]);
        City::create(['id'=>751,'ciudad'=>'Rivera','id_departamento'=>41]);
        City::create(['id'=>752,'ciudad'=>'Roberto Payán (San José)','id_departamento'=>52]);
        City::create(['id'=>753,'ciudad'=>'Roldanillo','id_departamento'=>76]);
        City::create(['id'=>754,'ciudad'=>'Roncesvalles','id_departamento'=>73]);
        City::create(['id'=>755,'ciudad'=>'Rondón','id_departamento'=>15]);
        City::create(['id'=>756,'ciudad'=>'Rosas','id_departamento'=>19]);
        City::create(['id'=>757,'ciudad'=>'Rovira','id_departamento'=>73]);
        City::create(['id'=>758,'ciudad'=>'Ráquira','id_departamento'=>15]);
        City::create(['id'=>759,'ciudad'=>'Río Iró','id_departamento'=>27]);
        City::create(['id'=>760,'ciudad'=>'Río Quito','id_departamento'=>27]);
        City::create(['id'=>761,'ciudad'=>'Río Sucio','id_departamento'=>17]);
        City::create(['id'=>762,'ciudad'=>'Río Viejo','id_departamento'=>13]);
        City::create(['id'=>763,'ciudad'=>'Río de oro','id_departamento'=>20]);
        City::create(['id'=>764,'ciudad'=>'Ríonegro','id_departamento'=>5]);
        City::create(['id'=>765,'ciudad'=>'Ríosucio','id_departamento'=>27]);
        City::create(['id'=>766,'ciudad'=>'Sabana de Torres','id_departamento'=>68]);
        City::create(['id'=>767,'ciudad'=>'Sabanagrande','id_departamento'=>8]);
        City::create(['id'=>768,'ciudad'=>'Sabanalarga','id_departamento'=>5]);
        City::create(['id'=>769,'ciudad'=>'Sabanalarga','id_departamento'=>8]);
        City::create(['id'=>770,'ciudad'=>'Sabanalarga','id_departamento'=>85]);
        City::create(['id'=>771,'ciudad'=>'Sabanas de San Angel (SAN ANGEL)','id_departamento'=>47]);
        City::create(['id'=>772,'ciudad'=>'Sabaneta','id_departamento'=>5]);
        City::create(['id'=>773,'ciudad'=>'Saboyá','id_departamento'=>15]);
        City::create(['id'=>774,'ciudad'=>'Sahagún','id_departamento'=>23]);
        City::create(['id'=>775,'ciudad'=>'Saladoblanco','id_departamento'=>41]);
        City::create(['id'=>776,'ciudad'=>'Salamina','id_departamento'=>17]);
        City::create(['id'=>777,'ciudad'=>'Salamina','id_departamento'=>47]);
        City::create(['id'=>778,'ciudad'=>'Salazar','id_departamento'=>54]);
        City::create(['id'=>779,'ciudad'=>'Saldaña','id_departamento'=>73]);
        City::create(['id'=>780,'ciudad'=>'Salento','id_departamento'=>63]);
        City::create(['id'=>781,'ciudad'=>'Salgar','id_departamento'=>5]);
        City::create(['id'=>782,'ciudad'=>'Samacá','id_departamento'=>15]);
        City::create(['id'=>783,'ciudad'=>'Samaniego','id_departamento'=>52]);
        City::create(['id'=>784,'ciudad'=>'Samaná','id_departamento'=>17]);
        City::create(['id'=>785,'ciudad'=>'Sampués','id_departamento'=>70]);
        City::create(['id'=>786,'ciudad'=>'San Agustín','id_departamento'=>41]);
        City::create(['id'=>787,'ciudad'=>'San Alberto','id_departamento'=>20]);
        City::create(['id'=>788,'ciudad'=>'San Andrés','id_departamento'=>68]);
        City::create(['id'=>789,'ciudad'=>'San Andrés Sotavento','id_departamento'=>23]);
        City::create(['id'=>790,'ciudad'=>'San Andrés de Cuerquía','id_departamento'=>5]);
        City::create(['id'=>791,'ciudad'=>'San Antero','id_departamento'=>23]);
        City::create(['id'=>792,'ciudad'=>'San Antonio','id_departamento'=>73]);
        City::create(['id'=>793,'ciudad'=>'San Antonio de Tequendama','id_departamento'=>25]);
        City::create(['id'=>794,'ciudad'=>'San Benito','id_departamento'=>68]);
        City::create(['id'=>795,'ciudad'=>'San Benito Abad','id_departamento'=>70]);
        City::create(['id'=>796,'ciudad'=>'San Bernardo','id_departamento'=>25]);
        City::create(['id'=>797,'ciudad'=>'San Bernardo','id_departamento'=>52]);
        City::create(['id'=>798,'ciudad'=>'San Bernardo del Viento','id_departamento'=>23]);
        City::create(['id'=>799,'ciudad'=>'San Calixto','id_departamento'=>54]);
        City::create(['id'=>800,'ciudad'=>'San Carlos','id_departamento'=>5]);
        City::create(['id'=>801,'ciudad'=>'San Carlos','id_departamento'=>23]);
        City::create(['id'=>802,'ciudad'=>'San Carlos de Guaroa','id_departamento'=>50]);
        City::create(['id'=>803,'ciudad'=>'San Cayetano','id_departamento'=>25]);
        City::create(['id'=>804,'ciudad'=>'San Cayetano','id_departamento'=>54]);
        City::create(['id'=>805,'ciudad'=>'San Cristobal','id_departamento'=>13]);
        City::create(['id'=>806,'ciudad'=>'San Diego','id_departamento'=>20]);
        City::create(['id'=>807,'ciudad'=>'San Eduardo','id_departamento'=>15]);
        City::create(['id'=>808,'ciudad'=>'San Estanislao','id_departamento'=>13]);
        City::create(['id'=>809,'ciudad'=>'San Fernando','id_departamento'=>13]);
        City::create(['id'=>810,'ciudad'=>'San Francisco','id_departamento'=>5]);
        City::create(['id'=>811,'ciudad'=>'San Francisco','id_departamento'=>25]);
        City::create(['id'=>812,'ciudad'=>'San Francisco','id_departamento'=>86]);
        City::create(['id'=>813,'ciudad'=>'San Gíl','id_departamento'=>68]);
        City::create(['id'=>814,'ciudad'=>'San Jacinto','id_departamento'=>13]);
        City::create(['id'=>815,'ciudad'=>'San Jacinto del Cauca','id_departamento'=>13]);
        City::create(['id'=>816,'ciudad'=>'San Jerónimo','id_departamento'=>5]);
        City::create(['id'=>817,'ciudad'=>'San Joaquín','id_departamento'=>68]);
        City::create(['id'=>818,'ciudad'=>'San José','id_departamento'=>17]);
        City::create(['id'=>819,'ciudad'=>'San José de Miranda','id_departamento'=>68]);
        City::create(['id'=>820,'ciudad'=>'San José de Montaña','id_departamento'=>5]);
        City::create(['id'=>821,'ciudad'=>'San José de Pare','id_departamento'=>15]);
        City::create(['id'=>822,'ciudad'=>'San José de Uré','id_departamento'=>23]);
        City::create(['id'=>823,'ciudad'=>'San José del Fragua','id_departamento'=>18]);
        City::create(['id'=>824,'ciudad'=>'San José del Guaviare','id_departamento'=>95]);
        City::create(['id'=>825,'ciudad'=>'San José del Palmar','id_departamento'=>27]);
        City::create(['id'=>826,'ciudad'=>'San Juan de Arama','id_departamento'=>50]);
        City::create(['id'=>827,'ciudad'=>'San Juan de Betulia','id_departamento'=>70]);
        City::create(['id'=>828,'ciudad'=>'San Juan de Nepomuceno','id_departamento'=>13]);
        City::create(['id'=>829,'ciudad'=>'San Juan de Pasto','id_departamento'=>52]);
        City::create(['id'=>830,'ciudad'=>'San Juan de Río Seco','id_departamento'=>25]);
        City::create(['id'=>831,'ciudad'=>'San Juan de Urabá','id_departamento'=>5]);
        City::create(['id'=>832,'ciudad'=>'San Juan del Cesar','id_departamento'=>44]);
        City::create(['id'=>833,'ciudad'=>'San Juanito','id_departamento'=>50]);
        City::create(['id'=>834,'ciudad'=>'San Lorenzo','id_departamento'=>52]);
        City::create(['id'=>835,'ciudad'=>'San Luis','id_departamento'=>73]);
        City::create(['id'=>836,'ciudad'=>'San Luís','id_departamento'=>5]);
        City::create(['id'=>837,'ciudad'=>'San Luís de Gaceno','id_departamento'=>15]);
        City::create(['id'=>838,'ciudad'=>'San Luís de Palenque','id_departamento'=>85]);
        City::create(['id'=>839,'ciudad'=>'San Marcos','id_departamento'=>70]);
        City::create(['id'=>840,'ciudad'=>'San Martín','id_departamento'=>20]);
        City::create(['id'=>841,'ciudad'=>'San Martín','id_departamento'=>50]);
        City::create(['id'=>842,'ciudad'=>'San Martín de Loba','id_departamento'=>13]);
        City::create(['id'=>843,'ciudad'=>'San Mateo','id_departamento'=>15]);
        City::create(['id'=>844,'ciudad'=>'San Miguel','id_departamento'=>68]);
        City::create(['id'=>845,'ciudad'=>'San Miguel','id_departamento'=>86]);
        City::create(['id'=>846,'ciudad'=>'San Miguel de Sema','id_departamento'=>15]);
        City::create(['id'=>847,'ciudad'=>'San Onofre','id_departamento'=>70]);
        City::create(['id'=>848,'ciudad'=>'San Pablo','id_departamento'=>13]);
        City::create(['id'=>849,'ciudad'=>'San Pablo','id_departamento'=>52]);
        City::create(['id'=>850,'ciudad'=>'San Pablo de Borbur','id_departamento'=>15]);
        City::create(['id'=>851,'ciudad'=>'San Pedro','id_departamento'=>5]);
        City::create(['id'=>852,'ciudad'=>'San Pedro','id_departamento'=>70]);
        City::create(['id'=>853,'ciudad'=>'San Pedro','id_departamento'=>76]);
        City::create(['id'=>854,'ciudad'=>'San Pedro de Cartago','id_departamento'=>52]);
        City::create(['id'=>855,'ciudad'=>'San Pedro de Urabá','id_departamento'=>5]);
        City::create(['id'=>856,'ciudad'=>'San Pelayo','id_departamento'=>23]);
        City::create(['id'=>857,'ciudad'=>'San Rafael','id_departamento'=>5]);
        City::create(['id'=>858,'ciudad'=>'San Roque','id_departamento'=>5]);
        City::create(['id'=>859,'ciudad'=>'San Sebastián','id_departamento'=>19]);
        City::create(['id'=>860,'ciudad'=>'San Sebastián de Buenavista','id_departamento'=>47]);
        City::create(['id'=>861,'ciudad'=>'San Vicente','id_departamento'=>5]);
        City::create(['id'=>862,'ciudad'=>'San Vicente del Caguán','id_departamento'=>18]);
        City::create(['id'=>863,'ciudad'=>'San Vicente del Chucurí','id_departamento'=>68]);
        City::create(['id'=>864,'ciudad'=>'San Zenón','id_departamento'=>47]);
        City::create(['id'=>865,'ciudad'=>'Sandoná','id_departamento'=>52]);
        City::create(['id'=>866,'ciudad'=>'Santa Ana','id_departamento'=>47]);
        City::create(['id'=>867,'ciudad'=>'Santa Bárbara','id_departamento'=>5]);
        City::create(['id'=>868,'ciudad'=>'Santa Bárbara','id_departamento'=>68]);
        City::create(['id'=>869,'ciudad'=>'Santa Bárbara (Iscuandé)','id_departamento'=>52]);
        City::create(['id'=>870,'ciudad'=>'Santa Bárbara de Pinto','id_departamento'=>47]);
        City::create(['id'=>871,'ciudad'=>'Santa Catalina','id_departamento'=>13]);
        City::create(['id'=>872,'ciudad'=>'Santa Fé de Antioquia','id_departamento'=>5]);
        City::create(['id'=>873,'ciudad'=>'Santa Genoveva de Docorodó','id_departamento'=>27]);
        City::create(['id'=>874,'ciudad'=>'Santa Helena del Opón','id_departamento'=>68]);
        City::create(['id'=>875,'ciudad'=>'Santa Isabel','id_departamento'=>73]);
        City::create(['id'=>876,'ciudad'=>'Santa Lucía','id_departamento'=>8]);
        City::create(['id'=>877,'ciudad'=>'Santa Marta','id_departamento'=>47]);
        City::create(['id'=>878,'ciudad'=>'Santa María','id_departamento'=>15]);
        City::create(['id'=>879,'ciudad'=>'Santa María','id_departamento'=>41]);
        City::create(['id'=>880,'ciudad'=>'Santa Rosa','id_departamento'=>13]);
        City::create(['id'=>881,'ciudad'=>'Santa Rosa','id_departamento'=>19]);
        City::create(['id'=>882,'ciudad'=>'Santa Rosa de Cabal','id_departamento'=>66]);
        City::create(['id'=>883,'ciudad'=>'Santa Rosa de Osos','id_departamento'=>5]);
        City::create(['id'=>884,'ciudad'=>'Santa Rosa de Viterbo','id_departamento'=>15]);
        City::create(['id'=>885,'ciudad'=>'Santa Rosa del Sur','id_departamento'=>13]);
        City::create(['id'=>886,'ciudad'=>'Santa Rosalía','id_departamento'=>99]);
        City::create(['id'=>887,'ciudad'=>'Santa Sofía','id_departamento'=>15]);
        City::create(['id'=>888,'ciudad'=>'Santana','id_departamento'=>15]);
        City::create(['id'=>889,'ciudad'=>'Santander de Quilichao','id_departamento'=>19]);
        City::create(['id'=>890,'ciudad'=>'Santiago','id_departamento'=>54]);
        City::create(['id'=>891,'ciudad'=>'Santiago','id_departamento'=>86]);
        City::create(['id'=>892,'ciudad'=>'Santo Domingo','id_departamento'=>5]);
        City::create(['id'=>893,'ciudad'=>'Santo Tomás','id_departamento'=>8]);
        City::create(['id'=>894,'ciudad'=>'Santuario','id_departamento'=>5]);
        City::create(['id'=>895,'ciudad'=>'Santuario','id_departamento'=>66]);
        City::create(['id'=>896,'ciudad'=>'Sapuyes','id_departamento'=>52]);
        City::create(['id'=>897,'ciudad'=>'Saravena','id_departamento'=>81]);
        City::create(['id'=>898,'ciudad'=>'Sardinata','id_departamento'=>54]);
        City::create(['id'=>899,'ciudad'=>'Sasaima','id_departamento'=>25]);
        City::create(['id'=>900,'ciudad'=>'Sativanorte','id_departamento'=>15]);
        City::create(['id'=>901,'ciudad'=>'Sativasur','id_departamento'=>15]);
        City::create(['id'=>902,'ciudad'=>'Segovia','id_departamento'=>5]);
        City::create(['id'=>903,'ciudad'=>'Sesquilé','id_departamento'=>25]);
        City::create(['id'=>904,'ciudad'=>'Sevilla','id_departamento'=>76]);
        City::create(['id'=>905,'ciudad'=>'Siachoque','id_departamento'=>15]);
        City::create(['id'=>906,'ciudad'=>'Sibaté','id_departamento'=>25]);
        City::create(['id'=>907,'ciudad'=>'Sibundoy','id_departamento'=>86]);
        City::create(['id'=>908,'ciudad'=>'Silos','id_departamento'=>54]);
        City::create(['id'=>909,'ciudad'=>'Silvania','id_departamento'=>25]);
        City::create(['id'=>910,'ciudad'=>'Silvia','id_departamento'=>19]);
        City::create(['id'=>911,'ciudad'=>'Simacota','id_departamento'=>68]);
        City::create(['id'=>912,'ciudad'=>'Simijaca','id_departamento'=>25]);
        City::create(['id'=>913,'ciudad'=>'Simití','id_departamento'=>13]);
        City::create(['id'=>914,'ciudad'=>'Sincelejo','id_departamento'=>70]);
        City::create(['id'=>915,'ciudad'=>'Sincé','id_departamento'=>70]);
        City::create(['id'=>916,'ciudad'=>'Sipí','id_departamento'=>27]);
        City::create(['id'=>917,'ciudad'=>'Sitionuevo','id_departamento'=>47]);
        City::create(['id'=>918,'ciudad'=>'Soacha','id_departamento'=>25]);
        City::create(['id'=>919,'ciudad'=>'Soatá','id_departamento'=>15]);
        City::create(['id'=>920,'ciudad'=>'Socha','id_departamento'=>15]);
        City::create(['id'=>921,'ciudad'=>'Socorro','id_departamento'=>68]);
        City::create(['id'=>922,'ciudad'=>'Socotá','id_departamento'=>15]);
        City::create(['id'=>923,'ciudad'=>'Sogamoso','id_departamento'=>15]);
        City::create(['id'=>924,'ciudad'=>'Solano','id_departamento'=>18]);
        City::create(['id'=>925,'ciudad'=>'Soledad','id_departamento'=>8]);
        City::create(['id'=>926,'ciudad'=>'Solita','id_departamento'=>18]);
        City::create(['id'=>927,'ciudad'=>'Somondoco','id_departamento'=>15]);
        City::create(['id'=>928,'ciudad'=>'Sonsón','id_departamento'=>5]);
        City::create(['id'=>929,'ciudad'=>'Sopetrán','id_departamento'=>5]);
        City::create(['id'=>930,'ciudad'=>'Soplaviento','id_departamento'=>13]);
        City::create(['id'=>931,'ciudad'=>'Sopó','id_departamento'=>25]);
        City::create(['id'=>932,'ciudad'=>'Sora','id_departamento'=>15]);
        City::create(['id'=>933,'ciudad'=>'Soracá','id_departamento'=>15]);
        City::create(['id'=>934,'ciudad'=>'Sotaquirá','id_departamento'=>15]);
        City::create(['id'=>935,'ciudad'=>'Sotara (Paispamba)','id_departamento'=>19]);
        City::create(['id'=>936,'ciudad'=>'Sotomayor (Los Andes)','id_departamento'=>52]);
        City::create(['id'=>937,'ciudad'=>'Suaita','id_departamento'=>68]);
        City::create(['id'=>938,'ciudad'=>'Suan','id_departamento'=>8]);
        City::create(['id'=>939,'ciudad'=>'Suaza','id_departamento'=>41]);
        City::create(['id'=>940,'ciudad'=>'Subachoque','id_departamento'=>25]);
        City::create(['id'=>941,'ciudad'=>'Sucre','id_departamento'=>19]);
        City::create(['id'=>942,'ciudad'=>'Sucre','id_departamento'=>68]);
        City::create(['id'=>943,'ciudad'=>'Sucre','id_departamento'=>70]);
        City::create(['id'=>944,'ciudad'=>'Suesca','id_departamento'=>25]);
        City::create(['id'=>945,'ciudad'=>'Supatá','id_departamento'=>25]);
        City::create(['id'=>946,'ciudad'=>'Supía','id_departamento'=>17]);
        City::create(['id'=>947,'ciudad'=>'Suratá','id_departamento'=>68]);
        City::create(['id'=>948,'ciudad'=>'Susa','id_departamento'=>25]);
        City::create(['id'=>949,'ciudad'=>'Susacón','id_departamento'=>15]);
        City::create(['id'=>950,'ciudad'=>'Sutamarchán','id_departamento'=>15]);
        City::create(['id'=>951,'ciudad'=>'Sutatausa','id_departamento'=>25]);
        City::create(['id'=>952,'ciudad'=>'Sutatenza','id_departamento'=>15]);
        City::create(['id'=>953,'ciudad'=>'Suárez','id_departamento'=>19]);
        City::create(['id'=>954,'ciudad'=>'Suárez','id_departamento'=>73]);
        City::create(['id'=>955,'ciudad'=>'Sácama','id_departamento'=>85]);
        City::create(['id'=>956,'ciudad'=>'Sáchica','id_departamento'=>15]);
        City::create(['id'=>957,'ciudad'=>'Tabio','id_departamento'=>25]);
        City::create(['id'=>958,'ciudad'=>'Tadó','id_departamento'=>27]);
        City::create(['id'=>959,'ciudad'=>'Talaigua Nuevo','id_departamento'=>13]);
        City::create(['id'=>960,'ciudad'=>'Tamalameque','id_departamento'=>20]);
        City::create(['id'=>961,'ciudad'=>'Tame','id_departamento'=>81]);
        City::create(['id'=>962,'ciudad'=>'Taminango','id_departamento'=>52]);
        City::create(['id'=>963,'ciudad'=>'Tangua','id_departamento'=>52]);
        City::create(['id'=>964,'ciudad'=>'Taraira','id_departamento'=>97]);
        City::create(['id'=>965,'ciudad'=>'Tarazá','id_departamento'=>5]);
        City::create(['id'=>966,'ciudad'=>'Tarqui','id_departamento'=>41]);
        City::create(['id'=>967,'ciudad'=>'Tarso','id_departamento'=>5]);
        City::create(['id'=>968,'ciudad'=>'Tasco','id_departamento'=>15]);
        City::create(['id'=>969,'ciudad'=>'Tauramena','id_departamento'=>85]);
        City::create(['id'=>970,'ciudad'=>'Tausa','id_departamento'=>25]);
        City::create(['id'=>971,'ciudad'=>'Tello','id_departamento'=>41]);
        City::create(['id'=>972,'ciudad'=>'Tena','id_departamento'=>25]);
        City::create(['id'=>973,'ciudad'=>'Tenerife','id_departamento'=>47]);
        City::create(['id'=>974,'ciudad'=>'Tenjo','id_departamento'=>25]);
        City::create(['id'=>975,'ciudad'=>'Tenza','id_departamento'=>15]);
        City::create(['id'=>976,'ciudad'=>'Teorama','id_departamento'=>54]);
        City::create(['id'=>977,'ciudad'=>'Teruel','id_departamento'=>41]);
        City::create(['id'=>978,'ciudad'=>'Tesalia','id_departamento'=>41]);
        City::create(['id'=>979,'ciudad'=>'Tibacuy','id_departamento'=>25]);
        City::create(['id'=>980,'ciudad'=>'Tibaná','id_departamento'=>15]);
        City::create(['id'=>981,'ciudad'=>'Tibasosa','id_departamento'=>15]);
        City::create(['id'=>982,'ciudad'=>'Tibirita','id_departamento'=>25]);
        City::create(['id'=>983,'ciudad'=>'Tibú','id_departamento'=>54]);
        City::create(['id'=>984,'ciudad'=>'Tierralta','id_departamento'=>23]);
        City::create(['id'=>985,'ciudad'=>'Timaná','id_departamento'=>41]);
        City::create(['id'=>986,'ciudad'=>'Timbiquí','id_departamento'=>19]);
        City::create(['id'=>987,'ciudad'=>'Timbío','id_departamento'=>19]);
        City::create(['id'=>988,'ciudad'=>'Tinjacá','id_departamento'=>15]);
        City::create(['id'=>989,'ciudad'=>'Tipacoque','id_departamento'=>15]);
        City::create(['id'=>990,'ciudad'=>'Tiquisio (Puerto Rico)','id_departamento'=>13]);
        City::create(['id'=>991,'ciudad'=>'Titiribí','id_departamento'=>5]);
        City::create(['id'=>992,'ciudad'=>'Toca','id_departamento'=>15]);
        City::create(['id'=>993,'ciudad'=>'Tocaima','id_departamento'=>25]);
        City::create(['id'=>994,'ciudad'=>'Tocancipá','id_departamento'=>25]);
        City::create(['id'=>995,'ciudad'=>'Toguí','id_departamento'=>15]);
        City::create(['id'=>996,'ciudad'=>'Toledo','id_departamento'=>5]);
        City::create(['id'=>997,'ciudad'=>'Toledo','id_departamento'=>54]);
        City::create(['id'=>998,'ciudad'=>'Tolú','id_departamento'=>70]);
        City::create(['id'=>999,'ciudad'=>'Tolú Viejo','id_departamento'=>70]);
        City::create(['id'=>1000,'ciudad'=>'Tona','id_departamento'=>68]);
        City::create(['id'=>1001,'ciudad'=>'Topagá','id_departamento'=>15]);
        City::create(['id'=>1002,'ciudad'=>'Topaipí','id_departamento'=>25]);
        City::create(['id'=>1003,'ciudad'=>'Toribío','id_departamento'=>19]);
        City::create(['id'=>1004,'ciudad'=>'Toro','id_departamento'=>76]);
        City::create(['id'=>1005,'ciudad'=>'Tota','id_departamento'=>15]);
        City::create(['id'=>1006,'ciudad'=>'Totoró','id_departamento'=>19]);
        City::create(['id'=>1007,'ciudad'=>'Trinidad','id_departamento'=>85]);
        City::create(['id'=>1008,'ciudad'=>'Trujillo','id_departamento'=>76]);
        City::create(['id'=>1009,'ciudad'=>'Tubará','id_departamento'=>8]);
        City::create(['id'=>1010,'ciudad'=>'Tuchín','id_departamento'=>23]);
        City::create(['id'=>1011,'ciudad'=>'Tulúa','id_departamento'=>76]);
        City::create(['id'=>1012,'ciudad'=>'Tumaco','id_departamento'=>52]);
        City::create(['id'=>1013,'ciudad'=>'Tunja','id_departamento'=>15]);
        City::create(['id'=>1014,'ciudad'=>'Tunungua','id_departamento'=>15]);
        City::create(['id'=>1015,'ciudad'=>'Turbaco','id_departamento'=>13]);
        City::create(['id'=>1016,'ciudad'=>'Turbaná','id_departamento'=>13]);
        City::create(['id'=>1017,'ciudad'=>'Turbo','id_departamento'=>5]);
        City::create(['id'=>1018,'ciudad'=>'Turmequé','id_departamento'=>15]);
        City::create(['id'=>1019,'ciudad'=>'Tuta','id_departamento'=>15]);
        City::create(['id'=>1020,'ciudad'=>'Tutasá','id_departamento'=>15]);
        City::create(['id'=>1021,'ciudad'=>'Támara','id_departamento'=>85]);
        City::create(['id'=>1022,'ciudad'=>'Támesis','id_departamento'=>5]);
        City::create(['id'=>1023,'ciudad'=>'Túquerres','id_departamento'=>52]);
        City::create(['id'=>1024,'ciudad'=>'Ubalá','id_departamento'=>25]);
        City::create(['id'=>1025,'ciudad'=>'Ubaque','id_departamento'=>25]);
        City::create(['id'=>1026,'ciudad'=>'Ubaté','id_departamento'=>25]);
        City::create(['id'=>1027,'ciudad'=>'Ulloa','id_departamento'=>76]);
        City::create(['id'=>1028,'ciudad'=>'Une','id_departamento'=>25]);
        City::create(['id'=>1029,'ciudad'=>'Unguía','id_departamento'=>27]);
        City::create(['id'=>1030,'ciudad'=>'Unión Panamericana (ÁNIMAS)','id_departamento'=>27]);
        City::create(['id'=>1031,'ciudad'=>'Uramita','id_departamento'=>5]);
        City::create(['id'=>1032,'ciudad'=>'Uribe','id_departamento'=>50]);
        City::create(['id'=>1033,'ciudad'=>'Uribia','id_departamento'=>44]);
        City::create(['id'=>1034,'ciudad'=>'Urrao','id_departamento'=>5]);
        City::create(['id'=>1035,'ciudad'=>'Urumita','id_departamento'=>44]);
        City::create(['id'=>1036,'ciudad'=>'Usiacuri','id_departamento'=>8]);
        City::create(['id'=>1037,'ciudad'=>'Valdivia','id_departamento'=>5]);
        City::create(['id'=>1038,'ciudad'=>'Valencia','id_departamento'=>23]);
        City::create(['id'=>1039,'ciudad'=>'Valle de San José','id_departamento'=>68]);
        City::create(['id'=>1040,'ciudad'=>'Valle de San Juan','id_departamento'=>73]);
        City::create(['id'=>1041,'ciudad'=>'Valle del Guamuez','id_departamento'=>86]);
        City::create(['id'=>1042,'ciudad'=>'Valledupar','id_departamento'=>20]);
        City::create(['id'=>1043,'ciudad'=>'Valparaiso','id_departamento'=>5]);
        City::create(['id'=>1044,'ciudad'=>'Valparaiso','id_departamento'=>18]);
        City::create(['id'=>1045,'ciudad'=>'Vegachí','id_departamento'=>5]);
        City::create(['id'=>1046,'ciudad'=>'Venadillo','id_departamento'=>73]);
        City::create(['id'=>1047,'ciudad'=>'Venecia','id_departamento'=>5]);
        City::create(['id'=>1048,'ciudad'=>'Venecia (Ospina Pérez)','id_departamento'=>25]);
        City::create(['id'=>1049,'ciudad'=>'Ventaquemada','id_departamento'=>15]);
        City::create(['id'=>1050,'ciudad'=>'Vergara','id_departamento'=>25]);
        City::create(['id'=>1051,'ciudad'=>'Versalles','id_departamento'=>76]);
        City::create(['id'=>1052,'ciudad'=>'Vetas','id_departamento'=>68]);
        City::create(['id'=>1053,'ciudad'=>'Viani','id_departamento'=>25]);
        City::create(['id'=>1054,'ciudad'=>'Vigía del Fuerte','id_departamento'=>5]);
        City::create(['id'=>1055,'ciudad'=>'Vijes','id_departamento'=>76]);
        City::create(['id'=>1056,'ciudad'=>'Villa Caro','id_departamento'=>54]);
        City::create(['id'=>1057,'ciudad'=>'Villa Rica','id_departamento'=>19]);
        City::create(['id'=>1058,'ciudad'=>'Villa de Leiva','id_departamento'=>15]);
        City::create(['id'=>1059,'ciudad'=>'Villa del Rosario','id_departamento'=>54]);
        City::create(['id'=>1060,'ciudad'=>'Villagarzón','id_departamento'=>86]);
        City::create(['id'=>1061,'ciudad'=>'Villagómez','id_departamento'=>25]);
        City::create(['id'=>1062,'ciudad'=>'Villahermosa','id_departamento'=>73]);
        City::create(['id'=>1063,'ciudad'=>'Villamaría','id_departamento'=>17]);
        City::create(['id'=>1064,'ciudad'=>'Villanueva','id_departamento'=>13]);
        City::create(['id'=>1065,'ciudad'=>'Villanueva','id_departamento'=>44]);
        City::create(['id'=>1066,'ciudad'=>'Villanueva','id_departamento'=>68]);
        City::create(['id'=>1067,'ciudad'=>'Villanueva','id_departamento'=>85]);
        City::create(['id'=>1068,'ciudad'=>'Villapinzón','id_departamento'=>25]);
        City::create(['id'=>1069,'ciudad'=>'Villarrica','id_departamento'=>73]);
        City::create(['id'=>1070,'ciudad'=>'Villavicencio','id_departamento'=>50]);
        City::create(['id'=>1071,'ciudad'=>'Villavieja','id_departamento'=>41]);
        City::create(['id'=>1072,'ciudad'=>'Villeta','id_departamento'=>25]);
        City::create(['id'=>1073,'ciudad'=>'Viotá','id_departamento'=>25]);
        City::create(['id'=>1074,'ciudad'=>'Viracachá','id_departamento'=>15]);
        City::create(['id'=>1075,'ciudad'=>'Vista Hermosa','id_departamento'=>50]);
        City::create(['id'=>1076,'ciudad'=>'Viterbo','id_departamento'=>17]);
        City::create(['id'=>1077,'ciudad'=>'Vélez','id_departamento'=>68]);
        City::create(['id'=>1078,'ciudad'=>'Yacopí','id_departamento'=>25]);
        City::create(['id'=>1079,'ciudad'=>'Yacuanquer','id_departamento'=>52]);
        City::create(['id'=>1080,'ciudad'=>'Yaguará','id_departamento'=>41]);
        City::create(['id'=>1081,'ciudad'=>'Yalí','id_departamento'=>5]);
        City::create(['id'=>1082,'ciudad'=>'Yarumal','id_departamento'=>5]);
        City::create(['id'=>1083,'ciudad'=>'Yolombó','id_departamento'=>5]);
        City::create(['id'=>1084,'ciudad'=>'Yondó (Casabe)','id_departamento'=>5]);
        City::create(['id'=>1085,'ciudad'=>'Yopal','id_departamento'=>85]);
        City::create(['id'=>1086,'ciudad'=>'Yotoco','id_departamento'=>76]);
        City::create(['id'=>1087,'ciudad'=>'Yumbo','id_departamento'=>76]);
        City::create(['id'=>1088,'ciudad'=>'Zambrano','id_departamento'=>13]);
        City::create(['id'=>1089,'ciudad'=>'Zapatoca','id_departamento'=>68]);
        City::create(['id'=>1090,'ciudad'=>'Zapayán (PUNTA DE PIEDRAS)','id_departamento'=>47]);
        City::create(['id'=>1091,'ciudad'=>'Zaragoza','id_departamento'=>5]);
        City::create(['id'=>1092,'ciudad'=>'Zarzal','id_departamento'=>76]);
        City::create(['id'=>1093,'ciudad'=>'Zetaquirá','id_departamento'=>15]);
        City::create(['id'=>1094,'ciudad'=>'Zipacón','id_departamento'=>25]);
        City::create(['id'=>1095,'ciudad'=>'Zipaquirá','id_departamento'=>25]);
        City::create(['id'=>1096,'ciudad'=>'Zona Bananera (PRADO - SEVILLA)','id_departamento'=>47]);
        City::create(['id'=>1097,'ciudad'=>'Ábrego','id_departamento'=>54]);
        City::create(['id'=>1098,'ciudad'=>'Íquira','id_departamento'=>41]);
        City::create(['id'=>1099,'ciudad'=>'Úmbita','id_departamento'=>15]);
        City::create(['id'=>1100,'ciudad'=>'Útica','id_departamento'=>25]);
    }
}
