<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create(['id'=>1,'ciudad'=>'Abriaquí','departamento_id'=>5]);
        City::create(['id'=>2,'ciudad'=>'Acacías','departamento_id'=>50]);
        City::create(['id'=>3,'ciudad'=>'Acandí','departamento_id'=>27]);
        City::create(['id'=>4,'ciudad'=>'Acevedo','departamento_id'=>41]);
        City::create(['id'=>5,'ciudad'=>'Achí','departamento_id'=>13]);
        City::create(['id'=>6,'ciudad'=>'Agrado','departamento_id'=>41]);
        City::create(['id'=>7,'ciudad'=>'Agua de Dios','departamento_id'=>25]);
        City::create(['id'=>8,'ciudad'=>'Aguachica','departamento_id'=>20]);
        City::create(['id'=>9,'ciudad'=>'Aguada','departamento_id'=>68]);
        City::create(['id'=>10,'ciudad'=>'Aguadas','departamento_id'=>17]);
        City::create(['id'=>11,'ciudad'=>'Aguazul','departamento_id'=>85]);
        City::create(['id'=>12,'ciudad'=>'Agustín Codazzi','departamento_id'=>20]);
        City::create(['id'=>13,'ciudad'=>'Aipe','departamento_id'=>41]);
        City::create(['id'=>14,'ciudad'=>'Albania','departamento_id'=>18]);
        City::create(['id'=>15,'ciudad'=>'Albania','departamento_id'=>44]);
        City::create(['id'=>16,'ciudad'=>'Albania','departamento_id'=>68]);
        City::create(['id'=>17,'ciudad'=>'Albán','departamento_id'=>25]);
        City::create(['id'=>18,'ciudad'=>'Albán (San José)','departamento_id'=>52]);
        City::create(['id'=>19,'ciudad'=>'Alcalá','departamento_id'=>76]);
        City::create(['id'=>20,'ciudad'=>'Alejandria','departamento_id'=>5]);
        City::create(['id'=>21,'ciudad'=>'Algarrobo','departamento_id'=>47]);
        City::create(['id'=>22,'ciudad'=>'Algeciras','departamento_id'=>41]);
        City::create(['id'=>23,'ciudad'=>'Almaguer','departamento_id'=>19]);
        City::create(['id'=>24,'ciudad'=>'Almeida','departamento_id'=>15]);
        City::create(['id'=>25,'ciudad'=>'Alpujarra','departamento_id'=>73]);
        City::create(['id'=>26,'ciudad'=>'Altamira','departamento_id'=>41]);
        City::create(['id'=>27,'ciudad'=>'Alto Baudó (Pie de Pato)','departamento_id'=>27]);
        City::create(['id'=>28,'ciudad'=>'Altos del Rosario','departamento_id'=>13]);
        City::create(['id'=>29,'ciudad'=>'Alvarado','departamento_id'=>73]);
        City::create(['id'=>30,'ciudad'=>'Amagá','departamento_id'=>5]);
        City::create(['id'=>31,'ciudad'=>'Amalfi','departamento_id'=>5]);
        City::create(['id'=>32,'ciudad'=>'Ambalema','departamento_id'=>73]);
        City::create(['id'=>33,'ciudad'=>'Anapoima','departamento_id'=>25]);
        City::create(['id'=>34,'ciudad'=>'Ancuya','departamento_id'=>52]);
        City::create(['id'=>35,'ciudad'=>'Andalucía','departamento_id'=>76]);
        City::create(['id'=>36,'ciudad'=>'Andes','departamento_id'=>5]);
        City::create(['id'=>37,'ciudad'=>'Angelópolis','departamento_id'=>5]);
        City::create(['id'=>38,'ciudad'=>'Angostura','departamento_id'=>5]);
        City::create(['id'=>39,'ciudad'=>'Anolaima','departamento_id'=>25]);
        City::create(['id'=>40,'ciudad'=>'Anorí','departamento_id'=>5]);
        City::create(['id'=>41,'ciudad'=>'Anserma','departamento_id'=>17]);
        City::create(['id'=>42,'ciudad'=>'Ansermanuevo','departamento_id'=>76]);
        City::create(['id'=>43,'ciudad'=>'Anzoátegui','departamento_id'=>73]);
        City::create(['id'=>44,'ciudad'=>'Anzá','departamento_id'=>5]);
        City::create(['id'=>45,'ciudad'=>'Apartadó','departamento_id'=>5]);
        City::create(['id'=>46,'ciudad'=>'Apulo','departamento_id'=>25]);
        City::create(['id'=>47,'ciudad'=>'Apía','departamento_id'=>66]);
        City::create(['id'=>48,'ciudad'=>'Aquitania','departamento_id'=>15]);
        City::create(['id'=>49,'ciudad'=>'Aracataca','departamento_id'=>47]);
        City::create(['id'=>50,'ciudad'=>'Aranzazu','departamento_id'=>17]);
        City::create(['id'=>51,'ciudad'=>'Aratoca','departamento_id'=>68]);
        City::create(['id'=>52,'ciudad'=>'Arauca','departamento_id'=>81]);
        City::create(['id'=>53,'ciudad'=>'Arauquita','departamento_id'=>81]);
        City::create(['id'=>54,'ciudad'=>'Arbeláez','departamento_id'=>25]);
        City::create(['id'=>55,'ciudad'=>'Arboleda (Berruecos)','departamento_id'=>52]);
        City::create(['id'=>56,'ciudad'=>'Arboledas','departamento_id'=>54]);
        City::create(['id'=>57,'ciudad'=>'Arboletes','departamento_id'=>5]);
        City::create(['id'=>58,'ciudad'=>'Arcabuco','departamento_id'=>15]);
        City::create(['id'=>59,'ciudad'=>'Arenal','departamento_id'=>13]);
        City::create(['id'=>60,'ciudad'=>'Argelia','departamento_id'=>5]);
        City::create(['id'=>61,'ciudad'=>'Argelia','departamento_id'=>19]);
        City::create(['id'=>62,'ciudad'=>'Argelia','departamento_id'=>76]);
        City::create(['id'=>63,'ciudad'=>'Ariguaní (El Difícil)','departamento_id'=>47]);
        City::create(['id'=>64,'ciudad'=>'Arjona','departamento_id'=>13]);
        City::create(['id'=>65,'ciudad'=>'Armenia','departamento_id'=>5]);
        City::create(['id'=>66,'ciudad'=>'Armenia','departamento_id'=>63]);
        City::create(['id'=>67,'ciudad'=>'Armero (Guayabal)','departamento_id'=>73]);
        City::create(['id'=>68,'ciudad'=>'Arroyohondo','departamento_id'=>13]);
        City::create(['id'=>69,'ciudad'=>'Astrea','departamento_id'=>20]);
        City::create(['id'=>70,'ciudad'=>'Ataco','departamento_id'=>73]);
        City::create(['id'=>71,'ciudad'=>'Atrato (Yuto)','departamento_id'=>27]);
        City::create(['id'=>72,'ciudad'=>'Ayapel','departamento_id'=>23]);
        City::create(['id'=>73,'ciudad'=>'Bagadó','departamento_id'=>27]);
        City::create(['id'=>74,'ciudad'=>'Bahía Solano (Mútis)','departamento_id'=>27]);
        City::create(['id'=>75,'ciudad'=>'Bajo Baudó (Pizarro)','departamento_id'=>27]);
        City::create(['id'=>76,'ciudad'=>'Balboa','departamento_id'=>19]);
        City::create(['id'=>77,'ciudad'=>'Balboa','departamento_id'=>66]);
        City::create(['id'=>78,'ciudad'=>'Baranoa','departamento_id'=>8]);
        City::create(['id'=>79,'ciudad'=>'Baraya','departamento_id'=>41]);
        City::create(['id'=>80,'ciudad'=>'Barbacoas','departamento_id'=>52]);
        City::create(['id'=>81,'ciudad'=>'Barbosa','departamento_id'=>5]);
        City::create(['id'=>82,'ciudad'=>'Barbosa','departamento_id'=>68]);
        City::create(['id'=>83,'ciudad'=>'Barichara','departamento_id'=>68]);
        City::create(['id'=>84,'ciudad'=>'Barranca de Upía','departamento_id'=>50]);
        City::create(['id'=>85,'ciudad'=>'Barrancabermeja','departamento_id'=>68]);
        City::create(['id'=>86,'ciudad'=>'Barrancas','departamento_id'=>44]);
        City::create(['id'=>87,'ciudad'=>'Barranco de Loba','departamento_id'=>13]);
        City::create(['id'=>88,'ciudad'=>'Barranquilla','departamento_id'=>8]);
        City::create(['id'=>89,'ciudad'=>'Becerríl','departamento_id'=>20]);
        City::create(['id'=>90,'ciudad'=>'Belalcázar','departamento_id'=>17]);
        City::create(['id'=>91,'ciudad'=>'Bello','departamento_id'=>5]);
        City::create(['id'=>92,'ciudad'=>'Belmira','departamento_id'=>5]);
        City::create(['id'=>93,'ciudad'=>'Beltrán','departamento_id'=>25]);
        City::create(['id'=>94,'ciudad'=>'Belén','departamento_id'=>15]);
        City::create(['id'=>95,'ciudad'=>'Belén','departamento_id'=>52]);
        City::create(['id'=>96,'ciudad'=>'Belén de Bajirá','departamento_id'=>27]);
        City::create(['id'=>97,'ciudad'=>'Belén de Umbría','departamento_id'=>66]);
        City::create(['id'=>98,'ciudad'=>'Belén de los Andaquíes','departamento_id'=>18]);
        City::create(['id'=>99,'ciudad'=>'Berbeo','departamento_id'=>15]);
        City::create(['id'=>100,'ciudad'=>'Betania','departamento_id'=>5]);
        City::create(['id'=>101,'ciudad'=>'Beteitiva','departamento_id'=>15]);
        City::create(['id'=>102,'ciudad'=>'Betulia','departamento_id'=>5]);
        City::create(['id'=>103,'ciudad'=>'Betulia','departamento_id'=>68]);
        City::create(['id'=>104,'ciudad'=>'Bituima','departamento_id'=>25]);
        City::create(['id'=>105,'ciudad'=>'Boavita','departamento_id'=>15]);
        City::create(['id'=>106,'ciudad'=>'Bochalema','departamento_id'=>54]);
        City::create(['id'=>107,'ciudad'=>'Bogotá D.C.','departamento_id'=>11]);
        City::create(['id'=>108,'ciudad'=>'Bojacá','departamento_id'=>25]);
        City::create(['id'=>109,'ciudad'=>'Bojayá (Bellavista)','departamento_id'=>27]);
        City::create(['id'=>110,'ciudad'=>'Bolívar','departamento_id'=>5]);
        City::create(['id'=>111,'ciudad'=>'Bolívar','departamento_id'=>19]);
        City::create(['id'=>112,'ciudad'=>'Bolívar','departamento_id'=>68]);
        City::create(['id'=>113,'ciudad'=>'Bolívar','departamento_id'=>76]);
        City::create(['id'=>114,'ciudad'=>'Bosconia','departamento_id'=>20]);
        City::create(['id'=>115,'ciudad'=>'Boyacá','departamento_id'=>15]);
        City::create(['id'=>116,'ciudad'=>'Briceño','departamento_id'=>5]);
        City::create(['id'=>117,'ciudad'=>'Briceño','departamento_id'=>15]);
        City::create(['id'=>118,'ciudad'=>'Bucaramanga','departamento_id'=>68]);
        City::create(['id'=>119,'ciudad'=>'Bucarasica','departamento_id'=>54]);
        City::create(['id'=>120,'ciudad'=>'Buenaventura','departamento_id'=>76]);
        City::create(['id'=>121,'ciudad'=>'Buenavista','departamento_id'=>15]);
        City::create(['id'=>122,'ciudad'=>'Buenavista','departamento_id'=>23]);
        City::create(['id'=>123,'ciudad'=>'Buenavista','departamento_id'=>63]);
        City::create(['id'=>124,'ciudad'=>'Buenavista','departamento_id'=>70]);
        City::create(['id'=>125,'ciudad'=>'Buenos Aires','departamento_id'=>19]);
        City::create(['id'=>126,'ciudad'=>'Buesaco','departamento_id'=>52]);
        City::create(['id'=>127,'ciudad'=>'Buga','departamento_id'=>76]);
        City::create(['id'=>128,'ciudad'=>'Bugalagrande','departamento_id'=>76]);
        City::create(['id'=>129,'ciudad'=>'Burítica','departamento_id'=>5]);
        City::create(['id'=>130,'ciudad'=>'Busbanza','departamento_id'=>15]);
        City::create(['id'=>131,'ciudad'=>'Cabrera','departamento_id'=>25]);
        City::create(['id'=>132,'ciudad'=>'Cabrera','departamento_id'=>68]);
        City::create(['id'=>133,'ciudad'=>'Cabuyaro','departamento_id'=>50]);
        City::create(['id'=>134,'ciudad'=>'Cachipay','departamento_id'=>25]);
        City::create(['id'=>135,'ciudad'=>'Caicedo','departamento_id'=>5]);
        City::create(['id'=>136,'ciudad'=>'Caicedonia','departamento_id'=>76]);
        City::create(['id'=>137,'ciudad'=>'Caimito','departamento_id'=>70]);
        City::create(['id'=>138,'ciudad'=>'Cajamarca','departamento_id'=>73]);
        City::create(['id'=>139,'ciudad'=>'Cajibío','departamento_id'=>19]);
        City::create(['id'=>140,'ciudad'=>'Cajicá','departamento_id'=>25]);
        City::create(['id'=>141,'ciudad'=>'Calamar','departamento_id'=>13]);
        City::create(['id'=>142,'ciudad'=>'Calamar','departamento_id'=>95]);
        City::create(['id'=>143,'ciudad'=>'Calarcá','departamento_id'=>63]);
        City::create(['id'=>144,'ciudad'=>'Caldas','departamento_id'=>5]);
        City::create(['id'=>145,'ciudad'=>'Caldas','departamento_id'=>15]);
        City::create(['id'=>146,'ciudad'=>'Caldono','departamento_id'=>19]);
        City::create(['id'=>147,'ciudad'=>'California','departamento_id'=>68]);
        City::create(['id'=>148,'ciudad'=>'Calima (Darién)','departamento_id'=>76]);
        City::create(['id'=>149,'ciudad'=>'Caloto','departamento_id'=>19]);
        City::create(['id'=>150,'ciudad'=>'Calí','departamento_id'=>76]);
        City::create(['id'=>151,'ciudad'=>'Campamento','departamento_id'=>5]);
        City::create(['id'=>152,'ciudad'=>'Campo de la Cruz','departamento_id'=>8]);
        City::create(['id'=>153,'ciudad'=>'Campoalegre','departamento_id'=>41]);
        City::create(['id'=>154,'ciudad'=>'Campohermoso','departamento_id'=>15]);
        City::create(['id'=>155,'ciudad'=>'Canalete','departamento_id'=>23]);
        City::create(['id'=>156,'ciudad'=>'Candelaria','departamento_id'=>8]);
        City::create(['id'=>157,'ciudad'=>'Candelaria','departamento_id'=>76]);
        City::create(['id'=>158,'ciudad'=>'Cantagallo','departamento_id'=>13]);
        City::create(['id'=>159,'ciudad'=>'Cantón de San Pablo','departamento_id'=>27]);
        City::create(['id'=>160,'ciudad'=>'Caparrapí','departamento_id'=>25]);
        City::create(['id'=>161,'ciudad'=>'Capitanejo','departamento_id'=>68]);
        City::create(['id'=>162,'ciudad'=>'Caracolí','departamento_id'=>5]);
        City::create(['id'=>163,'ciudad'=>'Caramanta','departamento_id'=>5]);
        City::create(['id'=>164,'ciudad'=>'Carcasí','departamento_id'=>68]);
        City::create(['id'=>165,'ciudad'=>'Carepa','departamento_id'=>5]);
        City::create(['id'=>166,'ciudad'=>'Carmen de Apicalá','departamento_id'=>73]);
        City::create(['id'=>167,'ciudad'=>'Carmen de Carupa','departamento_id'=>25]);
        City::create(['id'=>168,'ciudad'=>'Carmen de Viboral','departamento_id'=>5]);
        City::create(['id'=>169,'ciudad'=>'Carmen del Darién (CURBARADÓ)','departamento_id'=>27]);
        City::create(['id'=>170,'ciudad'=>'Carolina','departamento_id'=>5]);
        City::create(['id'=>171,'ciudad'=>'Cartagena','departamento_id'=>13]);
        City::create(['id'=>172,'ciudad'=>'Cartagena del Chairá','departamento_id'=>18]);
        City::create(['id'=>173,'ciudad'=>'Cartago','departamento_id'=>76]);
        City::create(['id'=>174,'ciudad'=>'Carurú','departamento_id'=>97]);
        City::create(['id'=>175,'ciudad'=>'Casabianca','departamento_id'=>73]);
        City::create(['id'=>176,'ciudad'=>'Castilla la Nueva','departamento_id'=>50]);
        City::create(['id'=>177,'ciudad'=>'Caucasia','departamento_id'=>5]);
        City::create(['id'=>178,'ciudad'=>'Cañasgordas','departamento_id'=>5]);
        City::create(['id'=>179,'ciudad'=>'Cepita','departamento_id'=>68]);
        City::create(['id'=>180,'ciudad'=>'Cereté','departamento_id'=>23]);
        City::create(['id'=>181,'ciudad'=>'Cerinza','departamento_id'=>15]);
        City::create(['id'=>182,'ciudad'=>'Cerrito','departamento_id'=>68]);
        City::create(['id'=>183,'ciudad'=>'Cerro San Antonio','departamento_id'=>47]);
        City::create(['id'=>184,'ciudad'=>'Chachaguí','departamento_id'=>52]);
        City::create(['id'=>185,'ciudad'=>'Chaguaní','departamento_id'=>25]);
        City::create(['id'=>186,'ciudad'=>'Chalán','departamento_id'=>70]);
        City::create(['id'=>187,'ciudad'=>'Chaparral','departamento_id'=>73]);
        City::create(['id'=>188,'ciudad'=>'Charalá','departamento_id'=>68]);
        City::create(['id'=>189,'ciudad'=>'Charta','departamento_id'=>68]);
        City::create(['id'=>190,'ciudad'=>'Chigorodó','departamento_id'=>5]);
        City::create(['id'=>191,'ciudad'=>'Chima','departamento_id'=>68]);
        City::create(['id'=>192,'ciudad'=>'Chimichagua','departamento_id'=>20]);
        City::create(['id'=>193,'ciudad'=>'Chimá','departamento_id'=>23]);
        City::create(['id'=>194,'ciudad'=>'Chinavita','departamento_id'=>15]);
        City::create(['id'=>195,'ciudad'=>'Chinchiná','departamento_id'=>17]);
        City::create(['id'=>196,'ciudad'=>'Chinácota','departamento_id'=>54]);
        City::create(['id'=>197,'ciudad'=>'Chinú','departamento_id'=>23]);
        City::create(['id'=>198,'ciudad'=>'Chipaque','departamento_id'=>25]);
        City::create(['id'=>199,'ciudad'=>'Chipatá','departamento_id'=>68]);
        City::create(['id'=>200,'ciudad'=>'Chiquinquirá','departamento_id'=>15]);
        City::create(['id'=>201,'ciudad'=>'Chiriguaná','departamento_id'=>20]);
        City::create(['id'=>202,'ciudad'=>'Chiscas','departamento_id'=>15]);
        City::create(['id'=>203,'ciudad'=>'Chita','departamento_id'=>15]);
        City::create(['id'=>204,'ciudad'=>'Chitagá','departamento_id'=>54]);
        City::create(['id'=>205,'ciudad'=>'Chitaraque','departamento_id'=>15]);
        City::create(['id'=>206,'ciudad'=>'Chivatá','departamento_id'=>15]);
        City::create(['id'=>207,'ciudad'=>'Chivolo','departamento_id'=>47]);
        City::create(['id'=>208,'ciudad'=>'Choachí','departamento_id'=>25]);
        City::create(['id'=>209,'ciudad'=>'Chocontá','departamento_id'=>25]);
        City::create(['id'=>210,'ciudad'=>'Chámeza','departamento_id'=>85]);
        City::create(['id'=>211,'ciudad'=>'Chía','departamento_id'=>25]);
        City::create(['id'=>212,'ciudad'=>'Chíquiza','departamento_id'=>15]);
        City::create(['id'=>213,'ciudad'=>'Chívor','departamento_id'=>15]);
        City::create(['id'=>214,'ciudad'=>'Cicuco','departamento_id'=>13]);
        City::create(['id'=>215,'ciudad'=>'Cimitarra','departamento_id'=>68]);
        City::create(['id'=>216,'ciudad'=>'Circasia','departamento_id'=>63]);
        City::create(['id'=>217,'ciudad'=>'Cisneros','departamento_id'=>5]);
        City::create(['id'=>218,'ciudad'=>'Ciénaga','departamento_id'=>15]);
        City::create(['id'=>219,'ciudad'=>'Ciénaga','departamento_id'=>47]);
        City::create(['id'=>220,'ciudad'=>'Ciénaga de Oro','departamento_id'=>23]);
        City::create(['id'=>221,'ciudad'=>'Clemencia','departamento_id'=>13]);
        City::create(['id'=>222,'ciudad'=>'Cocorná','departamento_id'=>5]);
        City::create(['id'=>223,'ciudad'=>'Coello','departamento_id'=>73]);
        City::create(['id'=>224,'ciudad'=>'Cogua','departamento_id'=>25]);
        City::create(['id'=>225,'ciudad'=>'Colombia','departamento_id'=>41]);
        City::create(['id'=>226,'ciudad'=>'Colosó (Ricaurte)','departamento_id'=>70]);
        City::create(['id'=>227,'ciudad'=>'Colón','departamento_id'=>86]);
        City::create(['id'=>228,'ciudad'=>'Colón (Génova)','departamento_id'=>52]);
        City::create(['id'=>229,'ciudad'=>'Concepción','departamento_id'=>5]);
        City::create(['id'=>230,'ciudad'=>'Concepción','departamento_id'=>68]);
        City::create(['id'=>231,'ciudad'=>'Concordia','departamento_id'=>5]);
        City::create(['id'=>232,'ciudad'=>'Concordia','departamento_id'=>47]);
        City::create(['id'=>233,'ciudad'=>'Condoto','departamento_id'=>27]);
        City::create(['id'=>234,'ciudad'=>'Confines','departamento_id'=>68]);
        City::create(['id'=>235,'ciudad'=>'Consaca','departamento_id'=>52]);
        City::create(['id'=>236,'ciudad'=>'Contadero','departamento_id'=>52]);
        City::create(['id'=>237,'ciudad'=>'Contratación','departamento_id'=>68]);
        City::create(['id'=>238,'ciudad'=>'Convención','departamento_id'=>54]);
        City::create(['id'=>239,'ciudad'=>'Copacabana','departamento_id'=>5]);
        City::create(['id'=>240,'ciudad'=>'Coper','departamento_id'=>15]);
        City::create(['id'=>241,'ciudad'=>'Cordobá','departamento_id'=>63]);
        City::create(['id'=>242,'ciudad'=>'Corinto','departamento_id'=>19]);
        City::create(['id'=>243,'ciudad'=>'Coromoro','departamento_id'=>68]);
        City::create(['id'=>244,'ciudad'=>'Corozal','departamento_id'=>70]);
        City::create(['id'=>245,'ciudad'=>'Corrales','departamento_id'=>15]);
        City::create(['id'=>246,'ciudad'=>'Cota','departamento_id'=>25]);
        City::create(['id'=>247,'ciudad'=>'Cotorra','departamento_id'=>23]);
        City::create(['id'=>248,'ciudad'=>'Covarachía','departamento_id'=>15]);
        City::create(['id'=>249,'ciudad'=>'Coveñas','departamento_id'=>70]);
        City::create(['id'=>250,'ciudad'=>'Coyaima','departamento_id'=>73]);
        City::create(['id'=>251,'ciudad'=>'Cravo Norte','departamento_id'=>81]);
        City::create(['id'=>252,'ciudad'=>'Cuaspud (Carlosama)','departamento_id'=>52]);
        City::create(['id'=>253,'ciudad'=>'Cubarral','departamento_id'=>50]);
        City::create(['id'=>254,'ciudad'=>'Cubará','departamento_id'=>15]);
        City::create(['id'=>255,'ciudad'=>'Cucaita','departamento_id'=>15]);
        City::create(['id'=>256,'ciudad'=>'Cucunubá','departamento_id'=>25]);
        City::create(['id'=>257,'ciudad'=>'Cucutilla','departamento_id'=>54]);
        City::create(['id'=>258,'ciudad'=>'Cuitiva','departamento_id'=>15]);
        City::create(['id'=>259,'ciudad'=>'Cumaral','departamento_id'=>50]);
        City::create(['id'=>260,'ciudad'=>'Cumaribo','departamento_id'=>99]);
        City::create(['id'=>261,'ciudad'=>'Cumbal','departamento_id'=>52]);
        City::create(['id'=>262,'ciudad'=>'Cumbitara','departamento_id'=>52]);
        City::create(['id'=>263,'ciudad'=>'Cunday','departamento_id'=>73]);
        City::create(['id'=>264,'ciudad'=>'Curillo','departamento_id'=>18]);
        City::create(['id'=>265,'ciudad'=>'Curití','departamento_id'=>68]);
        City::create(['id'=>266,'ciudad'=>'Curumaní','departamento_id'=>20]);
        City::create(['id'=>267,'ciudad'=>'Cáceres','departamento_id'=>5]);
        City::create(['id'=>268,'ciudad'=>'Cáchira','departamento_id'=>54]);
        City::create(['id'=>269,'ciudad'=>'Cácota','departamento_id'=>54]);
        City::create(['id'=>270,'ciudad'=>'Cáqueza','departamento_id'=>25]);
        City::create(['id'=>271,'ciudad'=>'Cértegui','departamento_id'=>27]);
        City::create(['id'=>272,'ciudad'=>'Cómbita','departamento_id'=>15]);
        City::create(['id'=>273,'ciudad'=>'Córdoba','departamento_id'=>13]);
        City::create(['id'=>274,'ciudad'=>'Córdoba','departamento_id'=>52]);
        City::create(['id'=>275,'ciudad'=>'Cúcuta','departamento_id'=>54]);
        City::create(['id'=>276,'ciudad'=>'Dabeiba','departamento_id'=>5]);
        City::create(['id'=>277,'ciudad'=>'Dagua','departamento_id'=>76]);
        City::create(['id'=>278,'ciudad'=>'Dibulla','departamento_id'=>44]);
        City::create(['id'=>279,'ciudad'=>'Distracción','departamento_id'=>44]);
        City::create(['id'=>280,'ciudad'=>'Dolores','departamento_id'=>73]);
        City::create(['id'=>281,'ciudad'=>'Don Matías','departamento_id'=>5]);
        City::create(['id'=>282,'ciudad'=>'Dos Quebradas','departamento_id'=>66]);
        City::create(['id'=>283,'ciudad'=>'Duitama','departamento_id'=>15]);
        City::create(['id'=>284,'ciudad'=>'Durania','departamento_id'=>54]);
        City::create(['id'=>285,'ciudad'=>'Ebéjico','departamento_id'=>5]);
        City::create(['id'=>286,'ciudad'=>'El Bagre','departamento_id'=>5]);
        City::create(['id'=>287,'ciudad'=>'El Banco','departamento_id'=>47]);
        City::create(['id'=>288,'ciudad'=>'El Cairo','departamento_id'=>76]);
        City::create(['id'=>289,'ciudad'=>'El Calvario','departamento_id'=>50]);
        City::create(['id'=>290,'ciudad'=>'El Carmen','departamento_id'=>54]);
        City::create(['id'=>291,'ciudad'=>'El Carmen','departamento_id'=>68]);
        City::create(['id'=>292,'ciudad'=>'El Carmen de Atrato','departamento_id'=>27]);
        City::create(['id'=>293,'ciudad'=>'El Carmen de Bolívar','departamento_id'=>13]);
        City::create(['id'=>294,'ciudad'=>'El Castillo','departamento_id'=>50]);
        City::create(['id'=>295,'ciudad'=>'El Cerrito','departamento_id'=>76]);
        City::create(['id'=>296,'ciudad'=>'El Charco','departamento_id'=>52]);
        City::create(['id'=>297,'ciudad'=>'El Cocuy','departamento_id'=>15]);
        City::create(['id'=>298,'ciudad'=>'El Colegio','departamento_id'=>25]);
        City::create(['id'=>299,'ciudad'=>'El Copey','departamento_id'=>20]);
        City::create(['id'=>300,'ciudad'=>'El Doncello','departamento_id'=>18]);
        City::create(['id'=>301,'ciudad'=>'El Dorado','departamento_id'=>50]);
        City::create(['id'=>302,'ciudad'=>'El Dovio','departamento_id'=>76]);
        City::create(['id'=>303,'ciudad'=>'El Espino','departamento_id'=>15]);
        City::create(['id'=>304,'ciudad'=>'El Guacamayo','departamento_id'=>68]);
        City::create(['id'=>305,'ciudad'=>'El Guamo','departamento_id'=>13]);
        City::create(['id'=>306,'ciudad'=>'El Molino','departamento_id'=>44]);
        City::create(['id'=>307,'ciudad'=>'El Paso','departamento_id'=>20]);
        City::create(['id'=>308,'ciudad'=>'El Paujil','departamento_id'=>18]);
        City::create(['id'=>309,'ciudad'=>'El Peñol','departamento_id'=>52]);
        City::create(['id'=>310,'ciudad'=>'El Peñon','departamento_id'=>13]);
        City::create(['id'=>311,'ciudad'=>'El Peñon','departamento_id'=>68]);
        City::create(['id'=>312,'ciudad'=>'El Peñón','departamento_id'=>25]);
        City::create(['id'=>313,'ciudad'=>'El Piñon','departamento_id'=>47]);
        City::create(['id'=>314,'ciudad'=>'El Playón','departamento_id'=>68]);
        City::create(['id'=>315,'ciudad'=>'El Retorno','departamento_id'=>95]);
        City::create(['id'=>316,'ciudad'=>'El Retén','departamento_id'=>47]);
        City::create(['id'=>317,'ciudad'=>'El Roble','departamento_id'=>70]);
        City::create(['id'=>318,'ciudad'=>'El Rosal','departamento_id'=>25]);
        City::create(['id'=>319,'ciudad'=>'El Rosario','departamento_id'=>52]);
        City::create(['id'=>320,'ciudad'=>'El Tablón de Gómez','departamento_id'=>52]);
        City::create(['id'=>321,'ciudad'=>'El Tambo','departamento_id'=>19]);
        City::create(['id'=>322,'ciudad'=>'El Tambo','departamento_id'=>52]);
        City::create(['id'=>323,'ciudad'=>'El Tarra','departamento_id'=>54]);
        City::create(['id'=>324,'ciudad'=>'El Zulia','departamento_id'=>54]);
        City::create(['id'=>325,'ciudad'=>'El Águila','departamento_id'=>76]);
        City::create(['id'=>326,'ciudad'=>'Elías','departamento_id'=>41]);
        City::create(['id'=>327,'ciudad'=>'Encino','departamento_id'=>68]);
        City::create(['id'=>328,'ciudad'=>'Enciso','departamento_id'=>68]);
        City::create(['id'=>329,'ciudad'=>'Entrerríos','departamento_id'=>5]);
        City::create(['id'=>330,'ciudad'=>'Envigado','departamento_id'=>5]);
        City::create(['id'=>331,'ciudad'=>'Espinal','departamento_id'=>73]);
        City::create(['id'=>332,'ciudad'=>'Facatativá','departamento_id'=>25]);
        City::create(['id'=>333,'ciudad'=>'Falan','departamento_id'=>73]);
        City::create(['id'=>334,'ciudad'=>'Filadelfia','departamento_id'=>17]);
        City::create(['id'=>335,'ciudad'=>'Filandia','departamento_id'=>63]);
        City::create(['id'=>336,'ciudad'=>'Firavitoba','departamento_id'=>15]);
        City::create(['id'=>337,'ciudad'=>'Flandes','departamento_id'=>73]);
        City::create(['id'=>338,'ciudad'=>'Florencia','departamento_id'=>18]);
        City::create(['id'=>339,'ciudad'=>'Florencia','departamento_id'=>19]);
        City::create(['id'=>340,'ciudad'=>'Floresta','departamento_id'=>15]);
        City::create(['id'=>341,'ciudad'=>'Florida','departamento_id'=>76]);
        City::create(['id'=>342,'ciudad'=>'Floridablanca','departamento_id'=>68]);
        City::create(['id'=>343,'ciudad'=>'Florián','departamento_id'=>68]);
        City::create(['id'=>344,'ciudad'=>'Fonseca','departamento_id'=>44]);
        City::create(['id'=>345,'ciudad'=>'Fortúl','departamento_id'=>81]);
        City::create(['id'=>346,'ciudad'=>'Fosca','departamento_id'=>25]);
        City::create(['id'=>347,'ciudad'=>'Francisco Pizarro','departamento_id'=>52]);
        City::create(['id'=>348,'ciudad'=>'Fredonia','departamento_id'=>5]);
        City::create(['id'=>349,'ciudad'=>'Fresno','departamento_id'=>73]);
        City::create(['id'=>350,'ciudad'=>'Frontino','departamento_id'=>5]);
        City::create(['id'=>351,'ciudad'=>'Fuente de Oro','departamento_id'=>50]);
        City::create(['id'=>352,'ciudad'=>'Fundación','departamento_id'=>47]);
        City::create(['id'=>353,'ciudad'=>'Funes','departamento_id'=>52]);
        City::create(['id'=>354,'ciudad'=>'Funza','departamento_id'=>25]);
        City::create(['id'=>355,'ciudad'=>'Fusagasugá','departamento_id'=>25]);
        City::create(['id'=>356,'ciudad'=>'Fómeque','departamento_id'=>25]);
        City::create(['id'=>357,'ciudad'=>'Fúquene','departamento_id'=>25]);
        City::create(['id'=>358,'ciudad'=>'Gachalá','departamento_id'=>25]);
        City::create(['id'=>359,'ciudad'=>'Gachancipá','departamento_id'=>25]);
        City::create(['id'=>360,'ciudad'=>'Gachantivá','departamento_id'=>15]);
        City::create(['id'=>361,'ciudad'=>'Gachetá','departamento_id'=>25]);
        City::create(['id'=>362,'ciudad'=>'Galapa','departamento_id'=>8]);
        City::create(['id'=>363,'ciudad'=>'Galeras (Nueva Granada)','departamento_id'=>70]);
        City::create(['id'=>364,'ciudad'=>'Galán','departamento_id'=>68]);
        City::create(['id'=>365,'ciudad'=>'Gama','departamento_id'=>25]);
        City::create(['id'=>366,'ciudad'=>'Gamarra','departamento_id'=>20]);
        City::create(['id'=>367,'ciudad'=>'Garagoa','departamento_id'=>15]);
        City::create(['id'=>368,'ciudad'=>'Garzón','departamento_id'=>41]);
        City::create(['id'=>369,'ciudad'=>'Gigante','departamento_id'=>41]);
        City::create(['id'=>370,'ciudad'=>'Ginebra','departamento_id'=>76]);
        City::create(['id'=>371,'ciudad'=>'Giraldo','departamento_id'=>5]);
        City::create(['id'=>372,'ciudad'=>'Girardot','departamento_id'=>25]);
        City::create(['id'=>373,'ciudad'=>'Girardota','departamento_id'=>5]);
        City::create(['id'=>374,'ciudad'=>'Girón','departamento_id'=>68]);
        City::create(['id'=>375,'ciudad'=>'Gonzalez','departamento_id'=>20]);
        City::create(['id'=>376,'ciudad'=>'Gramalote','departamento_id'=>54]);
        City::create(['id'=>377,'ciudad'=>'Granada','departamento_id'=>5]);
        City::create(['id'=>378,'ciudad'=>'Granada','departamento_id'=>25]);
        City::create(['id'=>379,'ciudad'=>'Granada','departamento_id'=>50]);
        City::create(['id'=>380,'ciudad'=>'Guaca','departamento_id'=>68]);
        City::create(['id'=>381,'ciudad'=>'Guacamayas','departamento_id'=>15]);
        City::create(['id'=>382,'ciudad'=>'Guacarí','departamento_id'=>76]);
        City::create(['id'=>383,'ciudad'=>'Guachavés','departamento_id'=>52]);
        City::create(['id'=>384,'ciudad'=>'Guachené','departamento_id'=>19]);
        City::create(['id'=>385,'ciudad'=>'Guachetá','departamento_id'=>25]);
        City::create(['id'=>386,'ciudad'=>'Guachucal','departamento_id'=>52]);
        City::create(['id'=>387,'ciudad'=>'Guadalupe','departamento_id'=>5]);
        City::create(['id'=>388,'ciudad'=>'Guadalupe','departamento_id'=>41]);
        City::create(['id'=>389,'ciudad'=>'Guadalupe','departamento_id'=>68]);
        City::create(['id'=>390,'ciudad'=>'Guaduas','departamento_id'=>25]);
        City::create(['id'=>391,'ciudad'=>'Guaitarilla','departamento_id'=>52]);
        City::create(['id'=>392,'ciudad'=>'Gualmatán','departamento_id'=>52]);
        City::create(['id'=>393,'ciudad'=>'Guamal','departamento_id'=>47]);
        City::create(['id'=>394,'ciudad'=>'Guamal','departamento_id'=>50]);
        City::create(['id'=>395,'ciudad'=>'Guamo','departamento_id'=>73]);
        City::create(['id'=>396,'ciudad'=>'Guapota','departamento_id'=>68]);
        City::create(['id'=>397,'ciudad'=>'Guapí','departamento_id'=>19]);
        City::create(['id'=>398,'ciudad'=>'Guaranda','departamento_id'=>70]);
        City::create(['id'=>399,'ciudad'=>'Guarne','departamento_id'=>5]);
        City::create(['id'=>400,'ciudad'=>'Guasca','departamento_id'=>25]);
        City::create(['id'=>401,'ciudad'=>'Guatapé','departamento_id'=>5]);
        City::create(['id'=>402,'ciudad'=>'Guataquí','departamento_id'=>25]);
        City::create(['id'=>403,'ciudad'=>'Guatavita','departamento_id'=>25]);
        City::create(['id'=>404,'ciudad'=>'Guateque','departamento_id'=>15]);
        City::create(['id'=>405,'ciudad'=>'Guavatá','departamento_id'=>68]);
        City::create(['id'=>406,'ciudad'=>'Guayabal de Siquima','departamento_id'=>25]);
        City::create(['id'=>407,'ciudad'=>'Guayabetal','departamento_id'=>25]);
        City::create(['id'=>408,'ciudad'=>'Guayatá','departamento_id'=>15]);
        City::create(['id'=>409,'ciudad'=>'Guepsa','departamento_id'=>68]);
        City::create(['id'=>410,'ciudad'=>'Guicán','departamento_id'=>15]);
        City::create(['id'=>411,'ciudad'=>'Gutiérrez','departamento_id'=>25]);
        City::create(['id'=>412,'ciudad'=>'Guática','departamento_id'=>66]);
        City::create(['id'=>413,'ciudad'=>'Gámbita','departamento_id'=>68]);
        City::create(['id'=>414,'ciudad'=>'Gámeza','departamento_id'=>15]);
        City::create(['id'=>415,'ciudad'=>'Génova','departamento_id'=>63]);
        City::create(['id'=>416,'ciudad'=>'Gómez Plata','departamento_id'=>5]);
        City::create(['id'=>417,'ciudad'=>'Hacarí','departamento_id'=>54]);
        City::create(['id'=>418,'ciudad'=>'Hatillo de Loba','departamento_id'=>13]);
        City::create(['id'=>419,'ciudad'=>'Hato','departamento_id'=>68]);
        City::create(['id'=>420,'ciudad'=>'Hato Corozal','departamento_id'=>85]);
        City::create(['id'=>421,'ciudad'=>'Hatonuevo','departamento_id'=>44]);
        City::create(['id'=>422,'ciudad'=>'Heliconia','departamento_id'=>5]);
        City::create(['id'=>423,'ciudad'=>'Herrán','departamento_id'=>54]);
        City::create(['id'=>424,'ciudad'=>'Herveo','departamento_id'=>73]);
        City::create(['id'=>425,'ciudad'=>'Hispania','departamento_id'=>5]);
        City::create(['id'=>426,'ciudad'=>'Hobo','departamento_id'=>41]);
        City::create(['id'=>427,'ciudad'=>'Honda','departamento_id'=>73]);
        City::create(['id'=>428,'ciudad'=>'Ibagué','departamento_id'=>73]);
        City::create(['id'=>429,'ciudad'=>'Icononzo','departamento_id'=>73]);
        City::create(['id'=>430,'ciudad'=>'Iles','departamento_id'=>52]);
        City::create(['id'=>431,'ciudad'=>'Imúes','departamento_id'=>52]);
        City::create(['id'=>432,'ciudad'=>'Inzá','departamento_id'=>19]);
        City::create(['id'=>433,'ciudad'=>'Inírida','departamento_id'=>94]);
        City::create(['id'=>434,'ciudad'=>'Ipiales','departamento_id'=>52]);
        City::create(['id'=>435,'ciudad'=>'Isnos','departamento_id'=>41]);
        City::create(['id'=>436,'ciudad'=>'Istmina','departamento_id'=>27]);
        City::create(['id'=>437,'ciudad'=>'Itagüí','departamento_id'=>5]);
        City::create(['id'=>438,'ciudad'=>'Ituango','departamento_id'=>5]);
        City::create(['id'=>439,'ciudad'=>'Izá','departamento_id'=>15]);
        City::create(['id'=>440,'ciudad'=>'Jambaló','departamento_id'=>19]);
        City::create(['id'=>441,'ciudad'=>'Jamundí','departamento_id'=>76]);
        City::create(['id'=>442,'ciudad'=>'Jardín','departamento_id'=>5]);
        City::create(['id'=>443,'ciudad'=>'Jenesano','departamento_id'=>15]);
        City::create(['id'=>444,'ciudad'=>'Jericó','departamento_id'=>5]);
        City::create(['id'=>445,'ciudad'=>'Jericó','departamento_id'=>15]);
        City::create(['id'=>446,'ciudad'=>'Jerusalén','departamento_id'=>25]);
        City::create(['id'=>447,'ciudad'=>'Jesús María','departamento_id'=>68]);
        City::create(['id'=>448,'ciudad'=>'Jordán','departamento_id'=>68]);
        City::create(['id'=>449,'ciudad'=>'Juan de Acosta','departamento_id'=>8]);
        City::create(['id'=>450,'ciudad'=>'Junín','departamento_id'=>25]);
        City::create(['id'=>451,'ciudad'=>'Juradó','departamento_id'=>27]);
        City::create(['id'=>452,'ciudad'=>'La Apartada y La Frontera','departamento_id'=>23]);
        City::create(['id'=>453,'ciudad'=>'La Argentina','departamento_id'=>41]);
        City::create(['id'=>454,'ciudad'=>'La Belleza','departamento_id'=>68]);
        City::create(['id'=>455,'ciudad'=>'La Calera','departamento_id'=>25]);
        City::create(['id'=>456,'ciudad'=>'La Capilla','departamento_id'=>15]);
        City::create(['id'=>457,'ciudad'=>'La Ceja','departamento_id'=>5]);
        City::create(['id'=>458,'ciudad'=>'La Celia','departamento_id'=>66]);
        City::create(['id'=>459,'ciudad'=>'La Cruz','departamento_id'=>52]);
        City::create(['id'=>460,'ciudad'=>'La Cumbre','departamento_id'=>76]);
        City::create(['id'=>461,'ciudad'=>'La Dorada','departamento_id'=>17]);
        City::create(['id'=>462,'ciudad'=>'La Esperanza','departamento_id'=>54]);
        City::create(['id'=>463,'ciudad'=>'La Estrella','departamento_id'=>5]);
        City::create(['id'=>464,'ciudad'=>'La Florida','departamento_id'=>52]);
        City::create(['id'=>465,'ciudad'=>'La Gloria','departamento_id'=>20]);
        City::create(['id'=>466,'ciudad'=>'La Jagua de Ibirico','departamento_id'=>20]);
        City::create(['id'=>467,'ciudad'=>'La Jagua del Pilar','departamento_id'=>44]);
        City::create(['id'=>468,'ciudad'=>'La Llanada','departamento_id'=>52]);
        City::create(['id'=>469,'ciudad'=>'La Macarena','departamento_id'=>50]);
        City::create(['id'=>470,'ciudad'=>'La Merced','departamento_id'=>17]);
        City::create(['id'=>471,'ciudad'=>'La Mesa','departamento_id'=>25]);
        City::create(['id'=>472,'ciudad'=>'La Montañita','departamento_id'=>18]);
        City::create(['id'=>473,'ciudad'=>'La Palma','departamento_id'=>25]);
        City::create(['id'=>474,'ciudad'=>'La Paz','departamento_id'=>68]);
        City::create(['id'=>475,'ciudad'=>'La Paz (Robles)','departamento_id'=>20]);
        City::create(['id'=>476,'ciudad'=>'La Peña','departamento_id'=>25]);
        City::create(['id'=>477,'ciudad'=>'La Pintada','departamento_id'=>5]);
        City::create(['id'=>478,'ciudad'=>'La Plata','departamento_id'=>41]);
        City::create(['id'=>479,'ciudad'=>'La Playa','departamento_id'=>54]);
        City::create(['id'=>480,'ciudad'=>'La Primavera','departamento_id'=>99]);
        City::create(['id'=>481,'ciudad'=>'La Salina','departamento_id'=>85]);
        City::create(['id'=>482,'ciudad'=>'La Sierra','departamento_id'=>19]);
        City::create(['id'=>483,'ciudad'=>'La Tebaida','departamento_id'=>63]);
        City::create(['id'=>484,'ciudad'=>'La Tola','departamento_id'=>52]);
        City::create(['id'=>485,'ciudad'=>'La Unión','departamento_id'=>5]);
        City::create(['id'=>486,'ciudad'=>'La Unión','departamento_id'=>52]);
        City::create(['id'=>487,'ciudad'=>'La Unión','departamento_id'=>70]);
        City::create(['id'=>488,'ciudad'=>'La Unión','departamento_id'=>76]);
        City::create(['id'=>489,'ciudad'=>'La Uvita','departamento_id'=>15]);
        City::create(['id'=>490,'ciudad'=>'La Vega','departamento_id'=>19]);
        City::create(['id'=>491,'ciudad'=>'La Vega','departamento_id'=>25]);
        City::create(['id'=>492,'ciudad'=>'La Victoria','departamento_id'=>15]);
        City::create(['id'=>493,'ciudad'=>'La Victoria','departamento_id'=>17]);
        City::create(['id'=>494,'ciudad'=>'La Victoria','departamento_id'=>76]);
        City::create(['id'=>495,'ciudad'=>'La Virginia','departamento_id'=>66]);
        City::create(['id'=>496,'ciudad'=>'Labateca','departamento_id'=>54]);
        City::create(['id'=>497,'ciudad'=>'Labranzagrande','departamento_id'=>15]);
        City::create(['id'=>498,'ciudad'=>'Landázuri','departamento_id'=>68]);
        City::create(['id'=>499,'ciudad'=>'Lebrija','departamento_id'=>68]);
        City::create(['id'=>500,'ciudad'=>'Leiva','departamento_id'=>52]);
        City::create(['id'=>501,'ciudad'=>'Lejanías','departamento_id'=>50]);
        City::create(['id'=>502,'ciudad'=>'Lenguazaque','departamento_id'=>25]);
        City::create(['id'=>503,'ciudad'=>'Leticia','departamento_id'=>91]);
        City::create(['id'=>504,'ciudad'=>'Liborina','departamento_id'=>5]);
        City::create(['id'=>505,'ciudad'=>'Linares','departamento_id'=>52]);
        City::create(['id'=>506,'ciudad'=>'Lloró','departamento_id'=>27]);
        City::create(['id'=>507,'ciudad'=>'Lorica','departamento_id'=>23]);
        City::create(['id'=>508,'ciudad'=>'Los Córdobas','departamento_id'=>23]);
        City::create(['id'=>509,'ciudad'=>'Los Palmitos','departamento_id'=>70]);
        City::create(['id'=>510,'ciudad'=>'Los Patios','departamento_id'=>54]);
        City::create(['id'=>511,'ciudad'=>'Los Santos','departamento_id'=>68]);
        City::create(['id'=>512,'ciudad'=>'Lourdes','departamento_id'=>54]);
        City::create(['id'=>513,'ciudad'=>'Luruaco','departamento_id'=>8]);
        City::create(['id'=>514,'ciudad'=>'Lérida','departamento_id'=>73]);
        City::create(['id'=>515,'ciudad'=>'Líbano','departamento_id'=>73]);
        City::create(['id'=>516,'ciudad'=>'López (Micay)','departamento_id'=>19]);
        City::create(['id'=>517,'ciudad'=>'Macanal','departamento_id'=>15]);
        City::create(['id'=>518,'ciudad'=>'Macaravita','departamento_id'=>68]);
        City::create(['id'=>519,'ciudad'=>'Maceo','departamento_id'=>5]);
        City::create(['id'=>520,'ciudad'=>'Machetá','departamento_id'=>25]);
        City::create(['id'=>521,'ciudad'=>'Madrid','departamento_id'=>25]);
        City::create(['id'=>522,'ciudad'=>'Magangué','departamento_id'=>13]);
        City::create(['id'=>523,'ciudad'=>'Magüi (Payán)','departamento_id'=>52]);
        City::create(['id'=>524,'ciudad'=>'Mahates','departamento_id'=>13]);
        City::create(['id'=>525,'ciudad'=>'Maicao','departamento_id'=>44]);
        City::create(['id'=>526,'ciudad'=>'Majagual','departamento_id'=>70]);
        City::create(['id'=>527,'ciudad'=>'Malambo','departamento_id'=>8]);
        City::create(['id'=>528,'ciudad'=>'Mallama (Piedrancha)','departamento_id'=>52]);
        City::create(['id'=>529,'ciudad'=>'Manatí','departamento_id'=>8]);
        City::create(['id'=>530,'ciudad'=>'Manaure','departamento_id'=>44]);
        City::create(['id'=>531,'ciudad'=>'Manaure Balcón del Cesar','departamento_id'=>20]);
        City::create(['id'=>532,'ciudad'=>'Manizales','departamento_id'=>17]);
        City::create(['id'=>533,'ciudad'=>'Manta','departamento_id'=>25]);
        City::create(['id'=>534,'ciudad'=>'Manzanares','departamento_id'=>17]);
        City::create(['id'=>535,'ciudad'=>'Maní','departamento_id'=>85]);
        City::create(['id'=>536,'ciudad'=>'Mapiripan','departamento_id'=>50]);
        City::create(['id'=>537,'ciudad'=>'Margarita','departamento_id'=>13]);
        City::create(['id'=>538,'ciudad'=>'Marinilla','departamento_id'=>5]);
        City::create(['id'=>539,'ciudad'=>'Maripí','departamento_id'=>15]);
        City::create(['id'=>540,'ciudad'=>'Mariquita','departamento_id'=>73]);
        City::create(['id'=>541,'ciudad'=>'Marmato','departamento_id'=>17]);
        City::create(['id'=>542,'ciudad'=>'Marquetalia','departamento_id'=>17]);
        City::create(['id'=>543,'ciudad'=>'Marsella','departamento_id'=>66]);
        City::create(['id'=>544,'ciudad'=>'Marulanda','departamento_id'=>17]);
        City::create(['id'=>545,'ciudad'=>'María la Baja','departamento_id'=>13]);
        City::create(['id'=>546,'ciudad'=>'Matanza','departamento_id'=>68]);
        City::create(['id'=>547,'ciudad'=>'Medellín','departamento_id'=>5]);
        City::create(['id'=>548,'ciudad'=>'Medina','departamento_id'=>25]);
        City::create(['id'=>549,'ciudad'=>'Medio Atrato','departamento_id'=>27]);
        City::create(['id'=>550,'ciudad'=>'Medio Baudó','departamento_id'=>27]);
        City::create(['id'=>551,'ciudad'=>'Medio San Juan (ANDAGOYA)','departamento_id'=>27]);
        City::create(['id'=>552,'ciudad'=>'Melgar','departamento_id'=>73]);
        City::create(['id'=>553,'ciudad'=>'Mercaderes','departamento_id'=>19]);
        City::create(['id'=>554,'ciudad'=>'Mesetas','departamento_id'=>50]);
        City::create(['id'=>555,'ciudad'=>'Milán','departamento_id'=>18]);
        City::create(['id'=>556,'ciudad'=>'Miraflores','departamento_id'=>15]);
        City::create(['id'=>557,'ciudad'=>'Miraflores','departamento_id'=>95]);
        City::create(['id'=>558,'ciudad'=>'Miranda','departamento_id'=>19]);
        City::create(['id'=>559,'ciudad'=>'Mistrató','departamento_id'=>66]);
        City::create(['id'=>560,'ciudad'=>'Mitú','departamento_id'=>97]);
        City::create(['id'=>561,'ciudad'=>'Mocoa','departamento_id'=>86]);
        City::create(['id'=>562,'ciudad'=>'Mogotes','departamento_id'=>68]);
        City::create(['id'=>563,'ciudad'=>'Molagavita','departamento_id'=>68]);
        City::create(['id'=>564,'ciudad'=>'Momil','departamento_id'=>23]);
        City::create(['id'=>565,'ciudad'=>'Mompós','departamento_id'=>13]);
        City::create(['id'=>566,'ciudad'=>'Mongua','departamento_id'=>15]);
        City::create(['id'=>567,'ciudad'=>'Monguí','departamento_id'=>15]);
        City::create(['id'=>568,'ciudad'=>'Moniquirá','departamento_id'=>15]);
        City::create(['id'=>569,'ciudad'=>'Montebello','departamento_id'=>5]);
        City::create(['id'=>570,'ciudad'=>'Montecristo','departamento_id'=>13]);
        City::create(['id'=>571,'ciudad'=>'Montelíbano','departamento_id'=>23]);
        City::create(['id'=>572,'ciudad'=>'Montenegro','departamento_id'=>63]);
        City::create(['id'=>573,'ciudad'=>'Monteria','departamento_id'=>23]);
        City::create(['id'=>574,'ciudad'=>'Monterrey','departamento_id'=>85]);
        City::create(['id'=>575,'ciudad'=>'Morales','departamento_id'=>13]);
        City::create(['id'=>576,'ciudad'=>'Morales','departamento_id'=>19]);
        City::create(['id'=>577,'ciudad'=>'Morelia','departamento_id'=>18]);
        City::create(['id'=>578,'ciudad'=>'Morroa','departamento_id'=>70]);
        City::create(['id'=>579,'ciudad'=>'Mosquera','departamento_id'=>25]);
        City::create(['id'=>580,'ciudad'=>'Mosquera','departamento_id'=>52]);
        City::create(['id'=>581,'ciudad'=>'Motavita','departamento_id'=>15]);
        City::create(['id'=>582,'ciudad'=>'Moñitos','departamento_id'=>23]);
        City::create(['id'=>583,'ciudad'=>'Murillo','departamento_id'=>73]);
        City::create(['id'=>584,'ciudad'=>'Murindó','departamento_id'=>5]);
        City::create(['id'=>585,'ciudad'=>'Mutatá','departamento_id'=>5]);
        City::create(['id'=>586,'ciudad'=>'Mutiscua','departamento_id'=>54]);
        City::create(['id'=>587,'ciudad'=>'Muzo','departamento_id'=>15]);
        City::create(['id'=>588,'ciudad'=>'Málaga','departamento_id'=>68]);
        City::create(['id'=>589,'ciudad'=>'Nariño','departamento_id'=>5]);
        City::create(['id'=>590,'ciudad'=>'Nariño','departamento_id'=>25]);
        City::create(['id'=>591,'ciudad'=>'Nariño','departamento_id'=>52]);
        City::create(['id'=>592,'ciudad'=>'Natagaima','departamento_id'=>73]);
        City::create(['id'=>593,'ciudad'=>'Nechí','departamento_id'=>5]);
        City::create(['id'=>594,'ciudad'=>'Necoclí','departamento_id'=>5]);
        City::create(['id'=>595,'ciudad'=>'Neira','departamento_id'=>17]);
        City::create(['id'=>596,'ciudad'=>'Neiva','departamento_id'=>41]);
        City::create(['id'=>597,'ciudad'=>'Nemocón','departamento_id'=>25]);
        City::create(['id'=>598,'ciudad'=>'Nilo','departamento_id'=>25]);
        City::create(['id'=>599,'ciudad'=>'Nimaima','departamento_id'=>25]);
        City::create(['id'=>600,'ciudad'=>'Nobsa','departamento_id'=>15]);
        City::create(['id'=>601,'ciudad'=>'Nocaima','departamento_id'=>25]);
        City::create(['id'=>602,'ciudad'=>'Norcasia','departamento_id'=>17]);
        City::create(['id'=>603,'ciudad'=>'Norosí','departamento_id'=>13]);
        City::create(['id'=>604,'ciudad'=>'Novita','departamento_id'=>27]);
        City::create(['id'=>605,'ciudad'=>'Nueva Granada','departamento_id'=>47]);
        City::create(['id'=>606,'ciudad'=>'Nuevo Colón','departamento_id'=>15]);
        City::create(['id'=>607,'ciudad'=>'Nunchía','departamento_id'=>85]);
        City::create(['id'=>608,'ciudad'=>'Nuquí','departamento_id'=>27]);
        City::create(['id'=>609,'ciudad'=>'Nátaga','departamento_id'=>41]);
        City::create(['id'=>610,'ciudad'=>'Obando','departamento_id'=>76]);
        City::create(['id'=>611,'ciudad'=>'Ocamonte','departamento_id'=>68]);
        City::create(['id'=>612,'ciudad'=>'Ocaña','departamento_id'=>54]);
        City::create(['id'=>613,'ciudad'=>'Oiba','departamento_id'=>68]);
        City::create(['id'=>614,'ciudad'=>'Oicatá','departamento_id'=>15]);
        City::create(['id'=>615,'ciudad'=>'Olaya','departamento_id'=>5]);
        City::create(['id'=>616,'ciudad'=>'Olaya Herrera','departamento_id'=>52]);
        City::create(['id'=>617,'ciudad'=>'Onzaga','departamento_id'=>68]);
        City::create(['id'=>618,'ciudad'=>'Oporapa','departamento_id'=>41]);
        City::create(['id'=>619,'ciudad'=>'Orito','departamento_id'=>86]);
        City::create(['id'=>620,'ciudad'=>'Orocué','departamento_id'=>85]);
        City::create(['id'=>621,'ciudad'=>'Ortega','departamento_id'=>73]);
        City::create(['id'=>622,'ciudad'=>'Ospina','departamento_id'=>52]);
        City::create(['id'=>623,'ciudad'=>'Otanche','departamento_id'=>15]);
        City::create(['id'=>624,'ciudad'=>'Ovejas','departamento_id'=>70]);
        City::create(['id'=>625,'ciudad'=>'Pachavita','departamento_id'=>15]);
        City::create(['id'=>626,'ciudad'=>'Pacho','departamento_id'=>25]);
        City::create(['id'=>627,'ciudad'=>'Padilla','departamento_id'=>19]);
        City::create(['id'=>628,'ciudad'=>'Paicol','departamento_id'=>41]);
        City::create(['id'=>629,'ciudad'=>'Pailitas','departamento_id'=>20]);
        City::create(['id'=>630,'ciudad'=>'Paime','departamento_id'=>25]);
        City::create(['id'=>631,'ciudad'=>'Paipa','departamento_id'=>15]);
        City::create(['id'=>632,'ciudad'=>'Pajarito','departamento_id'=>15]);
        City::create(['id'=>633,'ciudad'=>'Palermo','departamento_id'=>41]);
        City::create(['id'=>634,'ciudad'=>'Palestina','departamento_id'=>17]);
        City::create(['id'=>635,'ciudad'=>'Palestina','departamento_id'=>41]);
        City::create(['id'=>636,'ciudad'=>'Palmar','departamento_id'=>68]);
        City::create(['id'=>637,'ciudad'=>'Palmar de Varela','departamento_id'=>8]);
        City::create(['id'=>638,'ciudad'=>'Palmas del Socorro','departamento_id'=>68]);
        City::create(['id'=>639,'ciudad'=>'Palmira','departamento_id'=>76]);
        City::create(['id'=>640,'ciudad'=>'Palmito','departamento_id'=>70]);
        City::create(['id'=>641,'ciudad'=>'Palocabildo','departamento_id'=>73]);
        City::create(['id'=>642,'ciudad'=>'Pamplona','departamento_id'=>54]);
        City::create(['id'=>643,'ciudad'=>'Pamplonita','departamento_id'=>54]);
        City::create(['id'=>644,'ciudad'=>'Pandi','departamento_id'=>25]);
        City::create(['id'=>645,'ciudad'=>'Panqueba','departamento_id'=>15]);
        City::create(['id'=>646,'ciudad'=>'Paratebueno','departamento_id'=>25]);
        City::create(['id'=>647,'ciudad'=>'Pasca','departamento_id'=>25]);
        City::create(['id'=>648,'ciudad'=>'Patía (El Bordo)','departamento_id'=>19]);
        City::create(['id'=>649,'ciudad'=>'Pauna','departamento_id'=>15]);
        City::create(['id'=>650,'ciudad'=>'Paya','departamento_id'=>15]);
        City::create(['id'=>651,'ciudad'=>'Paz de Ariporo','departamento_id'=>85]);
        City::create(['id'=>652,'ciudad'=>'Paz de Río','departamento_id'=>15]);
        City::create(['id'=>653,'ciudad'=>'Pedraza','departamento_id'=>47]);
        City::create(['id'=>654,'ciudad'=>'Pelaya','departamento_id'=>20]);
        City::create(['id'=>655,'ciudad'=>'Pensilvania','departamento_id'=>17]);
        City::create(['id'=>656,'ciudad'=>'Peque','departamento_id'=>5]);
        City::create(['id'=>657,'ciudad'=>'Pereira','departamento_id'=>66]);
        City::create(['id'=>658,'ciudad'=>'Pesca','departamento_id'=>15]);
        City::create(['id'=>659,'ciudad'=>'Peñol','departamento_id'=>5]);
        City::create(['id'=>660,'ciudad'=>'Piamonte','departamento_id'=>19]);
        City::create(['id'=>661,'ciudad'=>'Pie de Cuesta','departamento_id'=>68]);
        City::create(['id'=>662,'ciudad'=>'Piedras','departamento_id'=>73]);
        City::create(['id'=>663,'ciudad'=>'Piendamó','departamento_id'=>19]);
        City::create(['id'=>664,'ciudad'=>'Pijao','departamento_id'=>63]);
        City::create(['id'=>665,'ciudad'=>'Pijiño','departamento_id'=>47]);
        City::create(['id'=>666,'ciudad'=>'Pinchote','departamento_id'=>68]);
        City::create(['id'=>667,'ciudad'=>'Pinillos','departamento_id'=>13]);
        City::create(['id'=>668,'ciudad'=>'Piojo','departamento_id'=>8]);
        City::create(['id'=>669,'ciudad'=>'Pisva','departamento_id'=>15]);
        City::create(['id'=>670,'ciudad'=>'Pital','departamento_id'=>41]);
        City::create(['id'=>671,'ciudad'=>'Pitalito','departamento_id'=>41]);
        City::create(['id'=>672,'ciudad'=>'Pivijay','departamento_id'=>47]);
        City::create(['id'=>673,'ciudad'=>'Planadas','departamento_id'=>73]);
        City::create(['id'=>674,'ciudad'=>'Planeta Rica','departamento_id'=>23]);
        City::create(['id'=>675,'ciudad'=>'Plato','departamento_id'=>47]);
        City::create(['id'=>676,'ciudad'=>'Policarpa','departamento_id'=>52]);
        City::create(['id'=>677,'ciudad'=>'Polonuevo','departamento_id'=>8]);
        City::create(['id'=>678,'ciudad'=>'Ponedera','departamento_id'=>8]);
        City::create(['id'=>679,'ciudad'=>'Popayán','departamento_id'=>19]);
        City::create(['id'=>680,'ciudad'=>'Pore','departamento_id'=>85]);
        City::create(['id'=>681,'ciudad'=>'Potosí','departamento_id'=>52]);
        City::create(['id'=>682,'ciudad'=>'Pradera','departamento_id'=>76]);
        City::create(['id'=>683,'ciudad'=>'Prado','departamento_id'=>73]);
        City::create(['id'=>684,'ciudad'=>'Providencia','departamento_id'=>52]);
        City::create(['id'=>685,'ciudad'=>'Providencia','departamento_id'=>88]);
        City::create(['id'=>686,'ciudad'=>'Pueblo Bello','departamento_id'=>20]);
        City::create(['id'=>687,'ciudad'=>'Pueblo Nuevo','departamento_id'=>23]);
        City::create(['id'=>688,'ciudad'=>'Pueblo Rico','departamento_id'=>66]);
        City::create(['id'=>689,'ciudad'=>'Pueblorrico','departamento_id'=>5]);
        City::create(['id'=>690,'ciudad'=>'Puebloviejo','departamento_id'=>47]);
        City::create(['id'=>691,'ciudad'=>'Puente Nacional','departamento_id'=>68]);
        City::create(['id'=>692,'ciudad'=>'Puerres','departamento_id'=>52]);
        City::create(['id'=>693,'ciudad'=>'Puerto Asís','departamento_id'=>86]);
        City::create(['id'=>694,'ciudad'=>'Puerto Berrío','departamento_id'=>5]);
        City::create(['id'=>695,'ciudad'=>'Puerto Boyacá','departamento_id'=>15]);
        City::create(['id'=>696,'ciudad'=>'Puerto Caicedo','departamento_id'=>86]);
        City::create(['id'=>697,'ciudad'=>'Puerto Carreño','departamento_id'=>99]);
        City::create(['id'=>698,'ciudad'=>'Puerto Colombia','departamento_id'=>8]);
        City::create(['id'=>699,'ciudad'=>'Puerto Concordia','departamento_id'=>50]);
        City::create(['id'=>700,'ciudad'=>'Puerto Escondido','departamento_id'=>23]);
        City::create(['id'=>701,'ciudad'=>'Puerto Gaitán','departamento_id'=>50]);
        City::create(['id'=>702,'ciudad'=>'Puerto Guzmán','departamento_id'=>86]);
        City::create(['id'=>703,'ciudad'=>'Puerto Leguízamo','departamento_id'=>86]);
        City::create(['id'=>704,'ciudad'=>'Puerto Libertador','departamento_id'=>23]);
        City::create(['id'=>705,'ciudad'=>'Puerto Lleras','departamento_id'=>50]);
        City::create(['id'=>706,'ciudad'=>'Puerto López','departamento_id'=>50]);
        City::create(['id'=>707,'ciudad'=>'Puerto Nare','departamento_id'=>5]);
        City::create(['id'=>708,'ciudad'=>'Puerto Nariño','departamento_id'=>91]);
        City::create(['id'=>709,'ciudad'=>'Puerto Parra','departamento_id'=>68]);
        City::create(['id'=>710,'ciudad'=>'Puerto Rico','departamento_id'=>18]);
        City::create(['id'=>711,'ciudad'=>'Puerto Rico','departamento_id'=>50]);
        City::create(['id'=>712,'ciudad'=>'Puerto Rondón','departamento_id'=>81]);
        City::create(['id'=>713,'ciudad'=>'Puerto Salgar','departamento_id'=>25]);
        City::create(['id'=>714,'ciudad'=>'Puerto Santander','departamento_id'=>54]);
        City::create(['id'=>715,'ciudad'=>'Puerto Tejada','departamento_id'=>19]);
        City::create(['id'=>716,'ciudad'=>'Puerto Triunfo','departamento_id'=>5]);
        City::create(['id'=>717,'ciudad'=>'Puerto Wilches','departamento_id'=>68]);
        City::create(['id'=>718,'ciudad'=>'Pulí','departamento_id'=>25]);
        City::create(['id'=>719,'ciudad'=>'Pupiales','departamento_id'=>52]);
        City::create(['id'=>720,'ciudad'=>'Puracé (Coconuco)','departamento_id'=>19]);
        City::create(['id'=>721,'ciudad'=>'Purificación','departamento_id'=>73]);
        City::create(['id'=>722,'ciudad'=>'Purísima','departamento_id'=>23]);
        City::create(['id'=>723,'ciudad'=>'Pácora','departamento_id'=>17]);
        City::create(['id'=>724,'ciudad'=>'Páez','departamento_id'=>15]);
        City::create(['id'=>725,'ciudad'=>'Páez (Belalcazar)','departamento_id'=>19]);
        City::create(['id'=>726,'ciudad'=>'Páramo','departamento_id'=>68]);
        City::create(['id'=>727,'ciudad'=>'Quebradanegra','departamento_id'=>25]);
        City::create(['id'=>728,'ciudad'=>'Quetame','departamento_id'=>25]);
        City::create(['id'=>729,'ciudad'=>'Quibdó','departamento_id'=>27]);
        City::create(['id'=>730,'ciudad'=>'Quimbaya','departamento_id'=>63]);
        City::create(['id'=>731,'ciudad'=>'Quinchía','departamento_id'=>66]);
        City::create(['id'=>732,'ciudad'=>'Quipama','departamento_id'=>15]);
        City::create(['id'=>733,'ciudad'=>'Quipile','departamento_id'=>25]);
        City::create(['id'=>734,'ciudad'=>'Ragonvalia','departamento_id'=>54]);
        City::create(['id'=>735,'ciudad'=>'Ramiriquí','departamento_id'=>15]);
        City::create(['id'=>736,'ciudad'=>'Recetor','departamento_id'=>85]);
        City::create(['id'=>737,'ciudad'=>'Regidor','departamento_id'=>13]);
        City::create(['id'=>738,'ciudad'=>'Remedios','departamento_id'=>5]);
        City::create(['id'=>739,'ciudad'=>'Remolino','departamento_id'=>47]);
        City::create(['id'=>740,'ciudad'=>'Repelón','departamento_id'=>8]);
        City::create(['id'=>741,'ciudad'=>'Restrepo','departamento_id'=>50]);
        City::create(['id'=>742,'ciudad'=>'Restrepo','departamento_id'=>76]);
        City::create(['id'=>743,'ciudad'=>'Retiro','departamento_id'=>5]);
        City::create(['id'=>744,'ciudad'=>'Ricaurte','departamento_id'=>25]);
        City::create(['id'=>745,'ciudad'=>'Ricaurte','departamento_id'=>52]);
        City::create(['id'=>746,'ciudad'=>'Rio Negro','departamento_id'=>68]);
        City::create(['id'=>747,'ciudad'=>'Rioblanco','departamento_id'=>73]);
        City::create(['id'=>748,'ciudad'=>'Riofrío','departamento_id'=>76]);
        City::create(['id'=>749,'ciudad'=>'Riohacha','departamento_id'=>44]);
        City::create(['id'=>750,'ciudad'=>'Risaralda','departamento_id'=>17]);
        City::create(['id'=>751,'ciudad'=>'Rivera','departamento_id'=>41]);
        City::create(['id'=>752,'ciudad'=>'Roberto Payán (San José)','departamento_id'=>52]);
        City::create(['id'=>753,'ciudad'=>'Roldanillo','departamento_id'=>76]);
        City::create(['id'=>754,'ciudad'=>'Roncesvalles','departamento_id'=>73]);
        City::create(['id'=>755,'ciudad'=>'Rondón','departamento_id'=>15]);
        City::create(['id'=>756,'ciudad'=>'Rosas','departamento_id'=>19]);
        City::create(['id'=>757,'ciudad'=>'Rovira','departamento_id'=>73]);
        City::create(['id'=>758,'ciudad'=>'Ráquira','departamento_id'=>15]);
        City::create(['id'=>759,'ciudad'=>'Río Iró','departamento_id'=>27]);
        City::create(['id'=>760,'ciudad'=>'Río Quito','departamento_id'=>27]);
        City::create(['id'=>761,'ciudad'=>'Río Sucio','departamento_id'=>17]);
        City::create(['id'=>762,'ciudad'=>'Río Viejo','departamento_id'=>13]);
        City::create(['id'=>763,'ciudad'=>'Río de oro','departamento_id'=>20]);
        City::create(['id'=>764,'ciudad'=>'Ríonegro','departamento_id'=>5]);
        City::create(['id'=>765,'ciudad'=>'Ríosucio','departamento_id'=>27]);
        City::create(['id'=>766,'ciudad'=>'Sabana de Torres','departamento_id'=>68]);
        City::create(['id'=>767,'ciudad'=>'Sabanagrande','departamento_id'=>8]);
        City::create(['id'=>768,'ciudad'=>'Sabanalarga','departamento_id'=>5]);
        City::create(['id'=>769,'ciudad'=>'Sabanalarga','departamento_id'=>8]);
        City::create(['id'=>770,'ciudad'=>'Sabanalarga','departamento_id'=>85]);
        City::create(['id'=>771,'ciudad'=>'Sabanas de San Angel (SAN ANGEL)','departamento_id'=>47]);
        City::create(['id'=>772,'ciudad'=>'Sabaneta','departamento_id'=>5]);
        City::create(['id'=>773,'ciudad'=>'Saboyá','departamento_id'=>15]);
        City::create(['id'=>774,'ciudad'=>'Sahagún','departamento_id'=>23]);
        City::create(['id'=>775,'ciudad'=>'Saladoblanco','departamento_id'=>41]);
        City::create(['id'=>776,'ciudad'=>'Salamina','departamento_id'=>17]);
        City::create(['id'=>777,'ciudad'=>'Salamina','departamento_id'=>47]);
        City::create(['id'=>778,'ciudad'=>'Salazar','departamento_id'=>54]);
        City::create(['id'=>779,'ciudad'=>'Saldaña','departamento_id'=>73]);
        City::create(['id'=>780,'ciudad'=>'Salento','departamento_id'=>63]);
        City::create(['id'=>781,'ciudad'=>'Salgar','departamento_id'=>5]);
        City::create(['id'=>782,'ciudad'=>'Samacá','departamento_id'=>15]);
        City::create(['id'=>783,'ciudad'=>'Samaniego','departamento_id'=>52]);
        City::create(['id'=>784,'ciudad'=>'Samaná','departamento_id'=>17]);
        City::create(['id'=>785,'ciudad'=>'Sampués','departamento_id'=>70]);
        City::create(['id'=>786,'ciudad'=>'San Agustín','departamento_id'=>41]);
        City::create(['id'=>787,'ciudad'=>'San Alberto','departamento_id'=>20]);
        City::create(['id'=>788,'ciudad'=>'San Andrés','departamento_id'=>68]);
        City::create(['id'=>789,'ciudad'=>'San Andrés Sotavento','departamento_id'=>23]);
        City::create(['id'=>790,'ciudad'=>'San Andrés de Cuerquía','departamento_id'=>5]);
        City::create(['id'=>791,'ciudad'=>'San Antero','departamento_id'=>23]);
        City::create(['id'=>792,'ciudad'=>'San Antonio','departamento_id'=>73]);
        City::create(['id'=>793,'ciudad'=>'San Antonio de Tequendama','departamento_id'=>25]);
        City::create(['id'=>794,'ciudad'=>'San Benito','departamento_id'=>68]);
        City::create(['id'=>795,'ciudad'=>'San Benito Abad','departamento_id'=>70]);
        City::create(['id'=>796,'ciudad'=>'San Bernardo','departamento_id'=>25]);
        City::create(['id'=>797,'ciudad'=>'San Bernardo','departamento_id'=>52]);
        City::create(['id'=>798,'ciudad'=>'San Bernardo del Viento','departamento_id'=>23]);
        City::create(['id'=>799,'ciudad'=>'San Calixto','departamento_id'=>54]);
        City::create(['id'=>800,'ciudad'=>'San Carlos','departamento_id'=>5]);
        City::create(['id'=>801,'ciudad'=>'San Carlos','departamento_id'=>23]);
        City::create(['id'=>802,'ciudad'=>'San Carlos de Guaroa','departamento_id'=>50]);
        City::create(['id'=>803,'ciudad'=>'San Cayetano','departamento_id'=>25]);
        City::create(['id'=>804,'ciudad'=>'San Cayetano','departamento_id'=>54]);
        City::create(['id'=>805,'ciudad'=>'San Cristobal','departamento_id'=>13]);
        City::create(['id'=>806,'ciudad'=>'San Diego','departamento_id'=>20]);
        City::create(['id'=>807,'ciudad'=>'San Eduardo','departamento_id'=>15]);
        City::create(['id'=>808,'ciudad'=>'San Estanislao','departamento_id'=>13]);
        City::create(['id'=>809,'ciudad'=>'San Fernando','departamento_id'=>13]);
        City::create(['id'=>810,'ciudad'=>'San Francisco','departamento_id'=>5]);
        City::create(['id'=>811,'ciudad'=>'San Francisco','departamento_id'=>25]);
        City::create(['id'=>812,'ciudad'=>'San Francisco','departamento_id'=>86]);
        City::create(['id'=>813,'ciudad'=>'San Gíl','departamento_id'=>68]);
        City::create(['id'=>814,'ciudad'=>'San Jacinto','departamento_id'=>13]);
        City::create(['id'=>815,'ciudad'=>'San Jacinto del Cauca','departamento_id'=>13]);
        City::create(['id'=>816,'ciudad'=>'San Jerónimo','departamento_id'=>5]);
        City::create(['id'=>817,'ciudad'=>'San Joaquín','departamento_id'=>68]);
        City::create(['id'=>818,'ciudad'=>'San José','departamento_id'=>17]);
        City::create(['id'=>819,'ciudad'=>'San José de Miranda','departamento_id'=>68]);
        City::create(['id'=>820,'ciudad'=>'San José de Montaña','departamento_id'=>5]);
        City::create(['id'=>821,'ciudad'=>'San José de Pare','departamento_id'=>15]);
        City::create(['id'=>822,'ciudad'=>'San José de Uré','departamento_id'=>23]);
        City::create(['id'=>823,'ciudad'=>'San José del Fragua','departamento_id'=>18]);
        City::create(['id'=>824,'ciudad'=>'San José del Guaviare','departamento_id'=>95]);
        City::create(['id'=>825,'ciudad'=>'San José del Palmar','departamento_id'=>27]);
        City::create(['id'=>826,'ciudad'=>'San Juan de Arama','departamento_id'=>50]);
        City::create(['id'=>827,'ciudad'=>'San Juan de Betulia','departamento_id'=>70]);
        City::create(['id'=>828,'ciudad'=>'San Juan de Nepomuceno','departamento_id'=>13]);
        City::create(['id'=>829,'ciudad'=>'San Juan de Pasto','departamento_id'=>52]);
        City::create(['id'=>830,'ciudad'=>'San Juan de Río Seco','departamento_id'=>25]);
        City::create(['id'=>831,'ciudad'=>'San Juan de Urabá','departamento_id'=>5]);
        City::create(['id'=>832,'ciudad'=>'San Juan del Cesar','departamento_id'=>44]);
        City::create(['id'=>833,'ciudad'=>'San Juanito','departamento_id'=>50]);
        City::create(['id'=>834,'ciudad'=>'San Lorenzo','departamento_id'=>52]);
        City::create(['id'=>835,'ciudad'=>'San Luis','departamento_id'=>73]);
        City::create(['id'=>836,'ciudad'=>'San Luís','departamento_id'=>5]);
        City::create(['id'=>837,'ciudad'=>'San Luís de Gaceno','departamento_id'=>15]);
        City::create(['id'=>838,'ciudad'=>'San Luís de Palenque','departamento_id'=>85]);
        City::create(['id'=>839,'ciudad'=>'San Marcos','departamento_id'=>70]);
        City::create(['id'=>840,'ciudad'=>'San Martín','departamento_id'=>20]);
        City::create(['id'=>841,'ciudad'=>'San Martín','departamento_id'=>50]);
        City::create(['id'=>842,'ciudad'=>'San Martín de Loba','departamento_id'=>13]);
        City::create(['id'=>843,'ciudad'=>'San Mateo','departamento_id'=>15]);
        City::create(['id'=>844,'ciudad'=>'San Miguel','departamento_id'=>68]);
        City::create(['id'=>845,'ciudad'=>'San Miguel','departamento_id'=>86]);
        City::create(['id'=>846,'ciudad'=>'San Miguel de Sema','departamento_id'=>15]);
        City::create(['id'=>847,'ciudad'=>'San Onofre','departamento_id'=>70]);
        City::create(['id'=>848,'ciudad'=>'San Pablo','departamento_id'=>13]);
        City::create(['id'=>849,'ciudad'=>'San Pablo','departamento_id'=>52]);
        City::create(['id'=>850,'ciudad'=>'San Pablo de Borbur','departamento_id'=>15]);
        City::create(['id'=>851,'ciudad'=>'San Pedro','departamento_id'=>5]);
        City::create(['id'=>852,'ciudad'=>'San Pedro','departamento_id'=>70]);
        City::create(['id'=>853,'ciudad'=>'San Pedro','departamento_id'=>76]);
        City::create(['id'=>854,'ciudad'=>'San Pedro de Cartago','departamento_id'=>52]);
        City::create(['id'=>855,'ciudad'=>'San Pedro de Urabá','departamento_id'=>5]);
        City::create(['id'=>856,'ciudad'=>'San Pelayo','departamento_id'=>23]);
        City::create(['id'=>857,'ciudad'=>'San Rafael','departamento_id'=>5]);
        City::create(['id'=>858,'ciudad'=>'San Roque','departamento_id'=>5]);
        City::create(['id'=>859,'ciudad'=>'San Sebastián','departamento_id'=>19]);
        City::create(['id'=>860,'ciudad'=>'San Sebastián de Buenavista','departamento_id'=>47]);
        City::create(['id'=>861,'ciudad'=>'San Vicente','departamento_id'=>5]);
        City::create(['id'=>862,'ciudad'=>'San Vicente del Caguán','departamento_id'=>18]);
        City::create(['id'=>863,'ciudad'=>'San Vicente del Chucurí','departamento_id'=>68]);
        City::create(['id'=>864,'ciudad'=>'San Zenón','departamento_id'=>47]);
        City::create(['id'=>865,'ciudad'=>'Sandoná','departamento_id'=>52]);
        City::create(['id'=>866,'ciudad'=>'Santa Ana','departamento_id'=>47]);
        City::create(['id'=>867,'ciudad'=>'Santa Bárbara','departamento_id'=>5]);
        City::create(['id'=>868,'ciudad'=>'Santa Bárbara','departamento_id'=>68]);
        City::create(['id'=>869,'ciudad'=>'Santa Bárbara (Iscuandé)','departamento_id'=>52]);
        City::create(['id'=>870,'ciudad'=>'Santa Bárbara de Pinto','departamento_id'=>47]);
        City::create(['id'=>871,'ciudad'=>'Santa Catalina','departamento_id'=>13]);
        City::create(['id'=>872,'ciudad'=>'Santa Fé de Antioquia','departamento_id'=>5]);
        City::create(['id'=>873,'ciudad'=>'Santa Genoveva de Docorodó','departamento_id'=>27]);
        City::create(['id'=>874,'ciudad'=>'Santa Helena del Opón','departamento_id'=>68]);
        City::create(['id'=>875,'ciudad'=>'Santa Isabel','departamento_id'=>73]);
        City::create(['id'=>876,'ciudad'=>'Santa Lucía','departamento_id'=>8]);
        City::create(['id'=>877,'ciudad'=>'Santa Marta','departamento_id'=>47]);
        City::create(['id'=>878,'ciudad'=>'Santa María','departamento_id'=>15]);
        City::create(['id'=>879,'ciudad'=>'Santa María','departamento_id'=>41]);
        City::create(['id'=>880,'ciudad'=>'Santa Rosa','departamento_id'=>13]);
        City::create(['id'=>881,'ciudad'=>'Santa Rosa','departamento_id'=>19]);
        City::create(['id'=>882,'ciudad'=>'Santa Rosa de Cabal','departamento_id'=>66]);
        City::create(['id'=>883,'ciudad'=>'Santa Rosa de Osos','departamento_id'=>5]);
        City::create(['id'=>884,'ciudad'=>'Santa Rosa de Viterbo','departamento_id'=>15]);
        City::create(['id'=>885,'ciudad'=>'Santa Rosa del Sur','departamento_id'=>13]);
        City::create(['id'=>886,'ciudad'=>'Santa Rosalía','departamento_id'=>99]);
        City::create(['id'=>887,'ciudad'=>'Santa Sofía','departamento_id'=>15]);
        City::create(['id'=>888,'ciudad'=>'Santana','departamento_id'=>15]);
        City::create(['id'=>889,'ciudad'=>'Santander de Quilichao','departamento_id'=>19]);
        City::create(['id'=>890,'ciudad'=>'Santiago','departamento_id'=>54]);
        City::create(['id'=>891,'ciudad'=>'Santiago','departamento_id'=>86]);
        City::create(['id'=>892,'ciudad'=>'Santo Domingo','departamento_id'=>5]);
        City::create(['id'=>893,'ciudad'=>'Santo Tomás','departamento_id'=>8]);
        City::create(['id'=>894,'ciudad'=>'Santuario','departamento_id'=>5]);
        City::create(['id'=>895,'ciudad'=>'Santuario','departamento_id'=>66]);
        City::create(['id'=>896,'ciudad'=>'Sapuyes','departamento_id'=>52]);
        City::create(['id'=>897,'ciudad'=>'Saravena','departamento_id'=>81]);
        City::create(['id'=>898,'ciudad'=>'Sardinata','departamento_id'=>54]);
        City::create(['id'=>899,'ciudad'=>'Sasaima','departamento_id'=>25]);
        City::create(['id'=>900,'ciudad'=>'Sativanorte','departamento_id'=>15]);
        City::create(['id'=>901,'ciudad'=>'Sativasur','departamento_id'=>15]);
        City::create(['id'=>902,'ciudad'=>'Segovia','departamento_id'=>5]);
        City::create(['id'=>903,'ciudad'=>'Sesquilé','departamento_id'=>25]);
        City::create(['id'=>904,'ciudad'=>'Sevilla','departamento_id'=>76]);
        City::create(['id'=>905,'ciudad'=>'Siachoque','departamento_id'=>15]);
        City::create(['id'=>906,'ciudad'=>'Sibaté','departamento_id'=>25]);
        City::create(['id'=>907,'ciudad'=>'Sibundoy','departamento_id'=>86]);
        City::create(['id'=>908,'ciudad'=>'Silos','departamento_id'=>54]);
        City::create(['id'=>909,'ciudad'=>'Silvania','departamento_id'=>25]);
        City::create(['id'=>910,'ciudad'=>'Silvia','departamento_id'=>19]);
        City::create(['id'=>911,'ciudad'=>'Simacota','departamento_id'=>68]);
        City::create(['id'=>912,'ciudad'=>'Simijaca','departamento_id'=>25]);
        City::create(['id'=>913,'ciudad'=>'Simití','departamento_id'=>13]);
        City::create(['id'=>914,'ciudad'=>'Sincelejo','departamento_id'=>70]);
        City::create(['id'=>915,'ciudad'=>'Sincé','departamento_id'=>70]);
        City::create(['id'=>916,'ciudad'=>'Sipí','departamento_id'=>27]);
        City::create(['id'=>917,'ciudad'=>'Sitionuevo','departamento_id'=>47]);
        City::create(['id'=>918,'ciudad'=>'Soacha','departamento_id'=>25]);
        City::create(['id'=>919,'ciudad'=>'Soatá','departamento_id'=>15]);
        City::create(['id'=>920,'ciudad'=>'Socha','departamento_id'=>15]);
        City::create(['id'=>921,'ciudad'=>'Socorro','departamento_id'=>68]);
        City::create(['id'=>922,'ciudad'=>'Socotá','departamento_id'=>15]);
        City::create(['id'=>923,'ciudad'=>'Sogamoso','departamento_id'=>15]);
        City::create(['id'=>924,'ciudad'=>'Solano','departamento_id'=>18]);
        City::create(['id'=>925,'ciudad'=>'Soledad','departamento_id'=>8]);
        City::create(['id'=>926,'ciudad'=>'Solita','departamento_id'=>18]);
        City::create(['id'=>927,'ciudad'=>'Somondoco','departamento_id'=>15]);
        City::create(['id'=>928,'ciudad'=>'Sonsón','departamento_id'=>5]);
        City::create(['id'=>929,'ciudad'=>'Sopetrán','departamento_id'=>5]);
        City::create(['id'=>930,'ciudad'=>'Soplaviento','departamento_id'=>13]);
        City::create(['id'=>931,'ciudad'=>'Sopó','departamento_id'=>25]);
        City::create(['id'=>932,'ciudad'=>'Sora','departamento_id'=>15]);
        City::create(['id'=>933,'ciudad'=>'Soracá','departamento_id'=>15]);
        City::create(['id'=>934,'ciudad'=>'Sotaquirá','departamento_id'=>15]);
        City::create(['id'=>935,'ciudad'=>'Sotara (Paispamba)','departamento_id'=>19]);
        City::create(['id'=>936,'ciudad'=>'Sotomayor (Los Andes)','departamento_id'=>52]);
        City::create(['id'=>937,'ciudad'=>'Suaita','departamento_id'=>68]);
        City::create(['id'=>938,'ciudad'=>'Suan','departamento_id'=>8]);
        City::create(['id'=>939,'ciudad'=>'Suaza','departamento_id'=>41]);
        City::create(['id'=>940,'ciudad'=>'Subachoque','departamento_id'=>25]);
        City::create(['id'=>941,'ciudad'=>'Sucre','departamento_id'=>19]);
        City::create(['id'=>942,'ciudad'=>'Sucre','departamento_id'=>68]);
        City::create(['id'=>943,'ciudad'=>'Sucre','departamento_id'=>70]);
        City::create(['id'=>944,'ciudad'=>'Suesca','departamento_id'=>25]);
        City::create(['id'=>945,'ciudad'=>'Supatá','departamento_id'=>25]);
        City::create(['id'=>946,'ciudad'=>'Supía','departamento_id'=>17]);
        City::create(['id'=>947,'ciudad'=>'Suratá','departamento_id'=>68]);
        City::create(['id'=>948,'ciudad'=>'Susa','departamento_id'=>25]);
        City::create(['id'=>949,'ciudad'=>'Susacón','departamento_id'=>15]);
        City::create(['id'=>950,'ciudad'=>'Sutamarchán','departamento_id'=>15]);
        City::create(['id'=>951,'ciudad'=>'Sutatausa','departamento_id'=>25]);
        City::create(['id'=>952,'ciudad'=>'Sutatenza','departamento_id'=>15]);
        City::create(['id'=>953,'ciudad'=>'Suárez','departamento_id'=>19]);
        City::create(['id'=>954,'ciudad'=>'Suárez','departamento_id'=>73]);
        City::create(['id'=>955,'ciudad'=>'Sácama','departamento_id'=>85]);
        City::create(['id'=>956,'ciudad'=>'Sáchica','departamento_id'=>15]);
        City::create(['id'=>957,'ciudad'=>'Tabio','departamento_id'=>25]);
        City::create(['id'=>958,'ciudad'=>'Tadó','departamento_id'=>27]);
        City::create(['id'=>959,'ciudad'=>'Talaigua Nuevo','departamento_id'=>13]);
        City::create(['id'=>960,'ciudad'=>'Tamalameque','departamento_id'=>20]);
        City::create(['id'=>961,'ciudad'=>'Tame','departamento_id'=>81]);
        City::create(['id'=>962,'ciudad'=>'Taminango','departamento_id'=>52]);
        City::create(['id'=>963,'ciudad'=>'Tangua','departamento_id'=>52]);
        City::create(['id'=>964,'ciudad'=>'Taraira','departamento_id'=>97]);
        City::create(['id'=>965,'ciudad'=>'Tarazá','departamento_id'=>5]);
        City::create(['id'=>966,'ciudad'=>'Tarqui','departamento_id'=>41]);
        City::create(['id'=>967,'ciudad'=>'Tarso','departamento_id'=>5]);
        City::create(['id'=>968,'ciudad'=>'Tasco','departamento_id'=>15]);
        City::create(['id'=>969,'ciudad'=>'Tauramena','departamento_id'=>85]);
        City::create(['id'=>970,'ciudad'=>'Tausa','departamento_id'=>25]);
        City::create(['id'=>971,'ciudad'=>'Tello','departamento_id'=>41]);
        City::create(['id'=>972,'ciudad'=>'Tena','departamento_id'=>25]);
        City::create(['id'=>973,'ciudad'=>'Tenerife','departamento_id'=>47]);
        City::create(['id'=>974,'ciudad'=>'Tenjo','departamento_id'=>25]);
        City::create(['id'=>975,'ciudad'=>'Tenza','departamento_id'=>15]);
        City::create(['id'=>976,'ciudad'=>'Teorama','departamento_id'=>54]);
        City::create(['id'=>977,'ciudad'=>'Teruel','departamento_id'=>41]);
        City::create(['id'=>978,'ciudad'=>'Tesalia','departamento_id'=>41]);
        City::create(['id'=>979,'ciudad'=>'Tibacuy','departamento_id'=>25]);
        City::create(['id'=>980,'ciudad'=>'Tibaná','departamento_id'=>15]);
        City::create(['id'=>981,'ciudad'=>'Tibasosa','departamento_id'=>15]);
        City::create(['id'=>982,'ciudad'=>'Tibirita','departamento_id'=>25]);
        City::create(['id'=>983,'ciudad'=>'Tibú','departamento_id'=>54]);
        City::create(['id'=>984,'ciudad'=>'Tierralta','departamento_id'=>23]);
        City::create(['id'=>985,'ciudad'=>'Timaná','departamento_id'=>41]);
        City::create(['id'=>986,'ciudad'=>'Timbiquí','departamento_id'=>19]);
        City::create(['id'=>987,'ciudad'=>'Timbío','departamento_id'=>19]);
        City::create(['id'=>988,'ciudad'=>'Tinjacá','departamento_id'=>15]);
        City::create(['id'=>989,'ciudad'=>'Tipacoque','departamento_id'=>15]);
        City::create(['id'=>990,'ciudad'=>'Tiquisio (Puerto Rico)','departamento_id'=>13]);
        City::create(['id'=>991,'ciudad'=>'Titiribí','departamento_id'=>5]);
        City::create(['id'=>992,'ciudad'=>'Toca','departamento_id'=>15]);
        City::create(['id'=>993,'ciudad'=>'Tocaima','departamento_id'=>25]);
        City::create(['id'=>994,'ciudad'=>'Tocancipá','departamento_id'=>25]);
        City::create(['id'=>995,'ciudad'=>'Toguí','departamento_id'=>15]);
        City::create(['id'=>996,'ciudad'=>'Toledo','departamento_id'=>5]);
        City::create(['id'=>997,'ciudad'=>'Toledo','departamento_id'=>54]);
        City::create(['id'=>998,'ciudad'=>'Tolú','departamento_id'=>70]);
        City::create(['id'=>999,'ciudad'=>'Tolú Viejo','departamento_id'=>70]);
        City::create(['id'=>1000,'ciudad'=>'Tona','departamento_id'=>68]);
        City::create(['id'=>1001,'ciudad'=>'Topagá','departamento_id'=>15]);
        City::create(['id'=>1002,'ciudad'=>'Topaipí','departamento_id'=>25]);
        City::create(['id'=>1003,'ciudad'=>'Toribío','departamento_id'=>19]);
        City::create(['id'=>1004,'ciudad'=>'Toro','departamento_id'=>76]);
        City::create(['id'=>1005,'ciudad'=>'Tota','departamento_id'=>15]);
        City::create(['id'=>1006,'ciudad'=>'Totoró','departamento_id'=>19]);
        City::create(['id'=>1007,'ciudad'=>'Trinidad','departamento_id'=>85]);
        City::create(['id'=>1008,'ciudad'=>'Trujillo','departamento_id'=>76]);
        City::create(['id'=>1009,'ciudad'=>'Tubará','departamento_id'=>8]);
        City::create(['id'=>1010,'ciudad'=>'Tuchín','departamento_id'=>23]);
        City::create(['id'=>1011,'ciudad'=>'Tulúa','departamento_id'=>76]);
        City::create(['id'=>1012,'ciudad'=>'Tumaco','departamento_id'=>52]);
        City::create(['id'=>1013,'ciudad'=>'Tunja','departamento_id'=>15]);
        City::create(['id'=>1014,'ciudad'=>'Tunungua','departamento_id'=>15]);
        City::create(['id'=>1015,'ciudad'=>'Turbaco','departamento_id'=>13]);
        City::create(['id'=>1016,'ciudad'=>'Turbaná','departamento_id'=>13]);
        City::create(['id'=>1017,'ciudad'=>'Turbo','departamento_id'=>5]);
        City::create(['id'=>1018,'ciudad'=>'Turmequé','departamento_id'=>15]);
        City::create(['id'=>1019,'ciudad'=>'Tuta','departamento_id'=>15]);
        City::create(['id'=>1020,'ciudad'=>'Tutasá','departamento_id'=>15]);
        City::create(['id'=>1021,'ciudad'=>'Támara','departamento_id'=>85]);
        City::create(['id'=>1022,'ciudad'=>'Támesis','departamento_id'=>5]);
        City::create(['id'=>1023,'ciudad'=>'Túquerres','departamento_id'=>52]);
        City::create(['id'=>1024,'ciudad'=>'Ubalá','departamento_id'=>25]);
        City::create(['id'=>1025,'ciudad'=>'Ubaque','departamento_id'=>25]);
        City::create(['id'=>1026,'ciudad'=>'Ubaté','departamento_id'=>25]);
        City::create(['id'=>1027,'ciudad'=>'Ulloa','departamento_id'=>76]);
        City::create(['id'=>1028,'ciudad'=>'Une','departamento_id'=>25]);
        City::create(['id'=>1029,'ciudad'=>'Unguía','departamento_id'=>27]);
        City::create(['id'=>1030,'ciudad'=>'Unión Panamericana (ÁNIMAS)','departamento_id'=>27]);
        City::create(['id'=>1031,'ciudad'=>'Uramita','departamento_id'=>5]);
        City::create(['id'=>1032,'ciudad'=>'Uribe','departamento_id'=>50]);
        City::create(['id'=>1033,'ciudad'=>'Uribia','departamento_id'=>44]);
        City::create(['id'=>1034,'ciudad'=>'Urrao','departamento_id'=>5]);
        City::create(['id'=>1035,'ciudad'=>'Urumita','departamento_id'=>44]);
        City::create(['id'=>1036,'ciudad'=>'Usiacuri','departamento_id'=>8]);
        City::create(['id'=>1037,'ciudad'=>'Valdivia','departamento_id'=>5]);
        City::create(['id'=>1038,'ciudad'=>'Valencia','departamento_id'=>23]);
        City::create(['id'=>1039,'ciudad'=>'Valle de San José','departamento_id'=>68]);
        City::create(['id'=>1040,'ciudad'=>'Valle de San Juan','departamento_id'=>73]);
        City::create(['id'=>1041,'ciudad'=>'Valle del Guamuez','departamento_id'=>86]);
        City::create(['id'=>1042,'ciudad'=>'Valledupar','departamento_id'=>20]);
        City::create(['id'=>1043,'ciudad'=>'Valparaiso','departamento_id'=>5]);
        City::create(['id'=>1044,'ciudad'=>'Valparaiso','departamento_id'=>18]);
        City::create(['id'=>1045,'ciudad'=>'Vegachí','departamento_id'=>5]);
        City::create(['id'=>1046,'ciudad'=>'Venadillo','departamento_id'=>73]);
        City::create(['id'=>1047,'ciudad'=>'Venecia','departamento_id'=>5]);
        City::create(['id'=>1048,'ciudad'=>'Venecia (Ospina Pérez)','departamento_id'=>25]);
        City::create(['id'=>1049,'ciudad'=>'Ventaquemada','departamento_id'=>15]);
        City::create(['id'=>1050,'ciudad'=>'Vergara','departamento_id'=>25]);
        City::create(['id'=>1051,'ciudad'=>'Versalles','departamento_id'=>76]);
        City::create(['id'=>1052,'ciudad'=>'Vetas','departamento_id'=>68]);
        City::create(['id'=>1053,'ciudad'=>'Viani','departamento_id'=>25]);
        City::create(['id'=>1054,'ciudad'=>'Vigía del Fuerte','departamento_id'=>5]);
        City::create(['id'=>1055,'ciudad'=>'Vijes','departamento_id'=>76]);
        City::create(['id'=>1056,'ciudad'=>'Villa Caro','departamento_id'=>54]);
        City::create(['id'=>1057,'ciudad'=>'Villa Rica','departamento_id'=>19]);
        City::create(['id'=>1058,'ciudad'=>'Villa de Leiva','departamento_id'=>15]);
        City::create(['id'=>1059,'ciudad'=>'Villa del Rosario','departamento_id'=>54]);
        City::create(['id'=>1060,'ciudad'=>'Villagarzón','departamento_id'=>86]);
        City::create(['id'=>1061,'ciudad'=>'Villagómez','departamento_id'=>25]);
        City::create(['id'=>1062,'ciudad'=>'Villahermosa','departamento_id'=>73]);
        City::create(['id'=>1063,'ciudad'=>'Villamaría','departamento_id'=>17]);
        City::create(['id'=>1064,'ciudad'=>'Villanueva','departamento_id'=>13]);
        City::create(['id'=>1065,'ciudad'=>'Villanueva','departamento_id'=>44]);
        City::create(['id'=>1066,'ciudad'=>'Villanueva','departamento_id'=>68]);
        City::create(['id'=>1067,'ciudad'=>'Villanueva','departamento_id'=>85]);
        City::create(['id'=>1068,'ciudad'=>'Villapinzón','departamento_id'=>25]);
        City::create(['id'=>1069,'ciudad'=>'Villarrica','departamento_id'=>73]);
        City::create(['id'=>1070,'ciudad'=>'Villavicencio','departamento_id'=>50]);
        City::create(['id'=>1071,'ciudad'=>'Villavieja','departamento_id'=>41]);
        City::create(['id'=>1072,'ciudad'=>'Villeta','departamento_id'=>25]);
        City::create(['id'=>1073,'ciudad'=>'Viotá','departamento_id'=>25]);
        City::create(['id'=>1074,'ciudad'=>'Viracachá','departamento_id'=>15]);
        City::create(['id'=>1075,'ciudad'=>'Vista Hermosa','departamento_id'=>50]);
        City::create(['id'=>1076,'ciudad'=>'Viterbo','departamento_id'=>17]);
        City::create(['id'=>1077,'ciudad'=>'Vélez','departamento_id'=>68]);
        City::create(['id'=>1078,'ciudad'=>'Yacopí','departamento_id'=>25]);
        City::create(['id'=>1079,'ciudad'=>'Yacuanquer','departamento_id'=>52]);
        City::create(['id'=>1080,'ciudad'=>'Yaguará','departamento_id'=>41]);
        City::create(['id'=>1081,'ciudad'=>'Yalí','departamento_id'=>5]);
        City::create(['id'=>1082,'ciudad'=>'Yarumal','departamento_id'=>5]);
        City::create(['id'=>1083,'ciudad'=>'Yolombó','departamento_id'=>5]);
        City::create(['id'=>1084,'ciudad'=>'Yondó (Casabe)','departamento_id'=>5]);
        City::create(['id'=>1085,'ciudad'=>'Yopal','departamento_id'=>85]);
        City::create(['id'=>1086,'ciudad'=>'Yotoco','departamento_id'=>76]);
        City::create(['id'=>1087,'ciudad'=>'Yumbo','departamento_id'=>76]);
        City::create(['id'=>1088,'ciudad'=>'Zambrano','departamento_id'=>13]);
        City::create(['id'=>1089,'ciudad'=>'Zapatoca','departamento_id'=>68]);
        City::create(['id'=>1090,'ciudad'=>'Zapayán (PUNTA DE PIEDRAS)','departamento_id'=>47]);
        City::create(['id'=>1091,'ciudad'=>'Zaragoza','departamento_id'=>5]);
        City::create(['id'=>1092,'ciudad'=>'Zarzal','departamento_id'=>76]);
        City::create(['id'=>1093,'ciudad'=>'Zetaquirá','departamento_id'=>15]);
        City::create(['id'=>1094,'ciudad'=>'Zipacón','departamento_id'=>25]);
        City::create(['id'=>1095,'ciudad'=>'Zipaquirá','departamento_id'=>25]);
        City::create(['id'=>1096,'ciudad'=>'Zona Bananera (PRADO - SEVILLA)','departamento_id'=>47]);
        City::create(['id'=>1097,'ciudad'=>'Ábrego','departamento_id'=>54]);
        City::create(['id'=>1098,'ciudad'=>'Íquira','departamento_id'=>41]);
        City::create(['id'=>1099,'ciudad'=>'Úmbita','departamento_id'=>15]);
        City::create(['id'=>1100,'ciudad'=>'Útica','departamento_id'=>25]);
    }
}
